package co.com.arcosoft.modelo;

// Generated 16-jun-2015 17:19:01 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * AnaCultivo generated by hbm2java
 */
public class AnaCultivo implements java.io.Serializable {

	private Long anaCultId;
	private AnaSanVeg anaSanVeg;
	private Cultivo cultivo;
	public Long compania;
	private Date fechaCreacion;
	private Date fechaModificacion;

	public AnaCultivo() {
	}

	public AnaCultivo(Long anaCultId) {
		this.anaCultId = anaCultId;
	}

	public AnaCultivo(Long anaCultId, AnaSanVeg anaSanVeg, Cultivo cultivo, Long compania, Date fechaCreacion,
			Date fechaModificacion) {
		this.anaCultId = anaCultId;
		this.anaSanVeg = anaSanVeg;
		this.cultivo = cultivo;
		this.compania = compania;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
	}

	public Long getAnaCultId() {
		return this.anaCultId;
	}

	public void setAnaCultId(Long anaCultId) {
		this.anaCultId = anaCultId;
	}

	public AnaSanVeg getAnaSanVeg() {
		return this.anaSanVeg;
	}

	public void setAnaSanVeg(AnaSanVeg anaSanVeg) {
		this.anaSanVeg = anaSanVeg;
	}

	public Cultivo getCultivo() {
		return this.cultivo;
	}

	public void setCultivo(Cultivo cultivo) {
		this.cultivo = cultivo;
	}

	public Long getCompania() {
		return this.compania;
	}

	public void setCompania(Long compania) {
		this.compania = compania;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

}
