package co.com.arcosoft.modelo;

// Generated 08-sep-2015 22:35:03 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AnioFiscal generated by hbm2java
 */
public class AnioFiscal implements java.io.Serializable {

	private Long anioFiscalId;
	private String codigo;
	private String nombre;
	private Date fechaInicial;
	private Date fechaFinal;
	private String infoAdicional;
	private String infoAdicional2;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String estado;
	private Long compania;
	private Set<Nivel4> nivel4s = new HashSet<Nivel4>(0);
	private Set<Calendario> calendarios = new HashSet<Calendario>(0);
	private Set<Semana> semanas = new HashSet<Semana>(0);

	public AnioFiscal() {
	}

	public AnioFiscal(Long anioFiscalId) {
		this.anioFiscalId = anioFiscalId;
	}

	public AnioFiscal(Long anioFiscalId, String codigo, String nombre, Date fechaInicial, Date fechaFinal,
			String infoAdicional, String infoAdicional2, Date fechaCreacion, Date fechaModificacion, String estado,
			Set<Nivel4> nivel4s, Set<Calendario> calendarios, Long compania, Set<Semana> semanas) {
		this.anioFiscalId = anioFiscalId;
		this.codigo = codigo;
		this.nombre = nombre;
		this.fechaInicial = fechaInicial;
		this.fechaFinal = fechaFinal;
		this.infoAdicional = infoAdicional;
		this.infoAdicional2 = infoAdicional2;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.estado = estado;
		this.nivel4s = nivel4s;
		this.calendarios = calendarios;
		this.compania = compania;
		this.semanas = semanas;
	}

	public Set<Semana> getSemanas() {
		return semanas;
	}

	public void setSemanas(Set<Semana> semanas) {
		this.semanas = semanas;
	}

	public Long getAnioFiscalId() {
		return this.anioFiscalId;
	}

	public void setAnioFiscalId(Long anioFiscalId) {
		this.anioFiscalId = anioFiscalId;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaInicial() {
		return this.fechaInicial;
	}

	public void setFechaInicial(Date fechaInicial) {
		this.fechaInicial = fechaInicial;
	}

	public Date getFechaFinal() {
		return this.fechaFinal;
	}

	public void setFechaFinal(Date fechaFinal) {
		this.fechaFinal = fechaFinal;
	}

	public String getInfoAdicional() {
		return this.infoAdicional;
	}

	public void setInfoAdicional(String infoAdicional) {
		this.infoAdicional = infoAdicional;
	}

	public String getInfoAdicional2() {
		return this.infoAdicional2;
	}

	public void setInfoAdicional2(String infoAdicional2) {
		this.infoAdicional2 = infoAdicional2;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set<Nivel4> getNivel4s() {
		return this.nivel4s;
	}

	public void setNivel4s(Set<Nivel4> nivel4s) {
		this.nivel4s = nivel4s;
	}

	public Set<Calendario> getCalendarios() {
		return this.calendarios;
	}

	public void setCalendarios(Set<Calendario> calendarios) {
		this.calendarios = calendarios;
	}

	public Long getCompania() {
		return compania;
	}

	public void setCompania(Long compania) {
		this.compania = compania;
	}

}
