package co.com.arcosoft.modelo;

// Generated 08-sep-2015 22:35:03 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ConceptoNomina generated by hbm2java
 */
public class ConceptoNomina implements java.io.Serializable {

	private Long ceptoNominaId;
	private Long elementoCosto;
	private String codigo;
	private String nombre;
	public Long compania;
	private String infoAdicional;
	private String infoAdicional2;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String estado;
	private Double factorPrestacional;
	private String excluyeInteface;
	private String excluyeDominical;
	private String excluyeAuxilio;
	private String excluyeAdmon;

	private Set<LimiteCeptoNomina> limiteCeptoNominas = new HashSet<LimiteCeptoNomina>(0);
	private Set<DatPlanillaNomina> datPlanillaNominas = new HashSet<DatPlanillaNomina>(0);

	private Set<TarifaDeduccion> tarifaDeduccions = new HashSet<TarifaDeduccion>(0);
	private Set<TarifaOtrosDevengos> tarifaOtrosDevengoss = new HashSet<TarifaOtrosDevengos>(0);
	private Set<DatMantenimientoEquipoMec> datMantenimientoEquipoMecs = new HashSet<DatMantenimientoEquipoMec>(0);
	private Set<DatTransProdTrabajadores> datTransProdTrabajadoreses = new HashSet<DatTransProdTrabajadores>(0);
	private Set<DatNominaTrabajadorDet> datNominaTrabajadorDets = new HashSet<DatNominaTrabajadorDet>(0);

    private Set<DatPlanillaNominaDet> datPlanillaNominaDets = new HashSet<DatPlanillaNominaDet>(0);
    private Set<TarifaContratista> tarifaContratistas = new HashSet<TarifaContratista>(0);
    private Set<TarifaOtrosDevengos> tarifaOtrosDevengoses = new HashSet<TarifaOtrosDevengos>(0);
    private Set<TarifaProfesion> tarifaProfesions = new HashSet<TarifaProfesion>(0);
    private Long cuentaContable;
    private String esAusentismo;
    private Long cuentaContable2;
    private Long udadMedId;
    
    private String tipoConcepto;
    
    
    public ConceptoNomina() {
	}

	public ConceptoNomina(Long ceptoNominaId) {
		this.ceptoNominaId = ceptoNominaId;
	}

	public ConceptoNomina(Long ceptoNominaId, Long elementoCosto, String codigo, String nombre, Long compania,
			String infoAdicional, String infoAdicional2, Date fechaCreacion, Date fechaModificacion,
			Double factorPrestacional, String estado, Set<LimiteCeptoNomina> limiteCeptoNominas,
			Set<TarifaDeduccion> tarifaDeduccions, Set<DatPlanillaNominaDet> datPlanillaNominaDets,
			Set<TarifaOtrosDevengos> tarifaOtrosDevengoss, Set<DatPlanillaNomina> datPlanillaNominas,
			Set<DatMantenimientoEquipoMec> datMantenimientoEquipoMecs, String excluyeInteface, String excluyeDominical,
			String excluyeAuxilio, String excluyeAdmon, Set<DatTransProdTrabajadores> datTransProdTrabajadoreses,
			Set<DatNominaTrabajadorDet> datNominaTrabajadorDets,
		     
		     Set<TarifaContratista> tarifaContratistas ,
		     Set<TarifaOtrosDevengos> tarifaOtrosDevengoses ,
		     Set<TarifaProfesion> tarifaProfesions,
		     Long cuentaContable, String esAusentismo,
		     Long cuentaContabl2, Long udadMedId,
		     String tipoConcepto
		     

			) {
		this.cuentaContable2 = cuentaContable;
		this.udadMedId = udadMedId;
		
		this.ceptoNominaId = ceptoNominaId;
		this.elementoCosto = elementoCosto;
		this.codigo = codigo;
		this.nombre = nombre;
		this.compania = compania;
		this.infoAdicional = infoAdicional;
		this.infoAdicional2 = infoAdicional2;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.estado = estado;
		this.limiteCeptoNominas = limiteCeptoNominas;
		this.datPlanillaNominas = datPlanillaNominas;
		this.tarifaDeduccions = tarifaDeduccions;
		this.tarifaOtrosDevengoss = tarifaOtrosDevengoss;
		this.datMantenimientoEquipoMecs = datMantenimientoEquipoMecs;
		this.factorPrestacional = factorPrestacional;
		this.excluyeAuxilio = excluyeAuxilio;
		this.excluyeDominical = excluyeDominical;
		this.excluyeInteface = excluyeInteface;
		this.excluyeAdmon = excluyeAdmon;
		this.datTransProdTrabajadoreses = datTransProdTrabajadoreses;
		this.datNominaTrabajadorDets = datNominaTrabajadorDets;
	   this.tarifaContratistas = tarifaContratistas;
	   this.tarifaOtrosDevengoses = tarifaOtrosDevengoses;
	   this.tarifaProfesions = tarifaProfesions;
	   this.cuentaContable = cuentaContable;
	   this.esAusentismo= esAusentismo;
	   this.tipoConcepto = tipoConcepto;
	}

	
	
	public String getTipoConcepto() {
		return tipoConcepto;
	}

	public void setTipoConcepto(String tipoConcepto) {
		this.tipoConcepto = tipoConcepto;
	}

	/**
	 * @return the cuentaContable2
	 */
	public Long getCuentaContable2() {
		return cuentaContable2;
	}

	/**
	 * @param cuentaContable2 the cuentaContable2 to set
	 */
	public void setCuentaContable2(Long cuentaContable2) {
		this.cuentaContable2 = cuentaContable2;
	}

	/**
	 * @return the udadMedId
	 */
	public Long getUdadMedId() {
		return udadMedId;
	}

	/**
	 * @param udadMedId the udadMedId to set
	 */
	public void setUdadMedId(Long udadMedId) {
		this.udadMedId = udadMedId;
	}

	/**
	 * @return the esAusentismo
	 */
	public String getEsAusentismo() {
		return esAusentismo;
	}

	/**
	 * @param esAusentismo the esAusentismo to set
	 */
	public void setEsAusentismo(String esAusentismo) {
		this.esAusentismo = esAusentismo;
	}

	/**
	 * @return the cuentaContable
	 */
	public Long getCuentaContable() {
		return cuentaContable;
	}

	/**
	 * @param cuentaContable the cuentaContable to set
	 */
	public void setCuentaContable(Long cuentaContable) {
		this.cuentaContable = cuentaContable;
	}

	public Set<DatPlanillaNominaDet> getDatPlanillaNominaDets() {
		return datPlanillaNominaDets;
	}

	public void setDatPlanillaNominaDets(Set<DatPlanillaNominaDet> datPlanillaNominaDets) {
		this.datPlanillaNominaDets = datPlanillaNominaDets;
	}

	public Set<TarifaContratista> getTarifaContratistas() {
		return tarifaContratistas;
	}

	public void setTarifaContratistas(Set<TarifaContratista> tarifaContratistas) {
		this.tarifaContratistas = tarifaContratistas;
	}

	public Set<TarifaOtrosDevengos> getTarifaOtrosDevengoses() {
		return tarifaOtrosDevengoses;
	}

	public void setTarifaOtrosDevengoses(Set<TarifaOtrosDevengos> tarifaOtrosDevengoses) {
		this.tarifaOtrosDevengoses = tarifaOtrosDevengoses;
	}

	public Set<TarifaProfesion> getTarifaProfesions() {
		return tarifaProfesions;
	}

	public void setTarifaProfesions(Set<TarifaProfesion> tarifaProfesions) {
		this.tarifaProfesions = tarifaProfesions;
	}

	public Set<DatNominaTrabajadorDet> getDatNominaTrabajadorDets() {
		return datNominaTrabajadorDets;
	}

	public void setDatNominaTrabajadorDets(Set<DatNominaTrabajadorDet> datNominaTrabajadorDets) {
		this.datNominaTrabajadorDets = datNominaTrabajadorDets;
	}

	public Set<DatTransProdTrabajadores> getDatTransProdTrabajadoreses() {
		return datTransProdTrabajadoreses;
	}

	public void setDatTransProdTrabajadoreses(Set<DatTransProdTrabajadores> datTransProdTrabajadoreses) {
		this.datTransProdTrabajadoreses = datTransProdTrabajadoreses;
	}

	public String getExcluyeAdmon() {
		return excluyeAdmon;
	}

	public void setExcluyeAdmon(String excluyeAdmon) {
		this.excluyeAdmon = excluyeAdmon;
	}

	public String getExcluyeInteface() {
		return excluyeInteface;
	}

	public void setExcluyeInteface(String excluyeInteface) {
		this.excluyeInteface = excluyeInteface;
	}

	public String getExcluyeDominical() {
		return excluyeDominical;
	}

	public void setExcluyeDominical(String excluyeDominical) {
		this.excluyeDominical = excluyeDominical;
	}

	public String getExcluyeAuxilio() {
		return excluyeAuxilio;
	}

	public void setExcluyeAuxilio(String excluyeAuxilio) {
		this.excluyeAuxilio = excluyeAuxilio;
	}

	public Double getFactorPrestacional() {
		return factorPrestacional;
	}

	public void setFactorPrestacional(Double factorPrestacional) {
		this.factorPrestacional = factorPrestacional;
	}

	public Long getCeptoNominaId() {
		return this.ceptoNominaId;
	}

	public void setCeptoNominaId(Long ceptoNominaId) {
		this.ceptoNominaId = ceptoNominaId;
	}

	public Long getElementoCosto() {
		return this.elementoCosto;
	}

	public void setElementoCosto(Long elementoCosto) {
		this.elementoCosto = elementoCosto;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Long getCompania() {
		return this.compania;
	}

	public void setCompania(Long compania) {
		this.compania = compania;
	}

	public String getInfoAdicional() {
		return this.infoAdicional;
	}

	public void setInfoAdicional(String infoAdicional) {
		this.infoAdicional = infoAdicional;
	}

	public String getInfoAdicional2() {
		return this.infoAdicional2;
	}

	public void setInfoAdicional2(String infoAdicional2) {
		this.infoAdicional2 = infoAdicional2;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set<LimiteCeptoNomina> getLimiteCeptoNominas() {
		return this.limiteCeptoNominas;
	}

	public void setLimiteCeptoNominas(Set<LimiteCeptoNomina> limiteCeptoNominas) {
		this.limiteCeptoNominas = limiteCeptoNominas;
	}

	public Set<DatPlanillaNomina> getDatPlanillaNominas() {
		return this.datPlanillaNominas;
	}

	public void setDatPlanillaNominas(Set<DatPlanillaNomina> datPlanillaNominas) {
		this.datPlanillaNominas = datPlanillaNominas;
	}

	public Set<TarifaDeduccion> getTarifaDeduccions() {
		return tarifaDeduccions;
	}

	public void setTarifaDeduccions(Set<TarifaDeduccion> tarifaDeduccions) {
		this.tarifaDeduccions = tarifaDeduccions;
	}

	public Set<TarifaOtrosDevengos> getTarifaOtrosDevengoss() {
		return tarifaOtrosDevengoss;
	}

	public void setTarifaOtrosDevengoss(Set<TarifaOtrosDevengos> tarifaOtrosDevengoss) {
		this.tarifaOtrosDevengoss = tarifaOtrosDevengoss;
	}

	public Set<DatMantenimientoEquipoMec> getDatMantenimientoEquipoMecs() {
		return this.datMantenimientoEquipoMecs;
	}

	public void setDatMantenimientoEquipoMecs(Set<DatMantenimientoEquipoMec> datMantenimientoEquipoMecs) {
		this.datMantenimientoEquipoMecs = datMantenimientoEquipoMecs;
	}

}
