package co.com.arcosoft.modelo;

// Generated 08-sep-2015 22:35:03 by Hibernate Tools 4.0.0

/**
 * CostoRecurso generated by hbm2java
 */
public class CostoRecurso implements java.io.Serializable {

	private CostoRecursoId id;
	private UdadMed udadMed;
	private Recurso recurso;
	private ElementoCosto elementoCosto;

	public CostoRecurso() {
	}

	public CostoRecurso(CostoRecursoId id) {
		this.id = id;
	}

	public CostoRecurso(CostoRecursoId id, UdadMed udadMed, Recurso recurso, ElementoCosto elementoCosto) {
		this.id = id;
		this.udadMed = udadMed;
		this.recurso = recurso;
		this.elementoCosto = elementoCosto;
	}

	public CostoRecursoId getId() {
		return this.id;
	}

	public void setId(CostoRecursoId id) {
		this.id = id;
	}

	public UdadMed getUdadMed() {
		return this.udadMed;
	}

	public void setUdadMed(UdadMed udadMed) {
		this.udadMed = udadMed;
	}

	public Recurso getRecurso() {
		return this.recurso;
	}

	public void setRecurso(Recurso recurso) {
		this.recurso = recurso;
	}

	public ElementoCosto getElementoCosto() {
		return this.elementoCosto;
	}

	public void setElementoCosto(ElementoCosto elementoCosto) {
		this.elementoCosto = elementoCosto;
	}

}
