package co.com.arcosoft.modelo;

// Generated 17-mar-2015 15:25:33 by Hibernate Tools 4.0.0

/**
 * CultivoFitosanidad generated by hbm2java
 */
public class CultivoFitosanidad implements java.io.Serializable {

	private CultivoFitosanidadId id;
	private Cultivo cultivo;
	private Fitosanidad fitosanidad;

	public CultivoFitosanidad() {
	}

	public CultivoFitosanidad(CultivoFitosanidadId id, Cultivo cultivo, Fitosanidad fitosanidad) {
		this.id = id;
		this.cultivo = cultivo;
		this.fitosanidad = fitosanidad;
	}

	public CultivoFitosanidadId getId() {
		return this.id;
	}

	public void setId(CultivoFitosanidadId id) {
		this.id = id;
	}

	public Cultivo getCultivo() {
		return this.cultivo;
	}

	public void setCultivo(Cultivo cultivo) {
		this.cultivo = cultivo;
	}

	public Fitosanidad getFitosanidad() {
		return this.fitosanidad;
	}

	public void setFitosanidad(Fitosanidad fitosanidad) {
		this.fitosanidad = fitosanidad;
	}

}
