package co.com.arcosoft.modelo;

// Generated 08-sep-2015 22:35:03 by Hibernate Tools 4.0.0

/**
 * DatAplicProdDet generated by hbm2java
 */
public class DatAplicProdDet implements java.io.Serializable {

	private Long datProdDetId;
	private UdadMed udadMed;
	private Producto producto;
	private DatAplicProducto datAplicProducto;
	private Double dosis;
	private Double cantidadAplicada;
	private Double valorUnit;
	private Double costoTotal;
	private DatPlanLaborDet ordenTrabajo;
	private Nivel4 nivel4;
	private Nivel2 nivel2Id;
	private Labor laborId;
	private Almacen almacenId;
	private DatPlanillaNomina datPlanillaNominaId;
	private Double numTinas;
	private Long etapaId;
	private Long variedId;
	private Double edad;
	
	public DatAplicProdDet() {
	}

	public DatAplicProdDet(Long datProdDetId) {
		this.datProdDetId = datProdDetId;
	}

	public DatAplicProdDet(Long datProdDetId, UdadMed udadMed, Producto producto, DatAplicProducto datAplicProducto,
			Double dosis, Double cantidadAplicada, Double valorUnit, Double costoTotal, Nivel2 nivel2, Nivel4 nivel4,
			 DatPlanLaborDet ordenTrabajo,  Nivel2 nivel2Id,  Labor laborId, Almacen almacenId, DatPlanillaNomina datPlanillaNominaId
			, Double numTinas, Long etapaId, Long variedId, Double edad) {
		this.datProdDetId = datProdDetId;
		this.udadMed = udadMed;
		this.producto = producto;
		this.datAplicProducto = datAplicProducto;
		this.dosis = dosis;
		this.cantidadAplicada = cantidadAplicada;
		this.valorUnit = valorUnit;
		this.costoTotal = costoTotal;
		
		this.ordenTrabajo = ordenTrabajo;
		this.nivel2Id = nivel2Id;
		this.nivel4= nivel4;
		this.laborId=laborId;
		this.almacenId=almacenId;
		this.datPlanillaNominaId = datPlanillaNominaId;
		this.numTinas= numTinas;
		this.etapaId = etapaId;
		this.variedId= variedId;
		this.edad= edad;
	}
	
	

	public Double getEdad() {
		return edad;
	}

	public void setEdad(Double edad) {
		this.edad = edad;
	}

	public Long getEtapaId() {
		return etapaId;
	}

	public void setEtapaId(Long etapaId) {
		this.etapaId = etapaId;
	}

	public Long getVariedId() {
		return variedId;
	}

	public void setVariedId(Long variedId) {
		this.variedId = variedId;
	}

	public Double getNumTinas() {
		return numTinas;
	}

	public void setNumTinas(Double numTinas) {
		this.numTinas = numTinas;
	}

	public DatPlanillaNomina getDatPlanillaNominaId() {
		return datPlanillaNominaId;
	}

	public void setDatPlanillaNominaId(DatPlanillaNomina datPlanillaNominaId) {
		this.datPlanillaNominaId = datPlanillaNominaId;
	}

	public Almacen getAlmacenId() {
		return almacenId;
	}

	public void setAlmacenId(Almacen almacenId) {
		this.almacenId = almacenId;
	}

	public Nivel4 getNivel4() {
		return nivel4;
	}

	public void setNivel4(Nivel4 nivel4) {
		this.nivel4 = nivel4;
	}


	public DatPlanLaborDet getOrdenTrabajo() {
		return ordenTrabajo;
	}

	public void setOrdenTrabajo(DatPlanLaborDet ordenTrabajo) {
		this.ordenTrabajo = ordenTrabajo;
	}

	public Nivel2 getNivel2Id() {
		return nivel2Id;
	}

	public void setNivel2Id(Nivel2 nivel2Id) {
		this.nivel2Id = nivel2Id;
	}

	public Labor getLaborId() {
		return laborId;
	}

	public void setLaborId(Labor laborId) {
		this.laborId = laborId;
	}

	public Long getDatProdDetId() {
		return this.datProdDetId;
	}

	public void setDatProdDetId(Long datProdDetId) {
		this.datProdDetId = datProdDetId;
	}

	public UdadMed getUdadMed() {
		return this.udadMed;
	}

	public void setUdadMed(UdadMed udadMed) {
		this.udadMed = udadMed;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public DatAplicProducto getDatAplicProducto() {
		return this.datAplicProducto;
	}

	public void setDatAplicProducto(DatAplicProducto datAplicProducto) {
		this.datAplicProducto = datAplicProducto;
	}

	public Double getDosis() {
		return this.dosis;
	}

	public void setDosis(Double dosis) {
		this.dosis = dosis;
	}

	public Double getCantidadAplicada() {
		return this.cantidadAplicada;
	}

	public void setCantidadAplicada(Double cantidadAplicada) {
		this.cantidadAplicada = cantidadAplicada;
	}

	public Double getValorUnit() {
		return this.valorUnit;
	}

	public void setValorUnit(Double valorUnit) {
		this.valorUnit = valorUnit;
	}

	public Double getCostoTotal() {
		return this.costoTotal;
	}

	public void setCostoTotal(Double costoTotal) {
		this.costoTotal = costoTotal;
	}

}
