package co.com.arcosoft.modelo;
// Generated 24-ago-2016 15:04:52 by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * DatAbastCombustible generated by hbm2java
 */
public class DatAbastCombustible  implements java.io.Serializable {


     private Long datAbastCombustibleId;
     private TipoAbastecimiento tipoAbastecimiento;
     private Trabajador trabajador;
     private BombaAbastecimiento bombaAbastecimiento;
     private Equipo equipo;
     private Producto producto;
     private UdadMed udadMed;
     private CentCost centCost;
     private Long consecutivo;
     private Date fechaRegistro;
     private Long turnoCampoId;
     private Double conductor;
     private Double cantidad;
     private Double valorUnitario;
     private Double costoTotal;
     private Double medidor;
     public Long compania;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Long numeroPlanillaFisica;
     private String observacion;
     private Long usuarioDigitacion;
     private String observacionAnularReg;
     private Date fechaAnulacion;
     private Date fechaCierreOt;
     private Date fechaReaperturaOt;
     private String cierreOt;
     private String estado;
     private Long almacenId;
     
     
    public DatAbastCombustible() {
    }

	
    public DatAbastCombustible(Long datAbastCombustibleId) {
        this.datAbastCombustibleId = datAbastCombustibleId;
    }
    public DatAbastCombustible(Long almacenId, Long datAbastCombustibleId, TipoAbastecimiento tipoAbastecimiento, Trabajador trabajador, BombaAbastecimiento bombaAbastecimiento, Equipo equipo, Producto producto, UdadMed udadMed, CentCost centCost, Long consecutivo, Date fechaRegistro, Long turnoCampoId, Double conductor, Double cantidad, Double valorUnitario, Double costoTotal, Double medidor, Long compania, Date fechaCreacion, Date fechaModificacion, Long numeroPlanillaFisica, String observacion, Long usuarioDigitacion, String observacionAnularReg, Date fechaAnulacion, Date fechaCierreOt, Date fechaReaperturaOt, String cierreOt, String estado) {
       this.datAbastCombustibleId = datAbastCombustibleId;
       this.tipoAbastecimiento = tipoAbastecimiento;
       this.trabajador = trabajador;
       this.bombaAbastecimiento = bombaAbastecimiento;
       this.equipo = equipo;
       this.producto = producto;
       this.udadMed = udadMed;
       this.centCost = centCost;
       this.consecutivo = consecutivo;
       this.fechaRegistro = fechaRegistro;
       this.turnoCampoId = turnoCampoId;
       this.conductor = conductor;
       this.cantidad = cantidad;
       this.valorUnitario = valorUnitario;
       this.costoTotal = costoTotal;
       this.medidor = medidor;
       this.compania = compania;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.numeroPlanillaFisica = numeroPlanillaFisica;
       this.observacion = observacion;
       this.usuarioDigitacion = usuarioDigitacion;
       this.observacionAnularReg = observacionAnularReg;
       this.fechaAnulacion = fechaAnulacion;
       this.fechaCierreOt = fechaCierreOt;
       this.fechaReaperturaOt = fechaReaperturaOt;
       this.cierreOt = cierreOt;
       this.estado = estado;
       this.almacenId=almacenId;
    }
   
    public Long getAlmacenId() {
		return almacenId;
	}


	public void setAlmacenId(Long almacenId) {
		this.almacenId = almacenId;
	}


	public Long getDatAbastCombustibleId() {
        return this.datAbastCombustibleId;
    }
    
    public void setDatAbastCombustibleId(Long datAbastCombustibleId) {
        this.datAbastCombustibleId = datAbastCombustibleId;
    }
    public TipoAbastecimiento getTipoAbastecimiento() {
        return this.tipoAbastecimiento;
    }
    
    public void setTipoAbastecimiento(TipoAbastecimiento tipoAbastecimiento) {
        this.tipoAbastecimiento = tipoAbastecimiento;
    }
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }
    public BombaAbastecimiento getBombaAbastecimiento() {
        return this.bombaAbastecimiento;
    }
    
    public void setBombaAbastecimiento(BombaAbastecimiento bombaAbastecimiento) {
        this.bombaAbastecimiento = bombaAbastecimiento;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public UdadMed getUdadMed() {
        return this.udadMed;
    }
    
    public void setUdadMed(UdadMed udadMed) {
        this.udadMed = udadMed;
    }
    public CentCost getCentCost() {
        return this.centCost;
    }
    
    public void setCentCost(CentCost centCost) {
        this.centCost = centCost;
    }
    public Long getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Long consecutivo) {
        this.consecutivo = consecutivo;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Long getTurnoCampoId() {
        return this.turnoCampoId;
    }
    
    public void setTurnoCampoId(Long turnoCampoId) {
        this.turnoCampoId = turnoCampoId;
    }
    public Double getConductor() {
        return this.conductor;
    }
    
    public void setConductor(Double conductor) {
        this.conductor = conductor;
    }
    public Double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Double cantidad) {
        this.cantidad = cantidad;
    }
    public Double getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(Double valorUnitario) {
        this.valorUnitario = valorUnitario;
    }
    public Double getCostoTotal() {
        return this.costoTotal;
    }
    
    public void setCostoTotal(Double costoTotal) {
        this.costoTotal = costoTotal;
    }
    public Double getMedidor() {
        return this.medidor;
    }
    
    public void setMedidor(Double medidor) {
        this.medidor = medidor;
    }
    public Long getCompania() {
        return this.compania;
    }
    
    public void setCompania(Long compania) {
        this.compania = compania;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Long getNumeroPlanillaFisica() {
        return this.numeroPlanillaFisica;
    }
    
    public void setNumeroPlanillaFisica(Long numeroPlanillaFisica) {
        this.numeroPlanillaFisica = numeroPlanillaFisica;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Long getUsuarioDigitacion() {
        return this.usuarioDigitacion;
    }
    
    public void setUsuarioDigitacion(Long usuarioDigitacion) {
        this.usuarioDigitacion = usuarioDigitacion;
    }
    public String getObservacionAnularReg() {
        return this.observacionAnularReg;
    }
    
    public void setObservacionAnularReg(String observacionAnularReg) {
        this.observacionAnularReg = observacionAnularReg;
    }
    public Date getFechaAnulacion() {
        return this.fechaAnulacion;
    }
    
    public void setFechaAnulacion(Date fechaAnulacion) {
        this.fechaAnulacion = fechaAnulacion;
    }
    public Date getFechaCierreOt() {
        return this.fechaCierreOt;
    }
    
    public void setFechaCierreOt(Date fechaCierreOt) {
        this.fechaCierreOt = fechaCierreOt;
    }
    public Date getFechaReaperturaOt() {
        return this.fechaReaperturaOt;
    }
    
    public void setFechaReaperturaOt(Date fechaReaperturaOt) {
        this.fechaReaperturaOt = fechaReaperturaOt;
    }
    public String getCierreOt() {
        return this.cierreOt;
    }
    
    public void setCierreOt(String cierreOt) {
        this.cierreOt = cierreOt;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


