package co.com.arcosoft.modelo;

// Generated 17-mar-2015 15:25:33 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * DatClimat generated by hbm2java
 */
public class DatClimat implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long datsClimatoId;
	private EstClimat estClimat;
	public Long compania;
	private Date fechaLluvia;
	private Double precipitacion;
	private Double temperaturaMaxima;
	private Double temperaturaMedia;
	private Double temperaturaMinima;
	private Double temperaturaAmbiente;
	private Double sensacionTermica;
	private Double humedadMaxima;
	private Double humedadMedia;
	private Double humedadMinima;
	private Double humedadExterior;
	private Double humedadInterior;
	private Double evaporacion;
	private Double evaporacionTranspiracion;
	private Double insolacion;
	private Double energiaSolar;
	private Double radiacionSolar;
	private Double nubosidad;
	private Double horasSol;
	private Double puntoRocio;
	private Double velocidadViento;
	private Double velocidadMaxima;
	private Double direccionViento;
	private Double gradosDiaCalor;
	private Double gradosDiaFrio;
	private Double horasLuz;
	private String infoAdicional;
	private String infoAdicional2;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String estado;
	private String observacion;
	private String observacionAnularReg;
	private Date fechaAnulacion;

	public DatClimat() {
	}

	public DatClimat(Long datsClimatoId) {
		this.datsClimatoId = datsClimatoId;
	}

	public DatClimat(Long datsClimatoId, EstClimat estClimat, Long compania, Date fechaLluvia, Double precipitacion,
			Double temperaturaMaxima, Double temperaturaMedia, Double temperaturaMinima, Double temperaturaAmbiente,
			Double sensacionTermica, Double humedadMaxima, Double humedadMedia, Double humedadMinima,
			Double humedadExterior, Double humedadInterior, Double evaporacion, Double evaporacionTranspiracion,
			Double insolacion, Double energiaSolar, Double radiacionSolar, Double nubosidad, Double horasSol,
			Double puntoRocio, Double velocidadViento, Double velocidadMaxima, Double direccionViento,
			Double gradosDiaCalor, Double gradosDiaFrio, Double horasLuz, String infoAdicional, String infoAdicional2,
			Date fechaCreacion, Date fechaModificacion, String estado, String observacion, String observacionAnularReg,
			Date fechaAnulacion) {
		this.datsClimatoId = datsClimatoId;
		this.estClimat = estClimat;
		this.compania = compania;
		this.fechaLluvia = fechaLluvia;
		this.precipitacion = precipitacion;
		this.temperaturaMaxima = temperaturaMaxima;
		this.temperaturaMedia = temperaturaMedia;
		this.temperaturaMinima = temperaturaMinima;
		this.temperaturaAmbiente = temperaturaAmbiente;
		this.sensacionTermica = sensacionTermica;
		this.humedadMaxima = humedadMaxima;
		this.humedadMedia = humedadMedia;
		this.humedadMinima = humedadMinima;
		this.humedadExterior = humedadExterior;
		this.humedadInterior = humedadInterior;
		this.evaporacion = evaporacion;
		this.evaporacionTranspiracion = evaporacionTranspiracion;
		this.insolacion = insolacion;
		this.energiaSolar = energiaSolar;
		this.radiacionSolar = radiacionSolar;
		this.nubosidad = nubosidad;
		this.horasSol = horasSol;
		this.puntoRocio = puntoRocio;
		this.velocidadViento = velocidadViento;
		this.velocidadMaxima = velocidadMaxima;
		this.direccionViento = direccionViento;
		this.gradosDiaCalor = gradosDiaCalor;
		this.gradosDiaFrio = gradosDiaFrio;
		this.horasLuz = horasLuz;
		this.infoAdicional = infoAdicional;
		this.infoAdicional2 = infoAdicional2;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.estado = estado;
		this.observacion = observacion;
		this.observacionAnularReg = observacionAnularReg;
		this.fechaAnulacion = fechaAnulacion;
	}

	public Long getDatsClimatoId() {
		return this.datsClimatoId;
	}

	public void setDatsClimatoId(Long datsClimatoId) {
		this.datsClimatoId = datsClimatoId;
	}

	public EstClimat getEstClimat() {
		return this.estClimat;
	}

	public void setEstClimat(EstClimat estClimat) {
		this.estClimat = estClimat;
	}

	public Long getCompania() {
		return this.compania;
	}

	public void setCompania(Long compania) {
		this.compania = compania;
	}

	public Date getFechaLluvia() {
		return this.fechaLluvia;
	}

	public void setFechaLluvia(Date fechaLluvia) {
		this.fechaLluvia = fechaLluvia;
	}

	public Double getPrecipitacion() {
		return this.precipitacion;
	}

	public void setPrecipitacion(Double precipitacion) {
		this.precipitacion = precipitacion;
	}

	public Double getTemperaturaMaxima() {
		return this.temperaturaMaxima;
	}

	public void setTemperaturaMaxima(Double temperaturaMaxima) {
		this.temperaturaMaxima = temperaturaMaxima;
	}

	public Double getTemperaturaMedia() {
		return this.temperaturaMedia;
	}

	public void setTemperaturaMedia(Double temperaturaMedia) {
		this.temperaturaMedia = temperaturaMedia;
	}

	public Double getTemperaturaMinima() {
		return this.temperaturaMinima;
	}

	public void setTemperaturaMinima(Double temperaturaMinima) {
		this.temperaturaMinima = temperaturaMinima;
	}

	public Double getTemperaturaAmbiente() {
		return this.temperaturaAmbiente;
	}

	public void setTemperaturaAmbiente(Double temperaturaAmbiente) {
		this.temperaturaAmbiente = temperaturaAmbiente;
	}

	public Double getSensacionTermica() {
		return this.sensacionTermica;
	}

	public void setSensacionTermica(Double sensacionTermica) {
		this.sensacionTermica = sensacionTermica;
	}

	public Double getHumedadMaxima() {
		return this.humedadMaxima;
	}

	public void setHumedadMaxima(Double hemedadMaxima) {
		this.humedadMaxima = hemedadMaxima;
	}

	public Double getHumedadMedia() {
		return this.humedadMedia;
	}

	public void setHumedadMedia(Double humedadMedia) {
		this.humedadMedia = humedadMedia;
	}

	public Double getHumedadMinima() {
		return this.humedadMinima;
	}

	public void setHumedadMinima(Double humedadMinima) {
		this.humedadMinima = humedadMinima;
	}

	public Double getHumedadExterior() {
		return this.humedadExterior;
	}

	public void setHumedadExterior(Double humedadExterior) {
		this.humedadExterior = humedadExterior;
	}

	public Double getHumedadInterior() {
		return this.humedadInterior;
	}

	public void setHumedadInterior(Double humedadInterior) {
		this.humedadInterior = humedadInterior;
	}

	public Double getEvaporacion() {
		return this.evaporacion;
	}

	public void setEvaporacion(Double evaporacion) {
		this.evaporacion = evaporacion;
	}

	public Double getEvaporacionTranspiracion() {
		return this.evaporacionTranspiracion;
	}

	public void setEvaporacionTranspiracion(Double evaporacionTranspiracion) {
		this.evaporacionTranspiracion = evaporacionTranspiracion;
	}

	public Double getInsolacion() {
		return this.insolacion;
	}

	public void setInsolacion(Double insolacion) {
		this.insolacion = insolacion;
	}

	public Double getEnergiaSolar() {
		return this.energiaSolar;
	}

	public void setEnergiaSolar(Double energiaSolar) {
		this.energiaSolar = energiaSolar;
	}

	public Double getRadiacionSolar() {
		return this.radiacionSolar;
	}

	public void setRadiacionSolar(Double radiacionSolar) {
		this.radiacionSolar = radiacionSolar;
	}

	public Double getNubosidad() {
		return this.nubosidad;
	}

	public void setNubosidad(Double nubosidad) {
		this.nubosidad = nubosidad;
	}

	public Double getHorasSol() {
		return this.horasSol;
	}

	public void setHorasSol(Double horasSol) {
		this.horasSol = horasSol;
	}

	public Double getPuntoRocio() {
		return this.puntoRocio;
	}

	public void setPuntoRocio(Double puntoRocio) {
		this.puntoRocio = puntoRocio;
	}

	public Double getVelocidadViento() {
		return this.velocidadViento;
	}

	public void setVelocidadViento(Double velocidadViento) {
		this.velocidadViento = velocidadViento;
	}

	public Double getVelocidadMaxima() {
		return this.velocidadMaxima;
	}

	public void setVelocidadMaxima(Double velocidadMaxima) {
		this.velocidadMaxima = velocidadMaxima;
	}

	public Double getDireccionViento() {
		return this.direccionViento;
	}

	public void setDireccionViento(Double direccionViento) {
		this.direccionViento = direccionViento;
	}

	public Double getGradosDiaCalor() {
		return this.gradosDiaCalor;
	}

	public void setGradosDiaCalor(Double gradosDiaCalor) {
		this.gradosDiaCalor = gradosDiaCalor;
	}

	public Double getGradosDiaFrio() {
		return this.gradosDiaFrio;
	}

	public void setGradosDiaFrio(Double gradosDiaFrio) {
		this.gradosDiaFrio = gradosDiaFrio;
	}

	public Double getHorasLuz() {
		return this.horasLuz;
	}

	public void setHorasLuz(Double horasLuz) {
		this.horasLuz = horasLuz;
	}

	public String getInfoAdicional() {
		return this.infoAdicional;
	}

	public void setInfoAdicional(String infoAdicional) {
		this.infoAdicional = infoAdicional;
	}

	public String getInfoAdicional2() {
		return this.infoAdicional2;
	}

	public void setInfoAdicional2(String infoAdicional2) {
		this.infoAdicional2 = infoAdicional2;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public String getObservacionAnularReg() {
		return this.observacionAnularReg;
	}

	public void setObservacionAnularReg(String observacionAnularReg) {
		this.observacionAnularReg = observacionAnularReg;
	}

	public Date getFechaAnulacion() {
		return this.fechaAnulacion;
	}

	public void setFechaAnulacion(Date fechaAnulacion) {
		this.fechaAnulacion = fechaAnulacion;
	}

}
