package co.com.arcosoft.modelo;
// Generated 19/12/2018 09:55:22 PM by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * DatCtrlMaqPines generated by hbm2java
 */
public class DatCtrlMaqPines  implements java.io.Serializable {


     private Long datCtrlMaqPinesId;
     private Equipo equipo;
     private Double ultHoroOdoMetro;
     private Long boletaInicial;
     private Long boletaFinal;
     private Long consecutivoPin;
     private Long compania;
     private Long usuarioDigitacion;
     private Date fechaCreacion;
     private String estado;
     private String observacionAnularReg;
     private Date fechaAnulacion;
     private String observacion;
     private Date fechaModificacion;
 	private Long indicador_vuelta_medidor;

    public DatCtrlMaqPines() {
    }

	
    public DatCtrlMaqPines(Long datCtrlMaqPinesId) {
        this.datCtrlMaqPinesId = datCtrlMaqPinesId;
    }
    public DatCtrlMaqPines(Long datCtrlMaqPinesId, Equipo equipo, Double ultHoroOdoMetro, Long boletaInicial, Long boletaFinal, Long consecutivoPin, Long compania, Long usuarioDigitacion, Date fechaCreacion, String estado, String observacionAnularReg, Date fechaAnulacion, String observacion, 
    		Date fechaModificacion, 	 Long indicador_vuelta_medidor) {
       this.datCtrlMaqPinesId = datCtrlMaqPinesId;
       this.equipo = equipo;
       this.ultHoroOdoMetro = ultHoroOdoMetro;
       this.boletaInicial = boletaInicial;
       this.boletaFinal = boletaFinal;
       this.consecutivoPin = consecutivoPin;
       this.compania = compania;
       this.usuarioDigitacion = usuarioDigitacion;
       this.fechaCreacion = fechaCreacion;
       this.estado = estado;
       this.observacionAnularReg = observacionAnularReg;
       this.fechaAnulacion = fechaAnulacion;
       this.observacion = observacion;
       this.fechaModificacion = fechaModificacion;
       this.indicador_vuelta_medidor= indicador_vuelta_medidor;
    }
   
    
    public Long getIndicador_vuelta_medidor() {
		return indicador_vuelta_medidor;
	}


	public void setIndicador_vuelta_medidor(Long indicador_vuelta_medidor) {
		this.indicador_vuelta_medidor = indicador_vuelta_medidor;
	}


	public Long getDatCtrlMaqPinesId() {
        return this.datCtrlMaqPinesId;
    }
    
    public void setDatCtrlMaqPinesId(Long datCtrlMaqPinesId) {
        this.datCtrlMaqPinesId = datCtrlMaqPinesId;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public Double getUltHoroOdoMetro() {
        return this.ultHoroOdoMetro;
    }
    
    public void setUltHoroOdoMetro(Double ultHoroOdoMetro) {
        this.ultHoroOdoMetro = ultHoroOdoMetro;
    }
    public Long getBoletaInicial() {
        return this.boletaInicial;
    }
    
    public void setBoletaInicial(Long boletaInicial) {
        this.boletaInicial = boletaInicial;
    }
    public Long getBoletaFinal() {
        return this.boletaFinal;
    }
    
    public void setBoletaFinal(Long boletaFinal) {
        this.boletaFinal = boletaFinal;
    }
    public Long getConsecutivoPin() {
        return this.consecutivoPin;
    }
    
    public void setConsecutivoPin(Long consecutivoPin) {
        this.consecutivoPin = consecutivoPin;
    }
    public Long getCompania() {
        return this.compania;
    }
    
    public void setCompania(Long compania) {
        this.compania = compania;
    }
    public Long getUsuarioDigitacion() {
        return this.usuarioDigitacion;
    }
    
    public void setUsuarioDigitacion(Long usuarioDigitacion) {
        this.usuarioDigitacion = usuarioDigitacion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservacionAnularReg() {
        return this.observacionAnularReg;
    }
    
    public void setObservacionAnularReg(String observacionAnularReg) {
        this.observacionAnularReg = observacionAnularReg;
    }
    public Date getFechaAnulacion() {
        return this.fechaAnulacion;
    }
    
    public void setFechaAnulacion(Date fechaAnulacion) {
        this.fechaAnulacion = fechaAnulacion;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


