package co.com.arcosoft.modelo;
// Generated 29/07/2019 11:07:22 AM by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DatDiferidosAgricola generated by hbm2java
 */
public class DatDiferidosAgricola  implements java.io.Serializable {


     private Long datDiferidosAgricolaId;
     private Labor labor;
     private Long consecutivo;
     private Long compania;
     private Date fechaRegistro;
     private Double valorInicial;
     private Double valorCuota;
     private Double valorSaldo;
     private Long periodos;
     private Long npReset;
     private String detalleNota;
     private Long anioAplicacion;
     private Long mesAplicacion;
     private String detalleAplicacion;
     private Long usuarioDigitacion;
     private Date fechaCreacion;
     private String estado;
     private String observacionAnularReg;
     private Date fechaAnulacion;
     private String observacion;
     private Date fechaModificacion;
     private String numeroFactura;
     private Long categEquipId;
     private String tipoTransaccion;
     private Set<DatDiferidosAgricolaDet> datDiferidosAgricolaDets = new HashSet<DatDiferidosAgricolaDet>(0);

    public DatDiferidosAgricola() {
    }

    public DatDiferidosAgricola(Labor labor, Long consecutivo, Long compania, Date fechaRegistro, Double valorInicial, Double valorCuota, Double valorSaldo, Long periodos, Long npReset, String detalleNota, Long anioAplicacion, Long mesAplicacion, String detalleAplicacion, Long usuarioDigitacion, Date fechaCreacion, String estado, String observacionAnularReg, Date fechaAnulacion, String observacion, Date fechaModificacion, String numeroFactura, Long categEquipId, String tipoTransaccion, Set<DatDiferidosAgricolaDet> datDiferidosAgricolaDets) {
       this.labor = labor;
       this.consecutivo = consecutivo;
       this.compania = compania;
       this.fechaRegistro = fechaRegistro;
       this.valorInicial = valorInicial;
       this.valorCuota = valorCuota;
       this.valorSaldo = valorSaldo;
       this.periodos = periodos;
       this.npReset = npReset;
       this.detalleNota = detalleNota;
       this.anioAplicacion = anioAplicacion;
       this.mesAplicacion = mesAplicacion;
       this.detalleAplicacion = detalleAplicacion;
       this.usuarioDigitacion = usuarioDigitacion;
       this.fechaCreacion = fechaCreacion;
       this.estado = estado;
       this.observacionAnularReg = observacionAnularReg;
       this.fechaAnulacion = fechaAnulacion;
       this.observacion = observacion;
       this.fechaModificacion = fechaModificacion;
       this.numeroFactura = numeroFactura;
       this.categEquipId = categEquipId;
       this.tipoTransaccion = tipoTransaccion;
       this.datDiferidosAgricolaDets = datDiferidosAgricolaDets;
    }
   
    public Long getDatDiferidosAgricolaId() {
        return this.datDiferidosAgricolaId;
    }
    
    public void setDatDiferidosAgricolaId(Long datDiferidosAgricolaId) {
        this.datDiferidosAgricolaId = datDiferidosAgricolaId;
    }
    public Labor getLabor() {
        return this.labor;
    }
    
    public void setLabor(Labor labor) {
        this.labor = labor;
    }
    public Long getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Long consecutivo) {
        this.consecutivo = consecutivo;
    }
    public Long getCompania() {
        return this.compania;
    }
    
    public void setCompania(Long compania) {
        this.compania = compania;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Double getValorInicial() {
        return this.valorInicial;
    }
    
    public void setValorInicial(Double valorInicial) {
        this.valorInicial = valorInicial;
    }
    public Double getValorCuota() {
        return this.valorCuota;
    }
    
    public void setValorCuota(Double valorCuota) {
        this.valorCuota = valorCuota;
    }
    public Double getValorSaldo() {
        return this.valorSaldo;
    }
    
    public void setValorSaldo(Double valorSaldo) {
        this.valorSaldo = valorSaldo;
    }
    public Long getPeriodos() {
        return this.periodos;
    }
    
    public void setPeriodos(Long periodos) {
        this.periodos = periodos;
    }
    public Long getNpReset() {
        return this.npReset;
    }
    
    public void setNpReset(Long npReset) {
        this.npReset = npReset;
    }
    public String getDetalleNota() {
        return this.detalleNota;
    }
    
    public void setDetalleNota(String detalleNota) {
        this.detalleNota = detalleNota;
    }
    public Long getAnioAplicacion() {
        return this.anioAplicacion;
    }
    
    public void setAnioAplicacion(Long anioAplicacion) {
        this.anioAplicacion = anioAplicacion;
    }
    public Long getMesAplicacion() {
        return this.mesAplicacion;
    }
    
    public void setMesAplicacion(Long mesAplicacion) {
        this.mesAplicacion = mesAplicacion;
    }
    public String getDetalleAplicacion() {
        return this.detalleAplicacion;
    }
    
    public void setDetalleAplicacion(String detalleAplicacion) {
        this.detalleAplicacion = detalleAplicacion;
    }
    public Long getUsuarioDigitacion() {
        return this.usuarioDigitacion;
    }
    
    public void setUsuarioDigitacion(Long usuarioDigitacion) {
        this.usuarioDigitacion = usuarioDigitacion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservacionAnularReg() {
        return this.observacionAnularReg;
    }
    
    public void setObservacionAnularReg(String observacionAnularReg) {
        this.observacionAnularReg = observacionAnularReg;
    }
    public Date getFechaAnulacion() {
        return this.fechaAnulacion;
    }
    
    public void setFechaAnulacion(Date fechaAnulacion) {
        this.fechaAnulacion = fechaAnulacion;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getNumeroFactura() {
        return this.numeroFactura;
    }
    
    public void setNumeroFactura(String numeroFactura) {
        this.numeroFactura = numeroFactura;
    }
    public Long getCategEquipId() {
        return this.categEquipId;
    }
    
    public void setCategEquipId(Long categEquipId) {
        this.categEquipId = categEquipId;
    }
    public String getTipoTransaccion() {
        return this.tipoTransaccion;
    }
    
    public void setTipoTransaccion(String tipoTransaccion) {
        this.tipoTransaccion = tipoTransaccion;
    }
    public Set<DatDiferidosAgricolaDet> getDatDiferidosAgricolaDets() {
        return this.datDiferidosAgricolaDets;
    }
    
    public void setDatDiferidosAgricolaDets(Set<DatDiferidosAgricolaDet> datDiferidosAgricolaDets) {
        this.datDiferidosAgricolaDets = datDiferidosAgricolaDets;
    }




}


