package co.com.arcosoft.modelo;
// Generated 19-oct-2018 9:33:36 by Hibernate Tools 4.0.0

/**
 * DatDiferidosDet generated by hbm2java
 */
public class DatDiferidosDet implements java.io.Serializable {

	private Long datDiferidosDetId;
	private DatDiferidos datDiferidos;
	private Equipo equipoId;

	private Double valorFactura;
	private Equipo implementoId;

	public DatDiferidosDet() {
	}

	public DatDiferidosDet(Equipo implementoId, DatDiferidos datDiferidos, Equipo equipoId, Double valorFactura) {
		this.datDiferidos = datDiferidos;
		this.equipoId = equipoId;
		this.valorFactura = valorFactura;
		this.implementoId = implementoId;
	}

	public Equipo getImplementoId() {
		return implementoId;
	}

	public void setImplementoId(Equipo implementoId) {
		this.implementoId = implementoId;
	}

	public Long getDatDiferidosDetId() {
		return this.datDiferidosDetId;
	}

	public void setDatDiferidosDetId(Long datDiferidosDetId) {
		this.datDiferidosDetId = datDiferidosDetId;
	}

	public DatDiferidos getDatDiferidos() {
		return this.datDiferidos;
	}

	public void setDatDiferidos(DatDiferidos datDiferidos) {
		this.datDiferidos = datDiferidos;
	}

	public Equipo getEquipoId() {
		return this.equipoId;
	}

	public void setEquipoId(Equipo equipoId) {
		this.equipoId = equipoId;
	}

	public Double getValorFactura() {
		return this.valorFactura;
	}

	public void setValorFactura(Double valorFactura) {
		this.valorFactura = valorFactura;
	}

}
