package co.com.arcosoft.modelo;
// Generated 27-feb-2017 16:59:46 by Hibernate Tools 4.0.0

/**
 * DatNominaTrabajadorDet generated by hbm2java
 */
public class DatNominaTrabajadorDet implements java.io.Serializable {

	private Long datNominaTrabajadorDetId;
	private Trabajador trabajador;
	private ConceptoNomina conceptoNomina;
	private DatNominaTrabajador datNominaTrabajador;
	private Double valorTotal;
	private Double cantidad;
	private UdadMed udadMedId;
	private Double valorDeduccion;
	private String tipoMovimiento;

	public DatNominaTrabajadorDet() {
	}

	public DatNominaTrabajadorDet(Long datNominaTrabajadorDetId) {
		this.datNominaTrabajadorDetId = datNominaTrabajadorDetId;
	}

	public DatNominaTrabajadorDet(Long datNominaTrabajadorDetId, Trabajador trabajador, ConceptoNomina conceptoNomina,
			DatNominaTrabajador datNominaTrabajador, Double valorTotal, Double cantidad, UdadMed udadMedId,
			Double valorDeduccion, String tipoMovimiento) {
		this.datNominaTrabajadorDetId = datNominaTrabajadorDetId;
		this.trabajador = trabajador;
		this.conceptoNomina = conceptoNomina;
		this.datNominaTrabajador = datNominaTrabajador;
		this.valorTotal = valorTotal;
		this.cantidad= cantidad;
		this.udadMedId=udadMedId;
		this.valorDeduccion=valorDeduccion;
		this.tipoMovimiento=tipoMovimiento;
				
	}

	/**
	 * @return the cantidad
	 */
	public Double getCantidad() {
		return cantidad;
	}

	/**
	 * @param cantidad the cantidad to set
	 */
	public void setCantidad(Double cantidad) {
		this.cantidad = cantidad;
	}

	/**
	 * @return the udadMedId
	 */
	public UdadMed getUdadMedId() {
		return udadMedId;
	}

	/**
	 * @param udadMedId the udadMedId to set
	 */
	public void setUdadMedId(UdadMed udadMedId) {
		this.udadMedId = udadMedId;
	}

	public Long getDatNominaTrabajadorDetId() {
		return this.datNominaTrabajadorDetId;
	}

	public void setDatNominaTrabajadorDetId(Long datNominaTrabajadorDetId) {
		this.datNominaTrabajadorDetId = datNominaTrabajadorDetId;
	}

	public Trabajador getTrabajador() {
		return this.trabajador;
	}

	public void setTrabajador(Trabajador trabajador) {
		this.trabajador = trabajador;
	}

	public ConceptoNomina getConceptoNomina() {
		return this.conceptoNomina;
	}

	public void setConceptoNomina(ConceptoNomina conceptoNomina) {
		this.conceptoNomina = conceptoNomina;
	}

	public DatNominaTrabajador getDatNominaTrabajador() {
		return this.datNominaTrabajador;
	}

	public void setDatNominaTrabajador(DatNominaTrabajador datNominaTrabajador) {
		this.datNominaTrabajador = datNominaTrabajador;
	}

	public Double getValorTotal() {
		return this.valorTotal;
	}

	public void setValorTotal(Double valorTotal) {
		this.valorTotal = valorTotal;
	}

	public Double getValorDeduccion() {
		return valorDeduccion;
	}

	public void setValorDeduccion(Double valorDeduccion) {
		this.valorDeduccion = valorDeduccion;
	}

	public String getTipoMovimiento() {
		return tipoMovimiento;
	}

	public void setTipoMovimiento(String tipoMovimiento) {
		this.tipoMovimiento = tipoMovimiento;
	}

}
