package co.com.arcosoft.modelo;
// Generated 12/04/2019 03:26:29 PM by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * DatPlanServiciosMqdetEjec generated by hbm2java
 */
public class DatPlanServiciosMqdetEjec  implements java.io.Serializable {


     private Long datPlanServiciosMqdetEjecId;
     private Equipo equipo;
     private DatPlanServiciosMqdet datPlanServiciosMqdet;
     private Double cantidadRealizada;
     private Date fechaRegistro;
     private Trabajador operario;

    public DatPlanServiciosMqdetEjec() {
    }

    public DatPlanServiciosMqdetEjec(Equipo equipo, DatPlanServiciosMqdet datPlanServiciosMqdet, 
    		Double cantidadRealizada, Date fechaRegistro, Trabajador operario) {
       this.equipo = equipo;
       this.datPlanServiciosMqdet = datPlanServiciosMqdet;
       this.cantidadRealizada = cantidadRealizada;
       this.fechaRegistro = fechaRegistro;
       this.operario=operario;
       
    }
   
    
    public Trabajador getOperario() {
		return operario;
	}

	public void setOperario(Trabajador operario) {
		this.operario = operario;
	}

	public Long getDatPlanServiciosMqdetEjecId() {
        return this.datPlanServiciosMqdetEjecId;
    }
    
    public void setDatPlanServiciosMqdetEjecId(Long datPlanServiciosMqdetEjecId) {
        this.datPlanServiciosMqdetEjecId = datPlanServiciosMqdetEjecId;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public DatPlanServiciosMqdet getDatPlanServiciosMqdet() {
        return this.datPlanServiciosMqdet;
    }
    
    public void setDatPlanServiciosMqdet(DatPlanServiciosMqdet datPlanServiciosMqdet) {
        this.datPlanServiciosMqdet = datPlanServiciosMqdet;
    }
    public Double getCantidadRealizada() {
        return this.cantidadRealizada;
    }
    
    public void setCantidadRealizada(Double cantidadRealizada) {
        this.cantidadRealizada = cantidadRealizada;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }




}


