package co.com.arcosoft.modelo;
// Generated 24-ene-2017 20:02:45 by Hibernate Tools 4.0.0

/**
 * DatPlanLaborDet generated by hbm2java
 */
public class DatPlanLaborDet implements java.io.Serializable {

	private Long planLaborDetId;
	private DatPlanLabor datPlanLabor;
	private Nivel4 nivel4;
	private Nivel2 nivel2;
	private Double edadPlanificacion;
	private Double cantidadPlan;

	public DatPlanLaborDet() {
	}

	public DatPlanLaborDet(DatPlanLabor datPlanLabor, Nivel4 nivel4, Nivel2 nivel2, Double edadPlanificacion,
			Double cantidadPlan) {
		this.datPlanLabor = datPlanLabor;
		this.nivel4 = nivel4;
		this.nivel2 = nivel2;
		this.edadPlanificacion = edadPlanificacion;
		this.cantidadPlan = cantidadPlan;
	}

	public Long getPlanLaborDetId() {
		return this.planLaborDetId;
	}

	public void setPlanLaborDetId(Long planLaborDetId) {
		this.planLaborDetId = planLaborDetId;
	}

	public DatPlanLabor getDatPlanLabor() {
		return this.datPlanLabor;
	}

	public void setDatPlanLabor(DatPlanLabor datPlanLabor) {
		this.datPlanLabor = datPlanLabor;
	}

	public Nivel4 getNivel4() {
		return this.nivel4;
	}

	public void setNivel4(Nivel4 nivel4) {
		this.nivel4 = nivel4;
	}

	public Nivel2 getNivel2() {
		return this.nivel2;
	}

	public void setNivel2(Nivel2 nivel2) {
		this.nivel2 = nivel2;
	}

	public Double getEdadPlanificacion() {
		return this.edadPlanificacion;
	}

	public void setEdadPlanificacion(Double edadPlanificacion) {
		this.edadPlanificacion = edadPlanificacion;
	}

	public Double getCantidadPlan() {
		return this.cantidadPlan;
	}

	public void setCantidadPlan(Double cantidadPlan) {
		this.cantidadPlan = cantidadPlan;
	}

}
