package co.com.arcosoft.modelo;
// Generated 27/12/2018 09:43:16 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * DatPlanServiciosMqdet generated by hbm2java
 */
public class DatPlanServiciosMqdet  implements java.io.Serializable {


     private Long datPlanServiciosMqdetId;
     private Nivel2Clientesmq nivel2Clientesmq;
     private Equipo equipo;
     private UdadMed udadMed;
     private DatPlanServiciosMq datPlanServiciosMq;
     private Labor labor;
     private PersEmpr persEmpr;
     private Nivel4Clientesmq nivel4ClientesmqId;
     private String nivel4mqTexto;
     private Double cantidadPlan;
     private String concluido;
     private Double valorEstUnitario;
     private Double valorEstTotal;
     private String detalleNota;

     private Double cantidadRealizada;
     private Double cantidadPendiente;
     private String facturado;
     private Trabajador operario;
     private Long numPases;
     private Date periodoInicial;
     private Double areaProgramada;
     private Double cantidadPresupuesto;
     
    public DatPlanServiciosMqdet() {
    }

    public DatPlanServiciosMqdet(Nivel2Clientesmq nivel2Clientesmq, Equipo equipo, UdadMed udadMed, 
    		DatPlanServiciosMq datPlanServiciosMq, Labor labor, PersEmpr persEmpr, Nivel4Clientesmq nivel4ClientesmqId,
    		String nivel4mqTexto, Double cantidadPlan, String concluido, Double valorEstUnitario, 
    		Double valorEstTotal, String detalleNota, Trabajador operario,
    		Double cantidadRealizada, Double cantidadPendiente, String facturado, Long numPases,   Date periodoInicial,
    		Double areaProgramada, Double cantidadPresupuesto
    		) {
    	this.numPases = numPases;
       this.nivel2Clientesmq = nivel2Clientesmq;
       this.equipo = equipo;
       this.udadMed = udadMed;
       this.datPlanServiciosMq = datPlanServiciosMq;
       this.labor = labor;
       this.persEmpr = persEmpr;
       this.nivel4ClientesmqId = nivel4ClientesmqId;
       this.nivel4mqTexto = nivel4mqTexto;
       this.cantidadPlan = cantidadPlan;
       this.concluido = concluido;
       this.valorEstUnitario = valorEstUnitario;
       this.valorEstTotal = valorEstTotal;
       this.detalleNota = detalleNota;
       this.cantidadRealizada=cantidadRealizada;
       this.cantidadPendiente=cantidadPendiente;
       this.facturado=facturado;
       this.operario = operario;
       this.periodoInicial=periodoInicial;
       this.areaProgramada=areaProgramada;
       this.cantidadPresupuesto=cantidadPresupuesto;
    }
    
    
   
    public Double getCantidadPresupuesto() {
		return cantidadPresupuesto;
	}

	public void setCantidadPresupuesto(Double cantidadPresupuesto) {
		this.cantidadPresupuesto = cantidadPresupuesto;
	}

	public Double getAreaProgramada() {
		return areaProgramada;
	}

	public void setAreaProgramada(Double areaProgramada) {
		this.areaProgramada = areaProgramada;
	}

	public Date getPeriodoInicial() {
		return periodoInicial;
	}

	public void setPeriodoInicial(Date periodoInicial) {
		this.periodoInicial = periodoInicial;
	}

	public Long getNumPases() {
		return numPases;
	}

	public void setNumPases(Long numPases) {
		this.numPases = numPases;
	}

	public Trabajador getOperario() {
		return operario;
	}

	public void setOperario(Trabajador operario) {
		this.operario = operario;
	}

	public Double getCantidadRealizada() {
		return cantidadRealizada;
	}

	public void setCantidadRealizada(Double cantidadRealizada) {
		this.cantidadRealizada = cantidadRealizada;
	}

	public Double getCantidadPendiente() {
		return cantidadPendiente;
	}

	public void setCantidadPendiente(Double cantidadPendiente) {
		this.cantidadPendiente = cantidadPendiente;
	}

	public String getFacturado() {
		return facturado;
	}

	public void setFacturado(String facturado) {
		this.facturado = facturado;
	}

	public Long getDatPlanServiciosMqdetId() {
        return this.datPlanServiciosMqdetId;
    }
    
    public void setDatPlanServiciosMqdetId(Long datPlanServiciosMqdetId) {
        this.datPlanServiciosMqdetId = datPlanServiciosMqdetId;
    }
    public Nivel2Clientesmq getNivel2Clientesmq() {
        return this.nivel2Clientesmq;
    }
    
    public void setNivel2Clientesmq(Nivel2Clientesmq nivel2Clientesmq) {
        this.nivel2Clientesmq = nivel2Clientesmq;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public UdadMed getUdadMed() {
        return this.udadMed;
    }
    
    public void setUdadMed(UdadMed udadMed) {
        this.udadMed = udadMed;
    }
    public DatPlanServiciosMq getDatPlanServiciosMq() {
        return this.datPlanServiciosMq;
    }
    
    public void setDatPlanServiciosMq(DatPlanServiciosMq datPlanServiciosMq) {
        this.datPlanServiciosMq = datPlanServiciosMq;
    }
    public Labor getLabor() {
        return this.labor;
    }
    
    public void setLabor(Labor labor) {
        this.labor = labor;
    }
    public PersEmpr getPersEmpr() {
        return this.persEmpr;
    }
    
    public void setPersEmpr(PersEmpr persEmpr) {
        this.persEmpr = persEmpr;
    }
    public Nivel4Clientesmq getNivel4ClientesmqId() {
        return this.nivel4ClientesmqId;
    }
    
    public void setNivel4ClientesmqId(Nivel4Clientesmq nivel4ClientesmqId) {
        this.nivel4ClientesmqId = nivel4ClientesmqId;
    }
    public String getNivel4mqTexto() {
        return this.nivel4mqTexto;
    }
    
    public void setNivel4mqTexto(String nivel4mqTexto) {
        this.nivel4mqTexto = nivel4mqTexto;
    }
    public Double getCantidadPlan() {
        return this.cantidadPlan;
    }
    
    public void setCantidadPlan(Double cantidadPlan) {
        this.cantidadPlan = cantidadPlan;
    }
    public String getConcluido() {
        return this.concluido;
    }
    
    public void setConcluido(String concluido) {
        this.concluido = concluido;
    }
    public Double getValorEstUnitario() {
        return this.valorEstUnitario;
    }
    
    public void setValorEstUnitario(Double valorEstUnitario) {
        this.valorEstUnitario = valorEstUnitario;
    }
    public Double getValorEstTotal() {
        return this.valorEstTotal;
    }
    
    public void setValorEstTotal(Double valorEstTotal) {
        this.valorEstTotal = valorEstTotal;
    }
    public String getDetalleNota() {
        return this.detalleNota;
    }
    
    public void setDetalleNota(String detalleNota) {
        this.detalleNota = detalleNota;
    }




}


