package co.com.arcosoft.modelo;
// Generated 27/12/2018 09:43:16 PM by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DatPlanServiciosMq generated by hbm2java
 */
public class DatPlanServiciosMq  implements java.io.Serializable {


     private Long datPlanServiciosMqId;
     private Trabajador trabajador;
     private ZonaGeografica zonaGeografica;
     private Long compania;
     private Integer anio;
     private Date periodoInicial;
     private Date periodoFinal;
     private Integer NPases;
     private Double costoTotalEstimado;
     private String observacion;
     private String cierreOt;
     private String idMobile;
     private Double latitud;
     private Double longitud;
     private Double precision1;
     private String infoAdicional;
     private String infoAdicional2;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private String estado;
     private Long usuarioDigitacion;
     private String observacionAnularReg;
     private Long consecutivo;
     private Date fechaAnulacion;
     private Date fechaCierreOt;
     private Date fechaReaperturaOt;
     private String nivelAutorizacion1;
     private String nivelAutorizacion2;
     private Set<DatPlanServiciosMqdet> datPlanServiciosMqdets = new HashSet<DatPlanServiciosMqdet>(0);
     private PersEmpr persEmpr;
     private Nivel2Clientesmq nivel2Clientesmq;
     private String tipoProyecto;
     
    public DatPlanServiciosMq() {
    }

    public DatPlanServiciosMq(Trabajador trabajador, ZonaGeografica zonaGeografica, Long compania, Integer anio, 
    		Date periodoInicial, Date periodoFinal, Integer NPases, Double costoTotalEstimado, 
    		String observacion, String cierreOt, String idMobile, Double latitud, Double longitud, 
    		Double precision1, String infoAdicional, String infoAdicional2, Date fechaCreacion, 
    		Date fechaModificacion, String estado, Long usuarioDigitacion, String observacionAnularReg,
    		Long consecutivo, Date fechaAnulacion, Date fechaCierreOt, Date fechaReaperturaOt, 
    		String nivelAutorizacion1, String nivelAutorizacion2, Set<DatPlanServiciosMqdet> datPlanServiciosMqdets,
    		 PersEmpr persEmpr,   Nivel2Clientesmq nivel2Clientesmq,String tipoProyecto 
    		) {
       this.trabajador = trabajador;
       this.zonaGeografica = zonaGeografica;
       this.compania = compania;
       this.anio = anio;
       this.periodoInicial = periodoInicial;
       this.periodoFinal = periodoFinal;
       this.NPases = NPases;
       this.costoTotalEstimado = costoTotalEstimado;
       this.observacion = observacion;
       this.cierreOt = cierreOt;
       this.idMobile = idMobile;
       this.latitud = latitud;
       this.longitud = longitud;
       this.precision1 = precision1;
       this.infoAdicional = infoAdicional;
       this.infoAdicional2 = infoAdicional2;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estado = estado;
       this.usuarioDigitacion = usuarioDigitacion;
       this.observacionAnularReg = observacionAnularReg;
       this.consecutivo = consecutivo;
       this.fechaAnulacion = fechaAnulacion;
       this.fechaCierreOt = fechaCierreOt;
       this.fechaReaperturaOt = fechaReaperturaOt;
       this.nivelAutorizacion1 = nivelAutorizacion1;
       this.nivelAutorizacion2 = nivelAutorizacion2;
       this.datPlanServiciosMqdets = datPlanServiciosMqdets;
       this.nivel2Clientesmq=nivel2Clientesmq;
       this.persEmpr=persEmpr;
       this.tipoProyecto=tipoProyecto;
    }
   
    
    
    public String getTipoProyecto() {
		return tipoProyecto;
	}

	public void setTipoProyecto(String tipoProyecto) {
		this.tipoProyecto = tipoProyecto;
	}

	public PersEmpr getPersEmpr() {
		return persEmpr;
	}

	public void setPersEmpr(PersEmpr persEmpr) {
		this.persEmpr = persEmpr;
	}

	public Nivel2Clientesmq getNivel2Clientesmq() {
		return nivel2Clientesmq;
	}

	public void setNivel2Clientesmq(Nivel2Clientesmq nivel2Clientesmq) {
		this.nivel2Clientesmq = nivel2Clientesmq;
	}

	public Long getDatPlanServiciosMqId() {
        return this.datPlanServiciosMqId;
    }
    
    public void setDatPlanServiciosMqId(Long datPlanServiciosMqId) {
        this.datPlanServiciosMqId = datPlanServiciosMqId;
    }
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }
    public ZonaGeografica getZonaGeografica() {
        return this.zonaGeografica;
    }
    
    public void setZonaGeografica(ZonaGeografica zonaGeografica) {
        this.zonaGeografica = zonaGeografica;
    }
    public Long getCompania() {
        return this.compania;
    }
    
    public void setCompania(Long compania) {
        this.compania = compania;
    }
    public Integer getAnio() {
        return this.anio;
    }
    
    public void setAnio(Integer anio) {
        this.anio = anio;
    }
    public Date getPeriodoInicial() {
        return this.periodoInicial;
    }
    
    public void setPeriodoInicial(Date periodoInicial) {
        this.periodoInicial = periodoInicial;
    }
    public Date getPeriodoFinal() {
        return this.periodoFinal;
    }
    
    public void setPeriodoFinal(Date periodoFinal) {
        this.periodoFinal = periodoFinal;
    }
    public Integer getNPases() {
        return this.NPases;
    }
    
    public void setNPases(Integer NPases) {
        this.NPases = NPases;
    }
    public Double getCostoTotalEstimado() {
        return this.costoTotalEstimado;
    }
    
    public void setCostoTotalEstimado(Double costoTotalEstimado) {
        this.costoTotalEstimado = costoTotalEstimado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getCierreOt() {
        return this.cierreOt;
    }
    
    public void setCierreOt(String cierreOt) {
        this.cierreOt = cierreOt;
    }
    public String getIdMobile() {
        return this.idMobile;
    }
    
    public void setIdMobile(String idMobile) {
        this.idMobile = idMobile;
    }
    public Double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Double latitud) {
        this.latitud = latitud;
    }
    public Double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Double longitud) {
        this.longitud = longitud;
    }
    public Double getPrecision1() {
        return this.precision1;
    }
    
    public void setPrecision1(Double precision1) {
        this.precision1 = precision1;
    }
    public String getInfoAdicional() {
        return this.infoAdicional;
    }
    
    public void setInfoAdicional(String infoAdicional) {
        this.infoAdicional = infoAdicional;
    }
    public String getInfoAdicional2() {
        return this.infoAdicional2;
    }
    
    public void setInfoAdicional2(String infoAdicional2) {
        this.infoAdicional2 = infoAdicional2;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Long getUsuarioDigitacion() {
        return this.usuarioDigitacion;
    }
    
    public void setUsuarioDigitacion(Long usuarioDigitacion) {
        this.usuarioDigitacion = usuarioDigitacion;
    }
    public String getObservacionAnularReg() {
        return this.observacionAnularReg;
    }
    
    public void setObservacionAnularReg(String observacionAnularReg) {
        this.observacionAnularReg = observacionAnularReg;
    }
    public Long getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Long consecutivo) {
        this.consecutivo = consecutivo;
    }
    public Date getFechaAnulacion() {
        return this.fechaAnulacion;
    }
    
    public void setFechaAnulacion(Date fechaAnulacion) {
        this.fechaAnulacion = fechaAnulacion;
    }
    public Date getFechaCierreOt() {
        return this.fechaCierreOt;
    }
    
    public void setFechaCierreOt(Date fechaCierreOt) {
        this.fechaCierreOt = fechaCierreOt;
    }
    public Date getFechaReaperturaOt() {
        return this.fechaReaperturaOt;
    }
    
    public void setFechaReaperturaOt(Date fechaReaperturaOt) {
        this.fechaReaperturaOt = fechaReaperturaOt;
    }
    public String getNivelAutorizacion1() {
        return this.nivelAutorizacion1;
    }
    
    public void setNivelAutorizacion1(String nivelAutorizacion1) {
        this.nivelAutorizacion1 = nivelAutorizacion1;
    }
    public String getNivelAutorizacion2() {
        return this.nivelAutorizacion2;
    }
    
    public void setNivelAutorizacion2(String nivelAutorizacion2) {
        this.nivelAutorizacion2 = nivelAutorizacion2;
    }
    public Set<DatPlanServiciosMqdet> getDatPlanServiciosMqdets() {
        return this.datPlanServiciosMqdets;
    }
    
    public void setDatPlanServiciosMqdets(Set<DatPlanServiciosMqdet> datPlanServiciosMqdets) {
        this.datPlanServiciosMqdets = datPlanServiciosMqdets;
    }




}


