package co.com.arcosoft.modelo;
// Generated 21-jul-2016 7:22:02 by Hibernate Tools 4.0.0

/**
 * DatPlanillaNominaDet generated by hbm2java
 */
public class DatPlanillaNominaDet implements java.io.Serializable {

	private Long detPlanillaNominaId;
	private UdadMed udadMedByUdadMedPago;
	private Trabajador trabajador;
	private ConceptoNomina conceptoNomina;
	private UdadMed udadMedByUdadMedProd;
	private PersEmpr persEmpr;
	private DatPlanillaNomina planillaNominaId;
	private Long eqpTrabId;
	private Double cantidadPago;
	private Double cantidadProd;
	private Double valorUnitario;
	private Double costoTotal;
	private Double cantidadDescontar;
	private String estadoIncidencia;
	private String alturaPlanta;
	private Long numeroTiquete;
	private Double pesoPromedio;
	private DatPlanLaborDet ordenTrabajo;
	private Nivel4 nivel4;
	private Nivel2 nivel2Id;
	private Labor laborId;
	private Long etapaId;
	private Long variedId;
	private Double edad;
	private Double horasTrabajadas;
	private Equipo equipoId;

	private String tipoServicio;
	private UdadMed udadMedMaq;

	private Double horasTotal;
	private Double horometroInicial;
	private Double horometroFinal;
	private Double horometroTotal;

	private Double cantidadMaq;
	private Double valorUnitarioMaq;
	private Double valorTotalMaq;
	
	private String tipoPersona;
	
	
	private Equipo implementoId;

	public DatPlanillaNominaDet() {
	}

	public DatPlanillaNominaDet(Long detPlanillaNominaId) {
		this.detPlanillaNominaId = detPlanillaNominaId;
	}

	public DatPlanillaNominaDet(Long detPlanillaNominaId, UdadMed udadMedByUdadMedPago, Trabajador trabajador,
			ConceptoNomina conceptoNomina, UdadMed udadMedByUdadMedProd, PersEmpr persEmpr,
			DatPlanillaNomina planillaNominaId, Long eqpTrabId, Double cantidadPago, Double cantidadProd,
			Double valorUnitario, Double costoTotal, Double cantidadDescontar, String estadoIncidencia,
			String alturaPlanta, Long numeroTiquete, Double pesoPromedio, DatPlanLaborDet ordenTrabajo, Nivel2 nivel2Id,
			Nivel4 nivel4, Labor laborId, Long etapaId, Long variedId, Double edad, Double horasTrabajadas,
			Equipo equipoId,

			String tipoServicio, UdadMed udadMedMaq,

			Double horasTotal, Double horometroInicial, Double horometroFinal, Double horometroTotal, Double cantidad,
			Double cantidadMaq, Double valorTotalMaq, Double valorUnitarioMaq, String tipoPersona, Equipo implementoId

	) { this.valorUnitarioMaq=valorUnitarioMaq;
		this.detPlanillaNominaId = detPlanillaNominaId;
		this.udadMedByUdadMedPago = udadMedByUdadMedPago;
		this.trabajador = trabajador;
		this.conceptoNomina = conceptoNomina;
		this.udadMedByUdadMedProd = udadMedByUdadMedProd;
		this.persEmpr = persEmpr;
		this.planillaNominaId = planillaNominaId;
		this.eqpTrabId = eqpTrabId;
		this.cantidadPago = cantidadPago;
		this.cantidadProd = cantidadProd;
		this.valorUnitario = valorUnitario;
		this.costoTotal = costoTotal;
		this.cantidadDescontar = cantidadDescontar;
		this.estadoIncidencia = estadoIncidencia;
		this.alturaPlanta = alturaPlanta;
		this.numeroTiquete = numeroTiquete;
		this.pesoPromedio = pesoPromedio;
		this.ordenTrabajo = ordenTrabajo;
		this.nivel2Id = nivel2Id;
		this.nivel4 = nivel4;
		this.laborId = laborId;
		this.etapaId = etapaId;
		this.variedId = variedId;
		this.edad = edad;
		this.horasTrabajadas = horasTrabajadas;
		this.equipoId = equipoId;
		this.tipoServicio = tipoServicio;
		this.udadMedMaq = udadMedMaq;
		this.horasTotal = horasTotal;
		this.horometroInicial = horometroInicial;
		this.horometroFinal = horometroFinal;
		this.horometroTotal = horometroTotal;
		this.cantidadMaq = cantidadMaq;
		this.valorTotalMaq = valorTotalMaq;
		this.tipoPersona = tipoPersona;
		this.implementoId=implementoId;
	}

	
	public void setPersEmpr(PersEmpr persEmpr) {
		this.persEmpr = persEmpr;
	}

	public Equipo getImplementoId() {
		return implementoId;
	}

	public void setImplementoId(Equipo implementoId) {
		this.implementoId = implementoId;
	}

	public Double getValorUnitarioMaq() {
		return valorUnitarioMaq;
	}

	public void setValorUnitarioMaq(Double valorUnitarioMaq) {
		this.valorUnitarioMaq = valorUnitarioMaq;
	}

	public String getTipoServicio() {
		return tipoServicio;
	}

	public void setTipoServicio(String tipoServicio) {
		this.tipoServicio = tipoServicio;
	}

	public UdadMed getUdadMedMaq() {
		return udadMedMaq;
	}

	public void setUdadMedMaq(UdadMed udadMedMaq) {
		this.udadMedMaq = udadMedMaq;
	}

	public Double getHorasTotal() {
		return horasTotal;
	}

	public void setHorasTotal(Double horasTotal) {
		this.horasTotal = horasTotal;
	}

	public Double getHorometroInicial() {
		return horometroInicial;
	}

	public void setHorometroInicial(Double horometroInicial) {
		this.horometroInicial = horometroInicial;
	}

	public Double getHorometroFinal() {
		return horometroFinal;
	}

	public void setHorometroFinal(Double horometroFinal) {
		this.horometroFinal = horometroFinal;
	}

	public Double getHorometroTotal() {
		return horometroTotal;
	}

	public void setHorometroTotal(Double horometroTotal) {
		this.horometroTotal = horometroTotal;
	}

	public Double getCantidadMaq() {
		return cantidadMaq;
	}

	public void setCantidadMaq(Double cantidadMaq) {
		this.cantidadMaq = cantidadMaq;
	}

	public Double getValorTotalMaq() {
		return valorTotalMaq;
	}

	public void setValorTotalMaq(Double valorTotalMaq) {
		this.valorTotalMaq = valorTotalMaq;
	}

	/**
	 * @return the equipoId
	 */
	public Equipo getEquipoId() {
		return equipoId;
	}

	/**
	 * @param equipoId the equipoId to set
	 */
	public void setEquipoId(Equipo equipoId) {
		this.equipoId = equipoId;
	}

	/**
	 * @return the horasTrabajadas
	 */
	public Double getHorasTrabajadas() {
		return horasTrabajadas;
	}

	/**
	 * @param horasTrabajadas the horasTrabajadas to set
	 */
	public void setHorasTrabajadas(Double horasTrabajadas) {
		this.horasTrabajadas = horasTrabajadas;
	}

	public Double getEdad() {
		return edad;
	}

	public void setEdad(Double edad) {
		this.edad = edad;
	}

	public Long getEtapaId() {
		return etapaId;
	}

	public void setEtapaId(Long etapaId) {
		this.etapaId = etapaId;
	}

	public Long getVariedId() {
		return variedId;
	}

	public void setVariedId(Long variedId) {
		this.variedId = variedId;
	}

	public Labor getLaborId() {
		return laborId;
	}

	public void setLaborId(Labor laborId) {
		this.laborId = laborId;
	}

	public Nivel4 getNivel4() {
		return nivel4;
	}

	public void setNivel4(Nivel4 nivel4) {
		this.nivel4 = nivel4;
	}

	public Nivel2 getNivel2Id() {
		return nivel2Id;
	}

	public void setNivel2Id(Nivel2 nivel2Id) {
		this.nivel2Id = nivel2Id;
	}

	public Long getNumeroTiquete() {
		return numeroTiquete;
	}

	public void setNumeroTiquete(Long numeroTiquete) {
		this.numeroTiquete = numeroTiquete;
	}

	public Double getPesoPromedio() {
		return pesoPromedio;
	}

	public void setPesoPromedio(Double pesoPromedio) {
		this.pesoPromedio = pesoPromedio;
	}

	public DatPlanLaborDet getOrdenTrabajo() {
		return ordenTrabajo;
	}

	public void setOrdenTrabajo(DatPlanLaborDet ordenTrabajo) {
		this.ordenTrabajo = ordenTrabajo;
	}

	public String getAlturaPlanta() {
		return alturaPlanta;
	}

	public void setAlturaPlanta(String alturaPlanta) {
		this.alturaPlanta = alturaPlanta;
	}

	public String getEstadoIncidencia() {
		return estadoIncidencia;
	}

	public void setEstadoIncidencia(String estadoIncidencia) {
		this.estadoIncidencia = estadoIncidencia;
	}

	public Double getCantidadDescontar() {
		return cantidadDescontar;
	}

	public void setCantidadDescontar(Double cantidadDescontar) {
		this.cantidadDescontar = cantidadDescontar;
	}

	public Long getDetPlanillaNominaId() {
		return this.detPlanillaNominaId;
	}

	public void setDetPlanillaNominaId(Long detPlanillaNominaId) {
		this.detPlanillaNominaId = detPlanillaNominaId;
	}

	public UdadMed getUdadMedByUdadMedPago() {
		return this.udadMedByUdadMedPago;
	}

	public void setUdadMedByUdadMedPago(UdadMed udadMedByUdadMedPago) {
		this.udadMedByUdadMedPago = udadMedByUdadMedPago;
	}

	public Trabajador getTrabajador() {
		return this.trabajador;
	}

	public void setTrabajador(Trabajador trabajador) {
		this.trabajador = trabajador;
	}

	public ConceptoNomina getConceptoNomina() {
		return this.conceptoNomina;
	}

	public void setConceptoNomina(ConceptoNomina conceptoNomina) {
		this.conceptoNomina = conceptoNomina;
	}

	public UdadMed getUdadMedByUdadMedProd() {
		return this.udadMedByUdadMedProd;
	}

	public void setUdadMedByUdadMedProd(UdadMed udadMedByUdadMedProd) {
		this.udadMedByUdadMedProd = udadMedByUdadMedProd;
	}



	public PersEmpr getPersEmpr() {
		return persEmpr;
	}

	public Long getEqpTrabId() {
		return this.eqpTrabId;
	}

	public void setEqpTrabId(Long eqpTrabId) {
		this.eqpTrabId = eqpTrabId;
	}

	public Double getCantidadPago() {
		return this.cantidadPago;
	}

	public void setCantidadPago(Double cantidadPago) {
		this.cantidadPago = cantidadPago;
	}

	public Double getCantidadProd() {
		return this.cantidadProd;
	}

	public void setCantidadProd(Double cantidadProd) {
		this.cantidadProd = cantidadProd;
	}

	public Double getValorUnitario() {
		return this.valorUnitario;
	}

	public void setValorUnitario(Double valorUnitario) {
		this.valorUnitario = valorUnitario;
	}

	public Double getCostoTotal() {
		return this.costoTotal;
	}

	public void setCostoTotal(Double costoTotal) {
		this.costoTotal = costoTotal;
	}

	public DatPlanillaNomina getPlanillaNominaId() {
		return planillaNominaId;
	}

	public void setPlanillaNominaId(DatPlanillaNomina planillaNominaId) {
		this.planillaNominaId = planillaNominaId;
	}

	public String getTipoPersona() {
		return tipoPersona;
	}

	public void setTipoPersona(String tipoPersona) {
		this.tipoPersona = tipoPersona;
	}

}
