package co.com.arcosoft.modelo;
// Generated 24-mar-2018 15:52:14 by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * DatPlanAnualFabrica generated by hbm2java
 */
public class DatPlanAnualFabrica  implements java.io.Serializable {


     private Long datPlanAnualFabricaId;
     private Long consecutivo;
     private Long anio;
     private Double horasArranque;
     private Double produccionEstEnero;
     private Double produccionEstFebrero;
     private Double produccionEstMarzo;
     private Double produccionEstAbril;
     private Double produccionEstMayo;
     private Double produccionEstJunio;
     private Double produccionEstJulio;
     private Double produccionEstAgosto;
     private Double produccionEstSeptiembre;
     private Double produccionEstOctubre;
     private Double produccionEstNoviembre;
     private Double produccionEstDiciembre;
     private Double produccionEstTotal;
     private Double produccionEnero;
     private Double produccionFebrero;
     private Double produccionMarzo;
     private Double produccionAbril;
     private Double produccionMayo;
     private Double produccionJunio;
     private Double produccionJulio;
     private Double produccionAgosto;
     private Double produccionSeptiembre;
     private Double produccionOctubre;
     private Double produccionNoviembre;
     private Double produccionDiciembre;
     private Double produccionTotal;
     private Double velocidadEstandar;
     private Double horasProcesoEst;
     private Double horasProcesoEjec;
     private Double horasMttoProgEst;
     private Double horasMttoProgEjec;
     private Double horasMttoNoProgEst;
     private Double horasMttoNoProgEjec;
     private Double horasPlantaEst;
     private Double horasPlantaEjec;
     private Double valorPromedioHrDia;
     private Long compania;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private String observacion;
     private Long usuarioDigitacion;
     private String observacionAnularReg;
     private Date fechaAnulacion;
     private String estado;
     private String origenDatos;

    public DatPlanAnualFabrica() {
    }

    public DatPlanAnualFabrica(Long consecutivo, Long anio, Double horasArranque, Double produccionEstEnero, Double produccionEstFebrero, Double produccionEstMarzo, Double produccionEstAbril, Double produccionEstMayo, Double produccionEstJunio, Double produccionEstJulio, Double produccionEstAgosto, Double produccionEstSeptiembre, Double produccionEstOctubre, Double produccionEstNoviembre, Double produccionEstDiciembre, Double produccionEstTotal, Double produccionEnero, Double produccionFebrero, Double produccionMarzo, Double produccionAbril, Double produccionMayo, Double produccionJunio, Double produccionJulio, Double produccionAgosto, Double produccionSeptiembre, Double produccionOctubre, Double produccionNoviembre, Double produccionDiciembre, Double produccionTotal, Double velocidadEstandar, Double horasProcesoEst, Double horasProcesoEjec, Double horasMttoProgEst, Double horasMttoProgEjec, Double horasMttoNoProgEst, Double horasMttoNoProgEjec, Double horasPlantaEst, Double horasPlantaEjec, Double valorPromedioHrDia, Long compania, Date fechaCreacion, Date fechaModificacion, String observacion, Long usuarioDigitacion, String observacionAnularReg, Date fechaAnulacion, String estado, String origenDatos) {
       this.consecutivo = consecutivo;
       this.anio = anio;
       this.horasArranque = horasArranque;
       this.produccionEstEnero = produccionEstEnero;
       this.produccionEstFebrero = produccionEstFebrero;
       this.produccionEstMarzo = produccionEstMarzo;
       this.produccionEstAbril = produccionEstAbril;
       this.produccionEstMayo = produccionEstMayo;
       this.produccionEstJunio = produccionEstJunio;
       this.produccionEstJulio = produccionEstJulio;
       this.produccionEstAgosto = produccionEstAgosto;
       this.produccionEstSeptiembre = produccionEstSeptiembre;
       this.produccionEstOctubre = produccionEstOctubre;
       this.produccionEstNoviembre = produccionEstNoviembre;
       this.produccionEstDiciembre = produccionEstDiciembre;
       this.produccionEstTotal = produccionEstTotal;
       this.produccionEnero = produccionEnero;
       this.produccionFebrero = produccionFebrero;
       this.produccionMarzo = produccionMarzo;
       this.produccionAbril = produccionAbril;
       this.produccionMayo = produccionMayo;
       this.produccionJunio = produccionJunio;
       this.produccionJulio = produccionJulio;
       this.produccionAgosto = produccionAgosto;
       this.produccionSeptiembre = produccionSeptiembre;
       this.produccionOctubre = produccionOctubre;
       this.produccionNoviembre = produccionNoviembre;
       this.produccionDiciembre = produccionDiciembre;
       this.produccionTotal = produccionTotal;
       this.velocidadEstandar = velocidadEstandar;
       this.horasProcesoEst = horasProcesoEst;
       this.horasProcesoEjec = horasProcesoEjec;
       this.horasMttoProgEst = horasMttoProgEst;
       this.horasMttoProgEjec = horasMttoProgEjec;
       this.horasMttoNoProgEst = horasMttoNoProgEst;
       this.horasMttoNoProgEjec = horasMttoNoProgEjec;
       this.horasPlantaEst = horasPlantaEst;
       this.horasPlantaEjec = horasPlantaEjec;
       this.valorPromedioHrDia = valorPromedioHrDia;
       this.compania = compania;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.observacion = observacion;
       this.usuarioDigitacion = usuarioDigitacion;
       this.observacionAnularReg = observacionAnularReg;
       this.fechaAnulacion = fechaAnulacion;
       this.estado = estado;
       this.origenDatos = origenDatos;
    }
   
    public Long getDatPlanAnualFabricaId() {
        return this.datPlanAnualFabricaId;
    }
    
    public void setDatPlanAnualFabricaId(Long datPlanAnualFabricaId) {
        this.datPlanAnualFabricaId = datPlanAnualFabricaId;
    }
    public Long getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Long consecutivo) {
        this.consecutivo = consecutivo;
    }
    public Long getAnio() {
        return this.anio;
    }
    
    public void setAnio(Long anio) {
        this.anio = anio;
    }
    
    public Double getProduccionEstEnero() {
        return this.produccionEstEnero;
    }
    
    public void setProduccionEstEnero(Double produccionEstEnero) {
        this.produccionEstEnero = produccionEstEnero;
    }
    public Double getProduccionEstFebrero() {
        return this.produccionEstFebrero;
    }
    
    public void setProduccionEstFebrero(Double produccionEstFebrero) {
        this.produccionEstFebrero = produccionEstFebrero;
    }
    public Double getProduccionEstMarzo() {
        return this.produccionEstMarzo;
    }
    
    public void setProduccionEstMarzo(Double produccionEstMarzo) {
        this.produccionEstMarzo = produccionEstMarzo;
    }
    public Double getProduccionEstAbril() {
        return this.produccionEstAbril;
    }
    
    public void setProduccionEstAbril(Double produccionEstAbril) {
        this.produccionEstAbril = produccionEstAbril;
    }
    public Double getProduccionEstMayo() {
        return this.produccionEstMayo;
    }
    
    public void setProduccionEstMayo(Double produccionEstMayo) {
        this.produccionEstMayo = produccionEstMayo;
    }
    public Double getProduccionEstJunio() {
        return this.produccionEstJunio;
    }
    
    public void setProduccionEstJunio(Double produccionEstJunio) {
        this.produccionEstJunio = produccionEstJunio;
    }
    public Double getProduccionEstJulio() {
        return this.produccionEstJulio;
    }
    
    public void setProduccionEstJulio(Double produccionEstJulio) {
        this.produccionEstJulio = produccionEstJulio;
    }
    public Double getProduccionEstAgosto() {
        return this.produccionEstAgosto;
    }
    
    public void setProduccionEstAgosto(Double produccionEstAgosto) {
        this.produccionEstAgosto = produccionEstAgosto;
    }
    public Double getProduccionEstSeptiembre() {
        return this.produccionEstSeptiembre;
    }
    
    public void setProduccionEstSeptiembre(Double produccionEstSeptiembre) {
        this.produccionEstSeptiembre = produccionEstSeptiembre;
    }
    public Double getProduccionEstOctubre() {
        return this.produccionEstOctubre;
    }
    
    public void setProduccionEstOctubre(Double produccionEstOctubre) {
        this.produccionEstOctubre = produccionEstOctubre;
    }
    public Double getProduccionEstNoviembre() {
        return this.produccionEstNoviembre;
    }
    
    public void setProduccionEstNoviembre(Double produccionEstNoviembre) {
        this.produccionEstNoviembre = produccionEstNoviembre;
    }
    public Double getProduccionEstDiciembre() {
        return this.produccionEstDiciembre;
    }
    
    public void setProduccionEstDiciembre(Double produccionEstDiciembre) {
        this.produccionEstDiciembre = produccionEstDiciembre;
    }
    public Double getProduccionEstTotal() {
        return this.produccionEstTotal;
    }
    
    public void setProduccionEstTotal(Double produccionEstTotal) {
        this.produccionEstTotal = produccionEstTotal;
    }
    public Double getProduccionEnero() {
        return this.produccionEnero;
    }
    
    public void setProduccionEnero(Double produccionEnero) {
        this.produccionEnero = produccionEnero;
    }
    public Double getProduccionFebrero() {
        return this.produccionFebrero;
    }
    
    public void setProduccionFebrero(Double produccionFebrero) {
        this.produccionFebrero = produccionFebrero;
    }
    public Double getProduccionMarzo() {
        return this.produccionMarzo;
    }
    
    public void setProduccionMarzo(Double produccionMarzo) {
        this.produccionMarzo = produccionMarzo;
    }
    public Double getProduccionAbril() {
        return this.produccionAbril;
    }
    
    public void setProduccionAbril(Double produccionAbril) {
        this.produccionAbril = produccionAbril;
    }
    public Double getProduccionMayo() {
        return this.produccionMayo;
    }
    
    public void setProduccionMayo(Double produccionMayo) {
        this.produccionMayo = produccionMayo;
    }
    public Double getProduccionJunio() {
        return this.produccionJunio;
    }
    
    public void setProduccionJunio(Double produccionJunio) {
        this.produccionJunio = produccionJunio;
    }
    public Double getProduccionJulio() {
        return this.produccionJulio;
    }
    
    public void setProduccionJulio(Double produccionJulio) {
        this.produccionJulio = produccionJulio;
    }
    public Double getProduccionAgosto() {
        return this.produccionAgosto;
    }
    
    public void setProduccionAgosto(Double produccionAgosto) {
        this.produccionAgosto = produccionAgosto;
    }
    public Double getProduccionSeptiembre() {
        return this.produccionSeptiembre;
    }
    
    public void setProduccionSeptiembre(Double produccionSeptiembre) {
        this.produccionSeptiembre = produccionSeptiembre;
    }
    public Double getProduccionOctubre() {
        return this.produccionOctubre;
    }
    
    public void setProduccionOctubre(Double produccionOctubre) {
        this.produccionOctubre = produccionOctubre;
    }
    public Double getProduccionNoviembre() {
        return this.produccionNoviembre;
    }
    
    public void setProduccionNoviembre(Double produccionNoviembre) {
        this.produccionNoviembre = produccionNoviembre;
    }
    public Double getProduccionDiciembre() {
        return this.produccionDiciembre;
    }
    
    public void setProduccionDiciembre(Double produccionDiciembre) {
        this.produccionDiciembre = produccionDiciembre;
    }
    public Double getProduccionTotal() {
        return this.produccionTotal;
    }
    
    public void setProduccionTotal(Double produccionTotal) {
        this.produccionTotal = produccionTotal;
    }
    public Double getVelocidadEstandar() {
        return this.velocidadEstandar;
    }
    
    public void setVelocidadEstandar(Double velocidadEstandar) {
        this.velocidadEstandar = velocidadEstandar;
    }
    public Double getHorasProcesoEst() {
        return this.horasProcesoEst;
    }
    
    public void setHorasProcesoEst(Double horasProcesoEst) {
        this.horasProcesoEst = horasProcesoEst;
    }
    public Double getHorasProcesoEjec() {
        return this.horasProcesoEjec;
    }
    
    public void setHorasProcesoEjec(Double horasProcesoEjec) {
        this.horasProcesoEjec = horasProcesoEjec;
    }
    public Double getHorasMttoProgEst() {
        return this.horasMttoProgEst;
    }
    
    public void setHorasMttoProgEst(Double horasMttoProgEst) {
        this.horasMttoProgEst = horasMttoProgEst;
    }
    public Double getHorasMttoProgEjec() {
        return this.horasMttoProgEjec;
    }
    
    public void setHorasMttoProgEjec(Double horasMttoProgEjec) {
        this.horasMttoProgEjec = horasMttoProgEjec;
    }
    public Double getHorasMttoNoProgEst() {
        return this.horasMttoNoProgEst;
    }
    
    public void setHorasMttoNoProgEst(Double horasMttoNoProgEst) {
        this.horasMttoNoProgEst = horasMttoNoProgEst;
    }
    public Double getHorasMttoNoProgEjec() {
        return this.horasMttoNoProgEjec;
    }
    
    public void setHorasMttoNoProgEjec(Double horasMttoNoProgEjec) {
        this.horasMttoNoProgEjec = horasMttoNoProgEjec;
    }
    public Double getHorasPlantaEst() {
        return this.horasPlantaEst;
    }
    
    public void setHorasPlantaEst(Double horasPlantaEst) {
        this.horasPlantaEst = horasPlantaEst;
    }
    public Double getHorasPlantaEjec() {
        return this.horasPlantaEjec;
    }
    
    public void setHorasPlantaEjec(Double horasPlantaEjec) {
        this.horasPlantaEjec = horasPlantaEjec;
    }
    public Double getValorPromedioHrDia() {
        return this.valorPromedioHrDia;
    }
    
    public void setValorPromedioHrDia(Double valorPromedioHrDia) {
        this.valorPromedioHrDia = valorPromedioHrDia;
    }
    public Long getCompania() {
        return this.compania;
    }
    
    public void setCompania(Long compania) {
        this.compania = compania;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Long getUsuarioDigitacion() {
        return this.usuarioDigitacion;
    }
    
    public void setUsuarioDigitacion(Long usuarioDigitacion) {
        this.usuarioDigitacion = usuarioDigitacion;
    }
    public String getObservacionAnularReg() {
        return this.observacionAnularReg;
    }
    
    public void setObservacionAnularReg(String observacionAnularReg) {
        this.observacionAnularReg = observacionAnularReg;
    }
    public Date getFechaAnulacion() {
        return this.fechaAnulacion;
    }
    
    public void setFechaAnulacion(Date fechaAnulacion) {
        this.fechaAnulacion = fechaAnulacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getOrigenDatos() {
        return this.origenDatos;
    }
    
    public void setOrigenDatos(String origenDatos) {
        this.origenDatos = origenDatos;
    }

	/**
	 * @return the horasArranque
	 */
	public Double getHorasArranque() {
		return horasArranque;
	}

	/**
	 * @param horasArranque the horasArranque to set
	 */
	public void setHorasArranque(Double horasArranque) {
		this.horasArranque = horasArranque;
	}




}


