package co.com.arcosoft.modelo;
// Generated 14-oct-2017 19:44:07 by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * DatReporteFallas generated by hbm2java
 */
public class DatReporteFallas  implements java.io.Serializable {


     private Long datReporteFallasId;
     private Equipo equipo;
     private AgenteCausadorParada agenteCausadorParada;
     private Tag tag;
     private MotivosEntradaTaller motivosEntradaTaller;
     private Long consecutivo;
     private Date fechaRegistro;
     private Long trabId;
     private Long supervisorId;
     private Long medidorId;
     private Double horometroActual;
     private String esParada;
     private Date horaInicialParada;
     private Date horaFinalParada;
     private String descripcionFalla;
     private Long compania;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Long usuarioDigitacion;
     private String observacionAnularReg;
     private Date fechaAnulacion;
     private String estado;
     private String origenDatos;
     private Double odometroActual;
     
    public DatReporteFallas() {
    }

    public DatReporteFallas(Double odometroActual, Equipo equipo, AgenteCausadorParada agenteCausadorParada, Tag tag, MotivosEntradaTaller motivosEntradaTaller, Long consecutivo, Date fechaRegistro, Long trabId, Long supervisorId, Long medidorId, Double horometroActual, String esParada, Date horaInicialParada, Date horaFinalParada, String descripcionFalla, Long compania, Date fechaCreacion, Date fechaModificacion, Long usuarioDigitacion, String observacionAnularReg, Date fechaAnulacion, String estado, String origenDatos) {
       this.equipo = equipo;
       this.agenteCausadorParada = agenteCausadorParada;
       this.tag = tag;
       this.motivosEntradaTaller = motivosEntradaTaller;
       this.consecutivo = consecutivo;
       this.fechaRegistro = fechaRegistro;
       this.trabId = trabId;
       this.supervisorId = supervisorId;
       this.medidorId = medidorId;
       this.horometroActual = horometroActual;
       this.esParada = esParada;
       this.horaInicialParada = horaInicialParada;
       this.horaFinalParada = horaFinalParada;
       this.descripcionFalla = descripcionFalla;
       this.compania = compania;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.usuarioDigitacion = usuarioDigitacion;
       this.observacionAnularReg = observacionAnularReg;
       this.fechaAnulacion = fechaAnulacion;
       this.estado = estado;
       this.origenDatos = origenDatos;
       this.odometroActual = odometroActual;
    }
   
    
    public Double getOdometroActual() {
		return odometroActual;
	}

	public void setOdometroActual(Double odometroActual) {
		this.odometroActual = odometroActual;
	}

	public Long getDatReporteFallasId() {
        return this.datReporteFallasId;
    }
    
    public void setDatReporteFallasId(Long datReporteFallasId) {
        this.datReporteFallasId = datReporteFallasId;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public AgenteCausadorParada getAgenteCausadorParada() {
        return this.agenteCausadorParada;
    }
    
    public void setAgenteCausadorParada(AgenteCausadorParada agenteCausadorParada) {
        this.agenteCausadorParada = agenteCausadorParada;
    }
    public Tag getTag() {
        return this.tag;
    }
    
    public void setTag(Tag tag) {
        this.tag = tag;
    }
    public MotivosEntradaTaller getMotivosEntradaTaller() {
        return this.motivosEntradaTaller;
    }
    
    public void setMotivosEntradaTaller(MotivosEntradaTaller motivosEntradaTaller) {
        this.motivosEntradaTaller = motivosEntradaTaller;
    }
    public Long getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Long consecutivo) {
        this.consecutivo = consecutivo;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Long getTrabId() {
        return this.trabId;
    }
    
    public void setTrabId(Long trabId) {
        this.trabId = trabId;
    }
    public Long getSupervisorId() {
        return this.supervisorId;
    }
    
    public void setSupervisorId(Long supervisorId) {
        this.supervisorId = supervisorId;
    }
    public Long getMedidorId() {
        return this.medidorId;
    }
    
    public void setMedidorId(Long medidorId) {
        this.medidorId = medidorId;
    }
    public Double getHorometroActual() {
        return this.horometroActual;
    }
    
    public void setHorometroActual(Double horometroActual) {
        this.horometroActual = horometroActual;
    }
    public String getEsParada() {
        return this.esParada;
    }
    
    public void setEsParada(String esParada) {
        this.esParada = esParada;
    }
    public Date getHoraInicialParada() {
        return this.horaInicialParada;
    }
    
    public void setHoraInicialParada(Date horaInicialParada) {
        this.horaInicialParada = horaInicialParada;
    }
    public Date getHoraFinalParada() {
        return this.horaFinalParada;
    }
    
    public void setHoraFinalParada(Date horaFinalParada) {
        this.horaFinalParada = horaFinalParada;
    }
    public String getDescripcionFalla() {
        return this.descripcionFalla;
    }
    
    public void setDescripcionFalla(String descripcionFalla) {
        this.descripcionFalla = descripcionFalla;
    }
    public Long getCompania() {
        return this.compania;
    }
    
    public void setCompania(Long compania) {
        this.compania = compania;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Long getUsuarioDigitacion() {
        return this.usuarioDigitacion;
    }
    
    public void setUsuarioDigitacion(Long usuarioDigitacion) {
        this.usuarioDigitacion = usuarioDigitacion;
    }
    public String getObservacionAnularReg() {
        return this.observacionAnularReg;
    }
    
    public void setObservacionAnularReg(String observacionAnularReg) {
        this.observacionAnularReg = observacionAnularReg;
    }
    public Date getFechaAnulacion() {
        return this.fechaAnulacion;
    }
    
    public void setFechaAnulacion(Date fechaAnulacion) {
        this.fechaAnulacion = fechaAnulacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getOrigenDatos() {
        return this.origenDatos;
    }
    
    public void setOrigenDatos(String origenDatos) {
        this.origenDatos = origenDatos;
    }




}


