package co.com.arcosoft.modelo;
// Generated 19/12/2018 09:55:22 PM by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DatReqProductos generated by hbm2java
 */
public class DatReqProductos  implements java.io.Serializable {


     private Long datReqProductosId;
     private Long consecutivo;
     private Long compania;
     private Date fechaRegistro;
     private Long usuarioDigitacion;
     private Date fechaCreacion;
     private String estado;
     private String observacionAnularReg;
     private Date fechaAnulacion;
     private String observacion;
     private Date fechaModificacion;
     private Set<DatReqProductosDet> datReqProductosDets = new HashSet<DatReqProductosDet>(0);

    public DatReqProductos() {
    }

    public DatReqProductos(Long consecutivo, Long compania, Date fechaRegistro, Long usuarioDigitacion, Date fechaCreacion, String estado, String observacionAnularReg, Date fechaAnulacion, String observacion, Date fechaModificacion, Set<DatReqProductosDet> datReqProductosDets) {
       this.consecutivo = consecutivo;
       this.compania = compania;
       this.fechaRegistro = fechaRegistro;
       this.usuarioDigitacion = usuarioDigitacion;
       this.fechaCreacion = fechaCreacion;
       this.estado = estado;
       this.observacionAnularReg = observacionAnularReg;
       this.fechaAnulacion = fechaAnulacion;
       this.observacion = observacion;
       this.fechaModificacion = fechaModificacion;
       this.datReqProductosDets = datReqProductosDets;
    }
   
    public Long getDatReqProductosId() {
        return this.datReqProductosId;
    }
    
    public void setDatReqProductosId(Long datReqProductosId) {
        this.datReqProductosId = datReqProductosId;
    }
    public Long getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Long consecutivo) {
        this.consecutivo = consecutivo;
    }
    public Long getCompania() {
        return this.compania;
    }
    
    public void setCompania(Long compania) {
        this.compania = compania;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Long getUsuarioDigitacion() {
        return this.usuarioDigitacion;
    }
    
    public void setUsuarioDigitacion(Long usuarioDigitacion) {
        this.usuarioDigitacion = usuarioDigitacion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservacionAnularReg() {
        return this.observacionAnularReg;
    }
    
    public void setObservacionAnularReg(String observacionAnularReg) {
        this.observacionAnularReg = observacionAnularReg;
    }
    public Date getFechaAnulacion() {
        return this.fechaAnulacion;
    }
    
    public void setFechaAnulacion(Date fechaAnulacion) {
        this.fechaAnulacion = fechaAnulacion;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set<DatReqProductosDet> getDatReqProductosDets() {
        return this.datReqProductosDets;
    }
    
    public void setDatReqProductosDets(Set<DatReqProductosDet> datReqProductosDets) {
        this.datReqProductosDets = datReqProductosDets;
    }




}


