package co.com.arcosoft.modelo;
// Generated 21-jul-2016 7:22:02 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * DatServicioDet generated by hbm2java
 */
public class DatServicioDet implements java.io.Serializable {

	private Long datServicioDetId;
	private UdadMed udadMedByUdadMedPago;
	private Equipo equipo;
	private UdadMed udadMedByUdadMedProd;
	private Long persEmpr;
	private DatServicio datServicioId;
	private Date horaInicial;
	private Date horaFinal;
	private Double tiempoInactivo;
	private Double totalHoras;
	private Double cantidadPago;
	private Double cantidadProd;
	private Double valorUnit;
	private Double costoTotal;
	private Double horometroInicial;
	private Double horometroFinal;
	private DatPlanLaborDet ordenTrabajo;
	private Nivel4 nivel4;
	private Nivel2 nivel2Id;
	private Labor laborId;
	private DatPlanillaNomina datPlanillaNominaId;
	private Long etapaId;
	private Long variedId;
	private Double edad;
	
	public DatServicioDet() {
	}

	public DatServicioDet(Long datServicioDetId) {
		this.datServicioDetId = datServicioDetId;
	}

	public DatServicioDet(Long datServicioDetId, UdadMed udadMedByUdadMedPago, Equipo equipo,
			UdadMed udadMedByUdadMedProd, Long persEmpr, DatServicio datServicioId, Date horaInicial, Date horaFinal,
			Double tiempoInactivo, Double totalHoras, Double cantidadPago, Double cantidadProd, 
			Double valorUnit, Double costoTotal, Double horometroInicial, Double horometroFinal,
			 DatPlanLaborDet ordenTrabajo,  Nivel2 nivel2Id, Nivel4 nivel4, Labor laborId, 	DatPlanillaNomina datPlanillaNominaId
			, Long etapaId, Long variedId, Double edad	) {
		this.datServicioDetId = datServicioDetId;
		this.udadMedByUdadMedPago = udadMedByUdadMedPago;
		this.equipo = equipo;
		this.udadMedByUdadMedProd = udadMedByUdadMedProd;
		this.persEmpr = persEmpr;
		this.datServicioId = datServicioId;
		this.horaInicial = horaInicial;
		this.horaFinal = horaFinal;
		this.tiempoInactivo = tiempoInactivo;
		this.totalHoras = totalHoras;
		this.cantidadPago = cantidadPago;
		this.cantidadProd = cantidadProd;
		this.valorUnit = valorUnit;
		this.costoTotal = costoTotal;
		this.horometroInicial = horometroInicial;
		this.horometroFinal = horometroFinal;
		
		this.ordenTrabajo = ordenTrabajo;
		this.nivel2Id = nivel2Id;
		this.nivel4= nivel4;
		this.laborId=laborId;
		this.datPlanillaNominaId = datPlanillaNominaId;
		this.etapaId = etapaId;
		this.variedId= variedId;
		this.edad=edad;
	}
	
	

	public Double getEdad() {
		return edad;
	}

	public void setEdad(Double edad) {
		this.edad = edad;
	}

	public Long getEtapaId() {
		return etapaId;
	}

	public void setEtapaId(Long etapaId) {
		this.etapaId = etapaId;
	}

	public Long getVariedId() {
		return variedId;
	}

	public void setVariedId(Long variedId) {
		this.variedId = variedId;
	}
	public DatPlanillaNomina getDatPlanillaNominaId() {
		return datPlanillaNominaId;
	}

	public void setDatPlanillaNominaId(DatPlanillaNomina datPlanillaNominaId) {
		this.datPlanillaNominaId = datPlanillaNominaId;
	}

	public Nivel4 getNivel4() {
		return nivel4;
	}

	public void setNivel4(Nivel4 nivel4) {
		this.nivel4 = nivel4;
	}


	public DatPlanLaborDet getOrdenTrabajo() {
		return ordenTrabajo;
	}

	public void setOrdenTrabajo(DatPlanLaborDet ordenTrabajo) {
		this.ordenTrabajo = ordenTrabajo;
	}

	public Nivel2 getNivel2Id() {
		return nivel2Id;
	}

	public void setNivel2Id(Nivel2 nivel2Id) {
		this.nivel2Id = nivel2Id;
	}

	public Labor getLaborId() {
		return laborId;
	}

	public void setLaborId(Labor laborId) {
		this.laborId = laborId;
	}

	public Long getDatServicioDetId() {
		return this.datServicioDetId;
	}

	public void setDatServicioDetId(Long datServicioDetId) {
		this.datServicioDetId = datServicioDetId;
	}

	public UdadMed getUdadMedByUdadMedPago() {
		return this.udadMedByUdadMedPago;
	}

	public void setUdadMedByUdadMedPago(UdadMed udadMedByUdadMedPago) {
		this.udadMedByUdadMedPago = udadMedByUdadMedPago;
	}

	public Equipo getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}

	public UdadMed getUdadMedByUdadMedProd() {
		return this.udadMedByUdadMedProd;
	}

	public void setUdadMedByUdadMedProd(UdadMed udadMedByUdadMedProd) {
		this.udadMedByUdadMedProd = udadMedByUdadMedProd;
	}

	public Long getPersEmpr() {
		return this.persEmpr;
	}

	public void setPersEmpr(Long persEmpr) {
		this.persEmpr = persEmpr;
	}

	public DatServicio getDatServicioId() {
		return this.datServicioId;
	}

	public void setDatServicioId(DatServicio datServicioId) {
		this.datServicioId = datServicioId;
	}

	public Date getHoraInicial() {
		return this.horaInicial;
	}

	public void setHoraInicial(Date horaInicial) {
		this.horaInicial = horaInicial;
	}

	public Date getHoraFinal() {
		return this.horaFinal;
	}

	public void setHoraFinal(Date horaFinal) {
		this.horaFinal = horaFinal;
	}

	public Double getTiempoInactivo() {
		return this.tiempoInactivo;
	}

	public void setTiempoInactivo(Double tiempoInactivo) {
		this.tiempoInactivo = tiempoInactivo;
	}

	public Double getTotalHoras() {
		return this.totalHoras;
	}

	public void setTotalHoras(Double totalHoras) {
		this.totalHoras = totalHoras;
	}

	public Double getCantidadPago() {
		return this.cantidadPago;
	}

	public void setCantidadPago(Double cantidadPago) {
		this.cantidadPago = cantidadPago;
	}

	public Double getCantidadProd() {
		return this.cantidadProd;
	}

	public void setCantidadProd(Double cantidadProd) {
		this.cantidadProd = cantidadProd;
	}

	public Double getValorUnit() {
		return this.valorUnit;
	}

	public void setValorUnit(Double valorUnit) {
		this.valorUnit = valorUnit;
	}

	public Double getCostoTotal() {
		return this.costoTotal;
	}

	public void setCostoTotal(Double costoTotal) {
		this.costoTotal = costoTotal;
	}

	public Double getHorometroInicial() {
		return horometroInicial;
	}

	public Double getHorometroFinal() {
		return horometroFinal;
	}

	public void setHorometroInicial(Double horometroInicial) {
		this.horometroInicial = horometroInicial;
	}

	public void setHorometroFinal(Double horometroFinal) {
		this.horometroFinal = horometroFinal;
	}

}
