package co.com.arcosoft.modelo;

// Generated 08-sep-2015 22:35:03 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DatTransProd generated by hbm2java
 */
public class DatTransProd implements java.io.Serializable {

	private Long datTransProdId;
	private Long transportadora;
	private Long nivel4;
	private Long modalidadCosecha;
	private Long proveedor;
	private Long frenteCos;
	private Long empresaCompradora;
	private Long conductor;
	private Long vehiculosTransp;
	private Date fechaRegistro;
	private Long consecutivo;
	private Long consecutivoPesoNeto;
	private String tipoTransaccion;
	private String destinoProduccion;
	public Long compania;
	private Long nivel1Id;
	private Long nivel2Id;
	private Long nivel3Id;
	private Double edadNivel4;
	private Long variedNivel4;
	private Long etapaNivel4;
	private Long anioFiscalNivel4;
	private Long faseFenoNivel4;
	private String observacion;
	private String mobileId;
	private Long usuarioDigitacion;
	private String infoAdicional;
	private String infoAdicional2;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String estado;
	private String observacionAnularReg;
	private Date fechaAnulacion;
	private String vagon1;
	private String vagon2;
	private String vagon3;
	private Date fechaEntrada;
	private Date fechaSalida;
	private Date fechaPesoBruto;
	private Date fechaTara;
	private Date fechaPesoNeto;
	private String numeroSellos;
	private Long basculaTara;
	private Long basculaPesoBruto;
	private Long usuarioPesoTara;
	private Long usuarioPesoBruto;
	private Double pesoBruto;
	private Double pesoTara;
	private Double pesoNeto;
	private Double variable1;
	private Double variable2;
	private Double variable3;
	private Double variable4;
	private Double variable5;
	private Double variable6;
	private Double variable7;
	private Double variable8;
	private Double variable9;
	private Double variable10;
	private String observacionAnalisis;
	private Double valorUnitario;
	private Double valorTotal;
	private Double valorDeduccion;
	private Double valorNeto;
	private Double cantidadKilosLiq;
	private Date fechaInicial;
	private String observacion2;
	private String observacion3;
    private Long vehiculoId;
	private Date fechaEstadoVehiculo;
    
	private Set<DatTransProdNivel4> datTransProdNivel4s = new HashSet<DatTransProdNivel4>(0);
	private Set<DatTransProdDet> datTransProdDets = new HashSet<DatTransProdDet>(0);
	private Set<DatAnaTransProd> datAnaTransProds = new HashSet<DatAnaTransProd>(0);
	private Set<DatTransProdTrabajadores> datTransProdTrabajadoreses = new HashSet<DatTransProdTrabajadores>(0);

	private String sello1;
	private String sello2;
	private String sello3;
	private String sello4;
	private String sello5;

	private String sello6;
	private String sello7;
	private String sello8;
	private String sello9;
	private String sello10;
	
	private String tipoPesajeBruto;
	private String tipoPesajeTara;
	private String noDocumento;
	private String origen;
	private String variableTexto1;
	
	public DatTransProd() {
	}

	public DatTransProd(Long datTransProdId) {
		this.datTransProdId = datTransProdId;
	}

	public DatTransProd(Long datTransProdId, Long transportadora, Long nivel4, Long modalidadCosecha, Long proveedor,
			Long frenteCos, Long empresaCompradora, Long conductor, Long vehiculosTransp, Date fechaRegistro,
			Long consecutivo, String tipoTransaccion, String destinoProduccion, Long compania, Long nivel1Id,
			Long nivel2Id, Long nivel3Id, Double edadNivel4, Long variedNivel4, Long etapaNivel4, Long anioFiscalNivel4,
			Long faseFenoNivel4, String observacion, String mobileId, Long usuarioDigitacion, String infoAdicional,
			String infoAdicional2, Date fechaCreacion, Date fechaModificacion, String estado,
			String observacionAnularReg, Set<DatTransProdDet> datTransProdDets, Date fechaInicial, Double valorUnitario,
			Double valorTotal, Double valorDeduccion, Double valorNeto, Double cantidadKilosLiq, String observacion2, String observacion3,

			Set<DatAnaTransProd> datAnaTransProds, Date fechaAnulacion, Set<DatTransProdNivel4> datTransProdNivel4s,
			String vagon1, String vagon2, String vagon3, Date fechaEntrada, Date fechaSalida, Date fechaPesoBruto,
			Date fechaTara, Date fechaPesoNeto, String numeroSellos, Long basculaTara, Long basculaPesoBruto,
			Long usuarioPesoTara, Long usuarioPesoBruto, Double pesoBruto, Double pesoTara, Double pesoNeto,

			Double variable1, Double variable2, Double variable3, Double variable4, Double variable5, Double variable6,
			Double variable7, Double variable8, Double variable9, Double variable10, String observacionAnalisis,
			Set<DatTransProdTrabajadores> datTransProdTrabajadoreses, String noDocumento, String origen,
		     Long vehiculoId	,

		     String sello1, String sello2, String sello3, String sello4, String sello5,
		     String sello6, String sello7, String sello8, String sello9, String sello10,
		     String tipoPesajeBruto,
				String tipoPesajeTara, String variableTexto1) {
		this.datTransProdId = datTransProdId;
		this.transportadora = transportadora;
		this.nivel4 = nivel4;
		this.modalidadCosecha = modalidadCosecha;
		this.proveedor = proveedor;
		this.frenteCos = frenteCos;
		this.empresaCompradora = empresaCompradora;
		this.conductor = conductor;
		this.vehiculosTransp = vehiculosTransp;
		this.fechaRegistro = fechaRegistro;
		this.consecutivo = consecutivo;
		this.tipoTransaccion = tipoTransaccion;
		this.destinoProduccion = destinoProduccion;
		this.compania = compania;
		this.nivel1Id = nivel1Id;
		this.nivel2Id = nivel2Id;
		this.nivel3Id = nivel3Id;
		this.edadNivel4 = edadNivel4;
		this.variedNivel4 = variedNivel4;
		this.etapaNivel4 = etapaNivel4;
		this.anioFiscalNivel4 = anioFiscalNivel4;
		this.faseFenoNivel4 = faseFenoNivel4;
		this.observacion = observacion;
		this.mobileId = mobileId;
		this.usuarioDigitacion = usuarioDigitacion;
		this.infoAdicional = infoAdicional;
		this.infoAdicional2 = infoAdicional2;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.estado = estado;
		this.observacionAnularReg = observacionAnularReg;
		this.datTransProdDets = datTransProdDets;
		this.datAnaTransProds = datAnaTransProds;
		this.fechaAnulacion = fechaAnulacion;
		this.datTransProdNivel4s = datTransProdNivel4s;
		this.vagon1 = vagon1;
		this.vagon2 = vagon2;
		this.vagon3 = vagon3;
		this.fechaEntrada = fechaEntrada;
		this.fechaSalida = fechaSalida;
		this.fechaPesoBruto = fechaPesoBruto;
		this.fechaTara = fechaTara;
		this.fechaPesoNeto = fechaPesoNeto;
		this.numeroSellos = numeroSellos;
		this.basculaTara = basculaTara;
		this.basculaPesoBruto = basculaPesoBruto;
		this.usuarioPesoTara = usuarioPesoTara;
		this.usuarioPesoBruto = usuarioPesoBruto;
		this.pesoBruto = pesoBruto;
		this.pesoTara = pesoTara;
		this.pesoNeto = pesoNeto;
		this.variable1 = variable1;
		this.variable2 = variable2;
		this.variable3 = variable3;
		this.variable4 = variable4;
		this.variable5 = variable5;
		this.variable6 = variable6;
		this.variable7 = variable7;
		this.variable8 = variable8;
		this.variable9 = variable9;
		this.variable10 = variable10;
		this.observacionAnalisis = observacionAnalisis;
		this.datTransProdTrabajadoreses = datTransProdTrabajadoreses;
		this.fechaInicial = fechaInicial;
		this.valorUnitario = valorUnitario;
		this.valorTotal = valorTotal;
		this.valorDeduccion = valorDeduccion;
		this.valorNeto = valorNeto;
		this.cantidadKilosLiq = cantidadKilosLiq;
		this.vehiculoId = vehiculoId;
		this.sello1 = sello1;
		this.sello2 = sello2;
		this.sello3 = sello3;
		this.sello4 = sello4;
		this.sello5 = sello5;
		this.sello6 = sello6;
		this.sello7 = sello7;
		this.sello8 = sello8;
		this.sello9 = sello9;
		this.sello10 = sello10;
		this.tipoPesajeBruto = tipoPesajeBruto;
		this.tipoPesajeTara = tipoPesajeTara;
		this.observacion2 = observacion2;
		this.observacion3 = observacion3;
		this.origen = origen;
		this.noDocumento = noDocumento;
		this.variableTexto1=variableTexto1;
	}
	
	
	

	
	public String getVariableTexto1() {
		return variableTexto1;
	}

	public void setVariableTexto1(String variableTexto1) {
		this.variableTexto1 = variableTexto1;
	}

	/**
	 * @return the tipoPesajeBruto
	 */
	public String getTipoPesajeBruto() {
		return tipoPesajeBruto;
	}

	/**
	 * @param tipoPesajeBruto the tipoPesajeBruto to set
	 */
	public void setTipoPesajeBruto(String tipoPesajeBruto) {
		this.tipoPesajeBruto = tipoPesajeBruto;
	}

	/**
	 * @return the tipoPesajeTara
	 */
	public String getTipoPesajeTara() {
		return tipoPesajeTara;
	}

	/**
	 * @param tipoPesajeTara the tipoPesajeTara to set
	 */
	public void setTipoPesajeTara(String tipoPesajeTara) {
		this.tipoPesajeTara = tipoPesajeTara;
	}

	public Long getVehiculoId() {
		return vehiculoId;
	}

	public void setVehiculoId(Long vehiculoId) {
		this.vehiculoId = vehiculoId;
	}

	public Date getFechaInicial() {
		return fechaInicial;
	}

	public void setFechaInicial(Date fechaInicial) {
		this.fechaInicial = fechaInicial;
	}

	public Double getValorUnitario() {
		return valorUnitario;
	}

	public void setValorUnitario(Double valorUnitario) {
		this.valorUnitario = valorUnitario;
	}

	public Double getValorTotal() {
		return valorTotal;
	}

	public void setValorTotal(Double valorTotal) {
		this.valorTotal = valorTotal;
	}

	public Double getValorDeduccion() {
		return valorDeduccion;
	}

	public void setValorDeduccion(Double valorDeduccion) {
		this.valorDeduccion = valorDeduccion;
	}

	public Double getValorNeto() {
		return valorNeto;
	}

	public void setValorNeto(Double valorNeto) {
		this.valorNeto = valorNeto;
	}

	public Double getCantidadKilosLiq() {
		return cantidadKilosLiq;
	}

	public void setCantidadKilosLiq(Double cantidadKilosLiq) {
		this.cantidadKilosLiq = cantidadKilosLiq;
	}

	public Set<DatTransProdTrabajadores> getDatTransProdTrabajadoreses() {
		return datTransProdTrabajadoreses;
	}

	public void setDatTransProdTrabajadoreses(Set<DatTransProdTrabajadores> datTransProdTrabajadoreses) {
		this.datTransProdTrabajadoreses = datTransProdTrabajadoreses;
	}

	public String getObservacionAnalisis() {
		return observacionAnalisis;
	}

	public void setObservacionAnalisis(String observacionAnalisis) {
		this.observacionAnalisis = observacionAnalisis;
	}

	public Double getVariable1() {
		return variable1;
	}

	public void setVariable1(Double variable1) {
		this.variable1 = variable1;
	}

	public Double getVariable2() {
		return variable2;
	}

	public void setVariable2(Double variable2) {
		this.variable2 = variable2;
	}

	public Double getVariable3() {
		return variable3;
	}

	public void setVariable3(Double variable3) {
		this.variable3 = variable3;
	}

	public Double getVariable4() {
		return variable4;
	}

	public void setVariable4(Double variable4) {
		this.variable4 = variable4;
	}

	public Double getVariable5() {
		return variable5;
	}

	public void setVariable5(Double variable5) {
		this.variable5 = variable5;
	}

	public Double getVariable6() {
		return variable6;
	}

	public void setVariable6(Double variable6) {
		this.variable6 = variable6;
	}

	public Double getVariable7() {
		return variable7;
	}

	public void setVariable7(Double variable7) {
		this.variable7 = variable7;
	}

	public Double getVariable8() {
		return variable8;
	}

	public void setVariable8(Double variable8) {
		this.variable8 = variable8;
	}

	public Double getVariable9() {
		return variable9;
	}

	public void setVariable9(Double variable9) {
		this.variable9 = variable9;
	}

	public Double getVariable10() {
		return variable10;
	}

	public void setVariable10(Double variable10) {
		this.variable10 = variable10;
	}

	public String getVagon1() {
		return vagon1;
	}

	public void setVagon1(String vagon1) {
		this.vagon1 = vagon1;
	}

	public String getVagon2() {
		return vagon2;
	}

	public void setVagon2(String vagon2) {
		this.vagon2 = vagon2;
	}

	public String getVagon3() {
		return vagon3;
	}

	public void setVagon3(String vagon3) {
		this.vagon3 = vagon3;
	}

	public Date getFechaEntrada() {
		return fechaEntrada;
	}

	public void setFechaEntrada(Date fechaEntrada) {
		this.fechaEntrada = fechaEntrada;
	}

	public Date getFechaSalida() {
		return fechaSalida;
	}

	public void setFechaSalida(Date fechaSalida) {
		this.fechaSalida = fechaSalida;
	}

	public Date getFechaPesoBruto() {
		return fechaPesoBruto;
	}

	public void setFechaPesoBruto(Date fechaPesoBruto) {
		this.fechaPesoBruto = fechaPesoBruto;
	}

	public Date getFechaTara() {
		return fechaTara;
	}

	public void setFechaTara(Date fechaTara) {
		this.fechaTara = fechaTara;
	}

	public Date getFechaPesoNeto() {
		return fechaPesoNeto;
	}

	public void setFechaPesoNeto(Date fechaPesoNeto) {
		this.fechaPesoNeto = fechaPesoNeto;
	}

	public String getNumeroSellos() {
		return numeroSellos;
	}

	public void setNumeroSellos(String numeroSellos) {
		this.numeroSellos = numeroSellos;
	}

	public Long getBasculaTara() {
		return basculaTara;
	}

	public void setBasculaTara(Long basculaTara) {
		this.basculaTara = basculaTara;
	}

	public Long getBasculaPesoBruto() {
		return basculaPesoBruto;
	}

	public void setBasculaPesoBruto(Long basculaPesoBruto) {
		this.basculaPesoBruto = basculaPesoBruto;
	}

	public Long getUsuarioPesoTara() {
		return usuarioPesoTara;
	}

	public void setUsuarioPesoTara(Long usuarioPesoTara) {
		this.usuarioPesoTara = usuarioPesoTara;
	}

	public Long getUsuarioPesoBruto() {
		return usuarioPesoBruto;
	}

	public void setUsuarioPesoBruto(Long usuarioPesoBruto) {
		this.usuarioPesoBruto = usuarioPesoBruto;
	}

	public Double getPesoBruto() {
		return pesoBruto;
	}

	public void setPesoBruto(Double pesoBruto) {
		this.pesoBruto = pesoBruto;
	}

	public Double getPesoTara() {
		return pesoTara;
	}

	public void setPesoTara(Double pesoTara) {
		this.pesoTara = pesoTara;
	}

	public Double getPesoNeto() {
		return pesoNeto;
	}

	public void setPesoNeto(Double pesoNeto) {
		this.pesoNeto = pesoNeto;
	}

	public Long getDatTransProdId() {
		return this.datTransProdId;
	}

	public void setDatTransProdId(Long datTransProdId) {
		this.datTransProdId = datTransProdId;
	}

	public Long getTransportadora() {
		return this.transportadora;
	}

	public void setTransportadora(Long transportadora) {
		this.transportadora = transportadora;
	}

	public Long getNivel4() {
		return this.nivel4;
	}

	public void setNivel4(Long nivel4) {
		this.nivel4 = nivel4;
	}

	public Long getModalidadCosecha() {
		return this.modalidadCosecha;
	}

	public void setModalidadCosecha(Long modalidadCosecha) {
		this.modalidadCosecha = modalidadCosecha;
	}

	public Long getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Long proveedor) {
		this.proveedor = proveedor;
	}

	public Long getFrenteCos() {
		return this.frenteCos;
	}

	public void setFrenteCos(Long frenteCos) {
		this.frenteCos = frenteCos;
	}

	public Long getEmpresaCompradora() {
		return this.empresaCompradora;
	}

	public void setEmpresaCompradora(Long empresaCompradora) {
		this.empresaCompradora = empresaCompradora;
	}

	public Long getConductor() {
		return this.conductor;
	}

	public void setConductor(Long conductor) {
		this.conductor = conductor;
	}

	public Long getVehiculosTransp() {
		return this.vehiculosTransp;
	}

	public void setVehiculosTransp(Long vehiculosTransp) {
		this.vehiculosTransp = vehiculosTransp;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public Long getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(Long consecutivo) {
		this.consecutivo = consecutivo;
	}

	public String getTipoTransaccion() {
		return this.tipoTransaccion;
	}

	public void setTipoTransaccion(String tipoTransaccion) {
		this.tipoTransaccion = tipoTransaccion;
	}

	public String getDestinoProduccion() {
		return this.destinoProduccion;
	}

	public void setDestinoProduccion(String destinoProduccion) {
		this.destinoProduccion = destinoProduccion;
	}

	public Long getCompania() {
		return this.compania;
	}

	public void setCompania(Long compania) {
		this.compania = compania;
	}

	public Long getNivel1Id() {
		return this.nivel1Id;
	}

	public void setNivel1Id(Long nivel1Id) {
		this.nivel1Id = nivel1Id;
	}

	public Long getNivel2Id() {
		return this.nivel2Id;
	}

	public void setNivel2Id(Long nivel2Id) {
		this.nivel2Id = nivel2Id;
	}

	public Long getNivel3Id() {
		return this.nivel3Id;
	}

	public void setNivel3Id(Long nivel3Id) {
		this.nivel3Id = nivel3Id;
	}

	public Double getEdadNivel4() {
		return this.edadNivel4;
	}

	public void setEdadNivel4(Double edadNivel4) {
		this.edadNivel4 = edadNivel4;
	}

	public Long getVariedNivel4() {
		return this.variedNivel4;
	}

	public void setVariedNivel4(Long variedNivel4) {
		this.variedNivel4 = variedNivel4;
	}

	public Long getEtapaNivel4() {
		return this.etapaNivel4;
	}

	public void setEtapaNivel4(Long etapaNivel4) {
		this.etapaNivel4 = etapaNivel4;
	}

	public Long getAnioFiscalNivel4() {
		return this.anioFiscalNivel4;
	}

	public void setAnioFiscalNivel4(Long anioFiscalNivel4) {
		this.anioFiscalNivel4 = anioFiscalNivel4;
	}

	public Long getFaseFenoNivel4() {
		return this.faseFenoNivel4;
	}

	public void setFaseFenoNivel4(Long faseFenoNivel4) {
		this.faseFenoNivel4 = faseFenoNivel4;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public String getMobileId() {
		return this.mobileId;
	}

	public void setMobileId(String mobileId) {
		this.mobileId = mobileId;
	}

	public Long getUsuarioDigitacion() {
		return this.usuarioDigitacion;
	}

	public void setUsuarioDigitacion(Long usuarioDigitacion) {
		this.usuarioDigitacion = usuarioDigitacion;
	}

	public String getInfoAdicional() {
		return this.infoAdicional;
	}

	public void setInfoAdicional(String infoAdicional) {
		this.infoAdicional = infoAdicional;
	}

	public String getInfoAdicional2() {
		return this.infoAdicional2;
	}

	public void setInfoAdicional2(String infoAdicional2) {
		this.infoAdicional2 = infoAdicional2;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getObservacionAnularReg() {
		return this.observacionAnularReg;
	}

	public void setObservacionAnularReg(String observacionAnularReg) {
		this.observacionAnularReg = observacionAnularReg;
	}

	public Set<DatTransProdDet> getDatTransProdDets() {
		return this.datTransProdDets;
	}

	public void setDatTransProdDets(Set<DatTransProdDet> datTransProdDets) {
		this.datTransProdDets = datTransProdDets;
	}

	public Set<DatAnaTransProd> getDatAnaTransProds() {
		return this.datAnaTransProds;
	}

	public void setDatAnaTransProds(Set<DatAnaTransProd> datAnaTransProds) {
		this.datAnaTransProds = datAnaTransProds;
	}

	public Date getFechaAnulacion() {
		return fechaAnulacion;
	}

	public void setFechaAnulacion(Date fechaAnulacion) {
		this.fechaAnulacion = fechaAnulacion;
	}

	public Set<DatTransProdNivel4> getDatTransProdNivel4s() {
		return datTransProdNivel4s;
	}

	public void setDatTransProdNivel4s(Set<DatTransProdNivel4> datTransProdNivel4s) {
		this.datTransProdNivel4s = datTransProdNivel4s;
	}

	public String getObservacion2() {
		return observacion2;
	}

	public void setObservacion2(String observacion2) {
		this.observacion2 = observacion2;
	}

	public String getObservacion3() {
		return observacion3;
	}

	public void setObservacion3(String observacion3) {
		this.observacion3 = observacion3;
	}

	public String getNoDocumento() {
		return noDocumento;
	}

	public void setNoDocumento(String noDocumento) {
		this.noDocumento = noDocumento;
	}

	public String getOrigen() {
		return origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	public String getSello1() {
		return sello1;
	}

	public void setSello1(String sello1) {
		this.sello1 = sello1;
	}

	public String getSello2() {
		return sello2;
	}

	public void setSello2(String sello2) {
		this.sello2 = sello2;
	}

	public String getSello3() {
		return sello3;
	}

	public void setSello3(String sello3) {
		this.sello3 = sello3;
	}

	public String getSello4() {
		return sello4;
	}

	public void setSello4(String sello4) {
		this.sello4 = sello4;
	}

	public String getSello5() {
		return sello5;
	}

	public void setSello5(String sello5) {
		this.sello5 = sello5;
	}

	public String getSello6() {
		return sello6;
	}

	public void setSello6(String sello6) {
		this.sello6 = sello6;
	}

	public String getSello7() {
		return sello7;
	}

	public void setSello7(String sello7) {
		this.sello7 = sello7;
	}

	public String getSello8() {
		return sello8;
	}

	public void setSello8(String sello8) {
		this.sello8 = sello8;
	}

	public String getSello9() {
		return sello9;
	}

	public void setSello9(String sello9) {
		this.sello9 = sello9;
	}

	public String getSello10() {
		return sello10;
	}

	public void setSello10(String sello10) {
		this.sello10 = sello10;
	}

	public Long getConsecutivoPesoNeto() {
		return consecutivoPesoNeto;
	}

	public void setConsecutivoPesoNeto(Long consecutivoPesoNeto) {
		this.consecutivoPesoNeto = consecutivoPesoNeto;
	}

	public Date getFechaEstadoVehiculo() {
		return fechaEstadoVehiculo;
	}

	public void setFechaEstadoVehiculo(Date fechaEstadoVehiculo) {
		this.fechaEstadoVehiculo = fechaEstadoVehiculo;
	}

}
