package co.com.arcosoft.modelo;

// Generated 05-ago-2015 14:10:19 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * DistSiembra generated by hbm2java
 */
public class DistSiembra implements java.io.Serializable {

	private Long distSiembraId;
	private String codigo;
	private Cultivo cultivo;
	private String nombre;
	public Long compania;
	private String infoAdicional;
	private String infoAdicional2;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String estado;
	private Double distanciaSiembra;
	private Double nroCalles;

	public DistSiembra() {
	}

	public DistSiembra(Long distSiembraId) {
		this.distSiembraId = distSiembraId;
	}

	public DistSiembra(Long distSiembraId, String codigo, Cultivo cultivo, String nombre, Long compania,
			String infoAdicional, Double nroCalles, String infoAdicional2, Date fechaCreacion, Date fechaModificacion,
			String estado, Double distanciaSiembra) {
		this.distSiembraId = distSiembraId;
		this.codigo = codigo;
		this.nroCalles = nroCalles;
		this.cultivo = cultivo;
		this.nombre = nombre;
		this.compania = compania;
		this.infoAdicional = infoAdicional;
		this.infoAdicional2 = infoAdicional2;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.estado = estado;
		this.distanciaSiembra = distanciaSiembra;
	}

	public Double getNroCalles() {
		return nroCalles;
	}

	public void setNroCalles(Double nroCalles) {
		this.nroCalles = nroCalles;
	}

	public Long getDistSiembraId() {
		return this.distSiembraId;
	}

	public void setDistSiembraId(Long distSiembraId) {
		this.distSiembraId = distSiembraId;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Long getCompania() {
		return this.compania;
	}

	public void setCompania(Long compania) {
		this.compania = compania;
	}

	public String getInfoAdicional() {
		return this.infoAdicional;
	}

	public void setInfoAdicional(String infoAdicional) {
		this.infoAdicional = infoAdicional;
	}

	public String getInfoAdicional2() {
		return this.infoAdicional2;
	}

	public void setInfoAdicional2(String infoAdicional2) {
		this.infoAdicional2 = infoAdicional2;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Double getDistanciaSiembra() {
		return this.distanciaSiembra;
	}

	public void setDistanciaSiembra(Double distanciaSiembra) {
		this.distanciaSiembra = distanciaSiembra;
	}

	public Cultivo getCultivo() {
		return cultivo;
	}

	public void setCultivo(Cultivo cultivo) {
		this.cultivo = cultivo;
	}

}
