package co.com.arcosoft.modelo;
// Generated 5/04/2019 11:07:05 AM by Hibernate Tools 4.0.0



/**
 * EquipoImplemento generated by hbm2java
 */
public class EquipoImplemento  implements java.io.Serializable {


     private Long equipoImplementoId;
     private Equipo equipo;
     private Long implementoId;

    public EquipoImplemento() {
    }

    public EquipoImplemento(Equipo equipo, Long implementoId) {
       this.equipo = equipo;
       this.implementoId = implementoId;
    }
   
    public Long getEquipoImplementoId() {
        return this.equipoImplementoId;
    }
    
    public void setEquipoImplementoId(Long equipoImplementoId) {
        this.equipoImplementoId = equipoImplementoId;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public Long getImplementoId() {
        return this.implementoId;
    }
    
    public void setImplementoId(Long implementoId) {
        this.implementoId = implementoId;
    }




}


