package co.com.arcosoft.modelo;
// Generated 17-nov-2016 19:51:06 by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * EquipoEvento generated by hbm2java
 */
public class EquipoEvento  implements java.io.Serializable {


    private Long id;
    private Equipo equipo;
    private Eventos eventos;
    private Date fechaInicial;
    private Date fechaFinal;
    private Date fechaCreacion;
    private Date fechaModificacion;
    private Long diasNotificacion;
    private String observacion;
    private String registraPago;
    private Long persEmprId;
    private Double valorEvento;
    private Date fechaPago;

   public EquipoEvento() {
   }

	
   public EquipoEvento(Equipo equipo, Eventos eventos) {
       this.equipo = equipo;
       this.eventos = eventos;
   }
   public EquipoEvento(Equipo equipo, Eventos eventos, Date fechaInicial, Date fechaFinal, Date fechaCreacion, Date fechaModificacion,  Long diasNotificacion, String observacion, String registraPago, Long persEmprId, Double valorEvento, Date fechaPago) {
      this.equipo = equipo;
      this.eventos = eventos;
      this.fechaInicial = fechaInicial;
      this.fechaFinal = fechaFinal;
      this.fechaCreacion = fechaCreacion;
      this.fechaModificacion = fechaModificacion;
      this.diasNotificacion = diasNotificacion;
      this.observacion = observacion;
      this.registraPago = registraPago;
      this.persEmprId = persEmprId;
      this.valorEvento = valorEvento;
      this.fechaPago = fechaPago;
   }
  
   public Long getId() {
       return this.id;
   }
   
   public void setId(Long id) {
       this.id = id;
   }
   public Equipo getEquipo() {
       return this.equipo;
   }
   
   public void setEquipo(Equipo equipo) {
       this.equipo = equipo;
   }
   public Eventos getEventos() {
       return this.eventos;
   }
   
   public void setEventos(Eventos eventos) {
       this.eventos = eventos;
   }
   public Date getFechaInicial() {
       return this.fechaInicial;
   }
   
   public void setFechaInicial(Date fechaInicial) {
       this.fechaInicial = fechaInicial;
   }
   public Date getFechaFinal() {
       return this.fechaFinal;
   }
   
   public void setFechaFinal(Date fechaFinal) {
       this.fechaFinal = fechaFinal;
   }
   public Date getFechaCreacion() {
       return this.fechaCreacion;
   }
   
   public void setFechaCreacion(Date fechaCreacion) {
       this.fechaCreacion = fechaCreacion;
   }
   public Date getFechaModificacion() {
       return this.fechaModificacion;
   }
   
   public void setFechaModificacion(Date fechaModificacion) {
       this.fechaModificacion = fechaModificacion;
   }
   
   public Long getDiasNotificacion() {
       return this.diasNotificacion;
   }
   
   public void setDiasNotificacion(Long diasNotificacion) {
       this.diasNotificacion = diasNotificacion;
   }
   public String getObservacion() {
       return this.observacion;
   }
   
   public void setObservacion(String observacion) {
       this.observacion = observacion;
   }
   public String getRegistraPago() {
       return this.registraPago;
   }
   
   public void setRegistraPago(String registraPago) {
       this.registraPago = registraPago;
   }
   public Long getPersEmprId() {
       return this.persEmprId;
   }
   
   public void setPersEmprId(Long persEmprId) {
       this.persEmprId = persEmprId;
   }
   public Double getValorEvento() {
       return this.valorEvento;
   }
   
   public void setValorEvento(Double valorEvento) {
       this.valorEvento = valorEvento;
   }
   public Date getFechaPago() {
       return this.fechaPago;
   }
   
   public void setFechaPago(Date fechaPago) {
       this.fechaPago = fechaPago;
   }




}


