package co.com.arcosoft.modelo;
// Generated 28-oct-2016 10:34:32 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Eventos generated by hbm2java
 */
public class Eventos  implements java.io.Serializable {


     private Long eventosId;
     private ElementoCosto elementoCosto;
     private String codigo;
     private String nombre;
     private String infoAdicional;
     private String infoAdicional2;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private String estado;
     private Long compania;
     private Set<EquipoEvento> equipoEventos = new HashSet<EquipoEvento>(0);

    public Eventos() {
    }

	
    public Eventos(Long eventosId) {
        this.eventosId = eventosId;
    }
    public Eventos(Long eventosId, ElementoCosto elementoCosto, String codigo, String nombre, String infoAdicional, String infoAdicional2, Date fechaCreacion, Date fechaModificacion, String estado, Long compania,Set<EquipoEvento> equipoEventos) {
       this.eventosId = eventosId;
       this.elementoCosto = elementoCosto;
       this.codigo = codigo;
       this.nombre = nombre;
       this.infoAdicional = infoAdicional;
       this.infoAdicional2 = infoAdicional2;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estado = estado;
       this.compania = compania;
       this.equipoEventos = equipoEventos;
       
    }
   
    public Long getEventosId() {
        return this.eventosId;
    }
    
    public void setEventosId(Long eventosId) {
        this.eventosId = eventosId;
    }
    public ElementoCosto getElementoCosto() {
        return this.elementoCosto;
    }
    
    public void setElementoCosto(ElementoCosto elementoCosto) {
        this.elementoCosto = elementoCosto;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getInfoAdicional() {
        return this.infoAdicional;
    }
    
    public void setInfoAdicional(String infoAdicional) {
        this.infoAdicional = infoAdicional;
    }
    public String getInfoAdicional2() {
        return this.infoAdicional2;
    }
    
    public void setInfoAdicional2(String infoAdicional2) {
        this.infoAdicional2 = infoAdicional2;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Long getCompania() {
        return this.compania;
    }
    
    public void setCompania(Long compania) {
        this.compania = compania;
    }


	public Set<EquipoEvento> getEquipoEventos() {
		return equipoEventos;
	}


	public void setEquipoEventos(Set<EquipoEvento> equipoEventos) {
		this.equipoEventos = equipoEventos;
	}




}


