package co.com.arcosoft.modelo;
// Generated 23-jul-2017 14:00:29 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Fitosanidad generated by hbm2java
 */
public class Fitosanidad  implements java.io.Serializable {


     private Long fitosanidadId;
     private String codigo;
     private String nombre;
     private String nombreCientifico;
     private String claseFitosanidad;
     private String tipoFitosanidad;
     private String infoAdicional;
     private String infoAdicional2;
     private String estado;
     private Long compania;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private String observacion;
     private String foto;
     private Set<CultivoFitosanidad> cultivoFitosanidads = new HashSet<CultivoFitosanidad>(0);
     private String controlInsectos;

    public Fitosanidad() {
    }

    public Fitosanidad(String codigo, String nombre, String nombreCientifico, String claseFitosanidad, String tipoFitosanidad, String infoAdicional, String infoAdicional2, String estado, Long compania, Date fechaCreacion, Date fechaModificacion, String observacion, String foto, Set<CultivoFitosanidad> cultivoFitosanidads,
    		String controlInsectos) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.nombreCientifico = nombreCientifico;
       this.claseFitosanidad = claseFitosanidad;
       this.tipoFitosanidad = tipoFitosanidad;
       this.infoAdicional = infoAdicional;
       this.infoAdicional2 = infoAdicional2;
       this.estado = estado;
       this.compania = compania;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.observacion = observacion;
       this.foto = foto;
       this.cultivoFitosanidads = cultivoFitosanidads;
       this.controlInsectos = controlInsectos;
    }
   
    /**
	 * @return the controlInsectos
	 */
	public String getControlInsectos() {
		return controlInsectos;
	}

	/**
	 * @param controlInsectos the controlInsectos to set
	 */
	public void setControlInsectos(String controlInsectos) {
		this.controlInsectos = controlInsectos;
	}

	public Long getFitosanidadId() {
        return this.fitosanidadId;
    }
    
    public void setFitosanidadId(Long fitosanidadId) {
        this.fitosanidadId = fitosanidadId;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNombreCientifico() {
        return this.nombreCientifico;
    }
    
    public void setNombreCientifico(String nombreCientifico) {
        this.nombreCientifico = nombreCientifico;
    }
    public String getClaseFitosanidad() {
        return this.claseFitosanidad;
    }
    
    public void setClaseFitosanidad(String claseFitosanidad) {
        this.claseFitosanidad = claseFitosanidad;
    }
    public String getTipoFitosanidad() {
        return this.tipoFitosanidad;
    }
    
    public void setTipoFitosanidad(String tipoFitosanidad) {
        this.tipoFitosanidad = tipoFitosanidad;
    }
    public String getInfoAdicional() {
        return this.infoAdicional;
    }
    
    public void setInfoAdicional(String infoAdicional) {
        this.infoAdicional = infoAdicional;
    }
    public String getInfoAdicional2() {
        return this.infoAdicional2;
    }
    
    public void setInfoAdicional2(String infoAdicional2) {
        this.infoAdicional2 = infoAdicional2;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Long getCompania() {
        return this.compania;
    }
    
    public void setCompania(Long compania) {
        this.compania = compania;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public Set<CultivoFitosanidad> getCultivoFitosanidads() {
        return this.cultivoFitosanidads;
    }
    
    public void setCultivoFitosanidads(Set<CultivoFitosanidad> cultivoFitosanidads) {
        this.cultivoFitosanidads = cultivoFitosanidads;
    }




}


