package co.com.arcosoft.modelo;
// Generated 20-abr-2016 14:39:50 by Hibernate Tools 4.0.0

/**
 * GroupAuthorities generated by hbm2java
 */
public class GroupAuthorities implements java.io.Serializable {

	private Long id;
	private Groups groups;
	private String authority;

	public GroupAuthorities() {
	}

	public GroupAuthorities(Long id, Groups groups, String authority) {
		this.id = id;
		this.groups = groups;
		this.authority = authority;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

	public String getAuthority() {
		return this.authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

}
