package co.com.arcosoft.modelo;

// Generated 08-sep-2015 22:35:03 by Hibernate Tools 4.0.0

/**
 * GrpLaborTenCencos generated by hbm2java
 */
public class GrpLaborTenCencos implements java.io.Serializable {

	private GrpLaborTenCencosId id;
	private Tenencia tenencia;
	private GrpLabor grpLabor;
	private CentCost centCost;

	public GrpLaborTenCencos() {
	}

	public GrpLaborTenCencos(GrpLaborTenCencosId id, GrpLabor grpLabor) {
		this.id = id;
		this.grpLabor = grpLabor;
	}

	public GrpLaborTenCencos(GrpLaborTenCencosId id, Tenencia tenencia, GrpLabor grpLabor, CentCost centCost) {
		this.id = id;
		this.tenencia = tenencia;
		this.grpLabor = grpLabor;
		this.centCost = centCost;
	}

	public GrpLaborTenCencosId getId() {
		return this.id;
	}

	public void setId(GrpLaborTenCencosId id) {
		this.id = id;
	}

	public Tenencia getTenencia() {
		return this.tenencia;
	}

	public void setTenencia(Tenencia tenencia) {
		this.tenencia = tenencia;
	}

	public GrpLabor getGrpLabor() {
		return this.grpLabor;
	}

	public void setGrpLabor(GrpLabor grpLabor) {
		this.grpLabor = grpLabor;
	}

	public CentCost getCentCost() {
		return this.centCost;
	}

	public void setCentCost(CentCost centCost) {
		this.centCost = centCost;
	}

}
