package co.com.arcosoft.modelo;

// Generated 08-sep-2015 22:35:03 by Hibernate Tools 4.0.0

/**
 * IngrActivProdId generated by hbm2java
 */
public class IngrActivProdId implements java.io.Serializable {

	private Long productoId;
	private Long ingredienteActId;
	public Long compania;
	private Double ptjeContribuccion;

	public IngrActivProdId() {
	}

	public IngrActivProdId(Long productoId, Long ingredienteActId, Long compania, Double ptjeContribuccion) {
		this.productoId = productoId;
		this.ingredienteActId = ingredienteActId;
		this.compania = compania;
		this.ptjeContribuccion = ptjeContribuccion;
	}

	public Long getProductoId() {
		return this.productoId;
	}

	public void setProductoId(Long productoId) {
		this.productoId = productoId;
	}

	public Long getIngredienteActId() {
		return this.ingredienteActId;
	}

	public void setIngredienteActId(Long ingredienteActId) {
		this.ingredienteActId = ingredienteActId;
	}

	public Long getCompania() {
		return this.compania;
	}

	public void setCompania(Long compania) {
		this.compania = compania;
	}

	public Double getPtjeContribuccion() {
		return this.ptjeContribuccion;
	}

	public void setPtjeContribuccion(Double ptjeContribuccion) {
		this.ptjeContribuccion = ptjeContribuccion;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IngrActivProdId))
			return false;
		IngrActivProdId castOther = (IngrActivProdId) other;

		return ((this.getProductoId() == castOther.getProductoId()) || (this.getProductoId() != null
				&& castOther.getProductoId() != null && this.getProductoId().equals(castOther.getProductoId())))
				&& ((this.getIngredienteActId() == castOther.getIngredienteActId())
						|| (this.getIngredienteActId() != null && castOther.getIngredienteActId() != null
								&& this.getIngredienteActId().equals(castOther.getIngredienteActId())))
				&& ((this.getCompania() == castOther.getCompania()) || (this.getCompania() != null
						&& castOther.getCompania() != null && this.getCompania().equals(castOther.getCompania())))
				&& ((this.getPtjeContribuccion() == castOther.getPtjeContribuccion())
						|| (this.getPtjeContribuccion() != null && castOther.getPtjeContribuccion() != null
								&& this.getPtjeContribuccion().equals(castOther.getPtjeContribuccion())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProductoId() == null ? 0 : this.getProductoId().hashCode());
		result = 37 * result + (getIngredienteActId() == null ? 0 : this.getIngredienteActId().hashCode());
		result = 37 * result + (getCompania() == null ? 0 : this.getCompania().hashCode());
		result = 37 * result + (getPtjeContribuccion() == null ? 0 : this.getPtjeContribuccion().hashCode());
		return result;
	}

}
