package co.com.arcosoft.modelo;
// Generated 08-ago-2016 17:52:47 by Hibernate Tools 4.0.0

/**
 * ItemsMenu generated by hbm2java
 */
public class ItemsMenu implements java.io.Serializable {

	private Long id;
	private String estado;
	private String nombreModulo;
	private String nombreItem;
	private String url;
	private String descripcion;
	private String nombreTabla;

	public ItemsMenu() {
	}

	public ItemsMenu(Long id) {
		this.id = id;
	}

	public ItemsMenu(Long id, String estado, String nombreModulo, String nombreItem, String url, String descripcion,
			String nombreTabla) {
		this.id = id;
		this.estado = estado;
		this.nombreModulo = nombreModulo;
		this.nombreItem = nombreItem;
		this.url = url;
		this.descripcion = descripcion;
		this.nombreTabla = nombreTabla;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getNombreModulo() {
		return this.nombreModulo;
	}

	public void setNombreModulo(String nombreModulo) {
		this.nombreModulo = nombreModulo;
	}

	public String getNombreItem() {
		return this.nombreItem;
	}

	public void setNombreItem(String nombreItem) {
		this.nombreItem = nombreItem;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getNombreTabla() {
		return this.nombreTabla;
	}

	public void setNombreTabla(String nombreTabla) {
		this.nombreTabla = nombreTabla;
	}

}
