package co.com.arcosoft.modelo;

// Generated 08-sep-2015 22:35:03 by Hibernate Tools 4.0.0

/**
 * LaborAsociada generated by hbm2java
 */
public class LaborAsociada implements java.io.Serializable {

	private LaborAsociadaId id;
	private Labor laborByLaborAsocId;
	private Labor laborByLaborId;

	public LaborAsociada() {
	}

	public LaborAsociada(LaborAsociadaId id) {
		this.id = id;
	}

	public LaborAsociada(LaborAsociadaId id, Labor laborByLaborAsocId, Labor laborByLaborId) {
		this.id = id;
		this.laborByLaborAsocId = laborByLaborAsocId;
		this.laborByLaborId = laborByLaborId;
	}

	public LaborAsociadaId getId() {
		return this.id;
	}

	public void setId(LaborAsociadaId id) {
		this.id = id;
	}

	public Labor getLaborByLaborAsocId() {
		return this.laborByLaborAsocId;
	}

	public void setLaborByLaborAsocId(Labor laborByLaborAsocId) {
		this.laborByLaborAsocId = laborByLaborAsocId;
	}

	public Labor getLaborByLaborId() {
		return this.laborByLaborId;
	}

	public void setLaborByLaborId(Labor laborByLaborId) {
		this.laborByLaborId = laborByLaborId;
	}

}
