package co.com.arcosoft.modelo;
// Generated 30-jul-2018 16:05:58 by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * LaborAdicionalMo generated by hbm2java
 */
public class LaborAdicionalMo  implements java.io.Serializable {


     private Long laborAdicionalMoId;
     private UdadMed udadMed;
     private Labor labor;
     private Date fechaInicial;
     private Date fechaFinal;
     private Double cantidadAdicionalMo;
     private Double tarifaAdicionalMo;

    public LaborAdicionalMo() {
    }

	
    public LaborAdicionalMo(Long laborAdicionalMoId) {
        this.laborAdicionalMoId = laborAdicionalMoId;
    }
    public LaborAdicionalMo(Long laborAdicionalMoId, UdadMed udadMed, Labor labor, Date fechaInicial, Date fechaFinal, Double cantidadAdicionalMo, Double tarifaAdicionalMo) {
       this.laborAdicionalMoId = laborAdicionalMoId;
       this.udadMed = udadMed;
       this.labor = labor;
       this.fechaInicial = fechaInicial;
       this.fechaFinal = fechaFinal;
       this.cantidadAdicionalMo = cantidadAdicionalMo;
       this.tarifaAdicionalMo = tarifaAdicionalMo;
    }
   
    public Long getLaborAdicionalMoId() {
        return this.laborAdicionalMoId;
    }
    
    public void setLaborAdicionalMoId(Long laborAdicionalMoId) {
        this.laborAdicionalMoId = laborAdicionalMoId;
    }
    public UdadMed getUdadMed() {
        return this.udadMed;
    }
    
    public void setUdadMed(UdadMed udadMed) {
        this.udadMed = udadMed;
    }
    public Labor getLabor() {
        return this.labor;
    }
    
    public void setLabor(Labor labor) {
        this.labor = labor;
    }
    public Date getFechaInicial() {
        return this.fechaInicial;
    }
    
    public void setFechaInicial(Date fechaInicial) {
        this.fechaInicial = fechaInicial;
    }
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }
    public Double getCantidadAdicionalMo() {
        return this.cantidadAdicionalMo;
    }
    
    public void setCantidadAdicionalMo(Double cantidadAdicionalMo) {
        this.cantidadAdicionalMo = cantidadAdicionalMo;
    }
    public Double getTarifaAdicionalMo() {
        return this.tarifaAdicionalMo;
    }
    
    public void setTarifaAdicionalMo(Double tarifaAdicionalMo) {
        this.tarifaAdicionalMo = tarifaAdicionalMo;
    }




}


