package co.com.arcosoft.modelo;

// Generated 08-sep-2015 22:35:03 by Hibernate Tools 4.0.0

/**
 * LaborCcontableId generated by hbm2java
 */
public class LaborCcontableId implements java.io.Serializable {

	private Long laborId;
	private Long ccontableId;

	public LaborCcontableId() {
	}

	public LaborCcontableId(Long laborId, Long ccontableId) {
		this.laborId = laborId;
		this.ccontableId = ccontableId;
	}

	public Long getLaborId() {
		return this.laborId;
	}

	public void setLaborId(Long laborId) {
		this.laborId = laborId;
	}

	public Long getCcontableId() {
		return this.ccontableId;
	}

	public void setCcontableId(Long ccontableId) {
		this.ccontableId = ccontableId;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LaborCcontableId))
			return false;
		LaborCcontableId castOther = (LaborCcontableId) other;

		return ((this.getLaborId() == castOther.getLaborId()) || (this.getLaborId() != null
				&& castOther.getLaborId() != null && this.getLaborId().equals(castOther.getLaborId())))
				&& ((this.getCcontableId() == castOther.getCcontableId())
						|| (this.getCcontableId() != null && castOther.getCcontableId() != null
								&& this.getCcontableId().equals(castOther.getCcontableId())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLaborId() == null ? 0 : this.getLaborId().hashCode());
		result = 37 * result + (getCcontableId() == null ? 0 : this.getCcontableId().hashCode());
		return result;
	}

}
