package co.com.arcosoft.modelo;

// Generated 08-sep-2015 22:35:03 by Hibernate Tools 4.0.0

/**
 * LaborServicioId generated by hbm2java
 */
public class LaborServicioId implements java.io.Serializable {

	private Long laborId;
	private Long servicioId;

	public LaborServicioId() {
	}

	public LaborServicioId(Long laborId, Long servicioId) {
		this.laborId = laborId;
		this.servicioId = servicioId;
	}

	public Long getLaborId() {
		return this.laborId;
	}

	public void setLaborId(Long laborId) {
		this.laborId = laborId;
	}

	public Long getServicioId() {
		return this.servicioId;
	}

	public void setServicioId(Long servicioId) {
		this.servicioId = servicioId;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LaborServicioId))
			return false;
		LaborServicioId castOther = (LaborServicioId) other;

		return ((this.getLaborId() == castOther.getLaborId()) || (this.getLaborId() != null
				&& castOther.getLaborId() != null && this.getLaborId().equals(castOther.getLaborId())))
				&& ((this.getServicioId() == castOther.getServicioId())
						|| (this.getServicioId() != null && castOther.getServicioId() != null
								&& this.getServicioId().equals(castOther.getServicioId())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLaborId() == null ? 0 : this.getLaborId().hashCode());
		result = 37 * result + (getServicioId() == null ? 0 : this.getServicioId().hashCode());
		return result;
	}

}
