package co.com.arcosoft.modelo;

// Generated 08-sep-2015 22:35:03 by Hibernate Tools 4.0.0

/**
 * LimiteCeptoNomina generated by hbm2java
 */
public class LimiteCeptoNomina implements java.io.Serializable {

	private LimiteCeptoNominaId id;
	private UdadMed udadMed;
	private ConceptoNomina conceptoNomina;

	public LimiteCeptoNomina() {
	}

	public LimiteCeptoNomina(LimiteCeptoNominaId id) {
		this.id = id;
	}

	public LimiteCeptoNomina(LimiteCeptoNominaId id, UdadMed udadMed, ConceptoNomina conceptoNomina) {
		this.id = id;
		this.udadMed = udadMed;
		this.conceptoNomina = conceptoNomina;
	}

	public LimiteCeptoNominaId getId() {
		return this.id;
	}

	public void setId(LimiteCeptoNominaId id) {
		this.id = id;
	}

	public UdadMed getUdadMed() {
		return this.udadMed;
	}

	public void setUdadMed(UdadMed udadMed) {
		this.udadMed = udadMed;
	}

	public ConceptoNomina getConceptoNomina() {
		return this.conceptoNomina;
	}

	public void setConceptoNomina(ConceptoNomina conceptoNomina) {
		this.conceptoNomina = conceptoNomina;
	}

}
