package co.com.arcosoft.modelo;
// Generated 26/04/2019 10:08:48 AM by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * LogDatServRealizadosEquipo generated by hbm2java
 */
public class LogDatServRealizadosEquipo  implements java.io.Serializable {


     private Long logDatServRealizadosEquipoId;
     private Long datServRealizadosEquipoId;
     private Long consecutivo;
     private Long compania;
     private Long usuarioModificacion;
     private String observacion;
     private Date fecha;
     private Equipo equipoId;
     
     
    public LogDatServRealizadosEquipo() {
    }

    public LogDatServRealizadosEquipo(Long datServRealizadosEquipoId, Long consecutivo, Long compania, Long usuarioModificacion, 
    		String observacion, Date fecha, Equipo equipoId) {
       this.datServRealizadosEquipoId = datServRealizadosEquipoId;
       this.consecutivo = consecutivo;
       this.compania = compania;
       this.usuarioModificacion = usuarioModificacion;
       this.observacion = observacion;
       this.fecha = fecha;
       this.equipoId=equipoId;
    }
   
    
    
    public Equipo getEquipoId() {
		return equipoId;
	}

	public void setEquipoId(Equipo equipoId) {
		this.equipoId = equipoId;
	}

	public Long getLogDatServRealizadosEquipoId() {
        return this.logDatServRealizadosEquipoId;
    }
    
    public void setLogDatServRealizadosEquipoId(Long logDatServRealizadosEquipoId) {
        this.logDatServRealizadosEquipoId = logDatServRealizadosEquipoId;
    }
    public Long getDatServRealizadosEquipoId() {
        return this.datServRealizadosEquipoId;
    }
    
    public void setDatServRealizadosEquipoId(Long datServRealizadosEquipoId) {
        this.datServRealizadosEquipoId = datServRealizadosEquipoId;
    }
    public Long getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Long consecutivo) {
        this.consecutivo = consecutivo;
    }
    public Long getCompania() {
        return this.compania;
    }
    
    public void setCompania(Long compania) {
        this.compania = compania;
    }
    public Long getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(Long usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


