package co.com.arcosoft.modelo;
// Generated 30-jul-2018 10:42:52 by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * Nivel2Clientesmq generated by hbm2java
 */
public class Nivel2Clientesmq  implements java.io.Serializable {


     private Long nivel2ClientesmqId;
     private Ciudad ciudad;
     private CentCost centCost;
     private PersEmpr persEmpr;
     private String codigo;
     private Long compania;
     private String nombre;
     private String tipoPropiedad;
     private String observacion;
     private String direccion;
     private String barrio;
     private String telefono;
     private String pbx;
     private Double distanciaPlanta;
     private Double distanciaOficina;
     private Float latitud;
     private Float longitud;
     private Float precision1;
     private String infoAdicional;
     private String infoAdicional2;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private String estado;
     private Long vereda;
     private String codigoAlternativo;

    public Nivel2Clientesmq() {
    }

    public Nivel2Clientesmq(Ciudad ciudad, CentCost centCost, PersEmpr persEmpr, String codigo, 
    		Long compania, String nombre, String tipoPropiedad, String observacion, String direccion,
    		String barrio, String telefono, String pbx, Double distanciaPlanta, Double distanciaOficina, 
    		Float latitud, Float longitud, Float precision1, String infoAdicional, String infoAdicional2, Date fechaCreacion, Date fechaModificacion, String estado, Long vereda, String codigoAlternativo) {
       this.ciudad = ciudad;
       this.centCost = centCost;
       this.persEmpr = persEmpr;
       this.codigo = codigo;
       this.compania = compania;
       this.nombre = nombre;
       this.tipoPropiedad = tipoPropiedad;
       this.observacion = observacion;
       this.direccion = direccion;
       this.barrio = barrio;
       this.telefono = telefono;
       this.pbx = pbx;
       this.distanciaPlanta = distanciaPlanta;
       this.distanciaOficina = distanciaOficina;
       this.latitud = latitud;
       this.longitud = longitud;
       this.precision1 = precision1;
       this.infoAdicional = infoAdicional;
       this.infoAdicional2 = infoAdicional2;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estado = estado;
       this.vereda = vereda;
       this.codigoAlternativo = codigoAlternativo;
    }
   
    public Long getNivel2ClientesmqId() {
        return this.nivel2ClientesmqId;
    }
    
    public void setNivel2ClientesmqId(Long nivel2ClientesmqId) {
        this.nivel2ClientesmqId = nivel2ClientesmqId;
    }
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    public CentCost getCentCost() {
        return this.centCost;
    }
    
    public void setCentCost(CentCost centCost) {
        this.centCost = centCost;
    }
    public PersEmpr getPersEmpr() {
        return this.persEmpr;
    }
    
    public void setPersEmpr(PersEmpr persEmpr) {
        this.persEmpr = persEmpr;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Long getCompania() {
        return this.compania;
    }
    
    public void setCompania(Long compania) {
        this.compania = compania;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipoPropiedad() {
        return this.tipoPropiedad;
    }
    
    public void setTipoPropiedad(String tipoPropiedad) {
        this.tipoPropiedad = tipoPropiedad;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getBarrio() {
        return this.barrio;
    }
    
    public void setBarrio(String barrio) {
        this.barrio = barrio;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getPbx() {
        return this.pbx;
    }
    
    public void setPbx(String pbx) {
        this.pbx = pbx;
    }
    public Double getDistanciaPlanta() {
        return this.distanciaPlanta;
    }
    
    public void setDistanciaPlanta(Double distanciaPlanta) {
        this.distanciaPlanta = distanciaPlanta;
    }
    public Double getDistanciaOficina() {
        return this.distanciaOficina;
    }
    
    public void setDistanciaOficina(Double distanciaOficina) {
        this.distanciaOficina = distanciaOficina;
    }
    public Float getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Float latitud) {
        this.latitud = latitud;
    }
    public Float getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Float longitud) {
        this.longitud = longitud;
    }
    public Float getPrecision1() {
        return this.precision1;
    }
    
    public void setPrecision1(Float precision1) {
        this.precision1 = precision1;
    }
    public String getInfoAdicional() {
        return this.infoAdicional;
    }
    
    public void setInfoAdicional(String infoAdicional) {
        this.infoAdicional = infoAdicional;
    }
    public String getInfoAdicional2() {
        return this.infoAdicional2;
    }
    
    public void setInfoAdicional2(String infoAdicional2) {
        this.infoAdicional2 = infoAdicional2;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Long getVereda() {
        return this.vereda;
    }
    
    public void setVereda(Long vereda) {
        this.vereda = vereda;
    }
    public String getCodigoAlternativo() {
        return this.codigoAlternativo;
    }
    
    public void setCodigoAlternativo(String codigoAlternativo) {
        this.codigoAlternativo = codigoAlternativo;
    }




}


