package co.com.arcosoft.modelo;

// Generated 15-sep-2015 10:09:32 by Hibernate Tools 4.0.0

/**
 * PlanAsignarRecurso generated by hbm2java
 */
public class PlanAsignarRecurso implements java.io.Serializable {

	private PlanAsignarRecursoId id;
	private DatPlanLabor datPlanLabor;
	private Recurso recurso;
	private UdadMed udadMed;
	private TipoRecurso tipoRecurso;

	public PlanAsignarRecurso() {
	}

	public PlanAsignarRecurso(PlanAsignarRecursoId id) {
		this.id = id;
	}

	public PlanAsignarRecurso(PlanAsignarRecursoId id, DatPlanLabor datPlanLabor, Recurso recurso, UdadMed udadMed,
			TipoRecurso tipoRecurso) {
		this.id = id;
		this.datPlanLabor = datPlanLabor;
		this.recurso = recurso;
		this.udadMed = udadMed;
		this.tipoRecurso = tipoRecurso;
	}

	public PlanAsignarRecursoId getId() {
		return this.id;
	}

	public void setId(PlanAsignarRecursoId id) {
		this.id = id;
	}

	public DatPlanLabor getDatPlanLabor() {
		return this.datPlanLabor;
	}

	public void setDatPlanLabor(DatPlanLabor datPlanLabor) {
		this.datPlanLabor = datPlanLabor;
	}

	public Recurso getRecurso() {
		return this.recurso;
	}

	public void setRecurso(Recurso recurso) {
		this.recurso = recurso;
	}

	public UdadMed getUdadMed() {
		return this.udadMed;
	}

	public void setUdadMed(UdadMed udadMed) {
		this.udadMed = udadMed;
	}

	public TipoRecurso getTipoRecurso() {
		return this.tipoRecurso;
	}

	public void setTipoRecurso(TipoRecurso tipoRecurso) {
		this.tipoRecurso = tipoRecurso;
	}

}
