package co.com.arcosoft.modelo;
// Generated 19-oct-2018 11:57:40 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * PrecioPromProd generated by hbm2java
 */
public class PrecioPromProd implements java.io.Serializable {
	private Long precioProdId;
	private Producto producto;
	private PersEmpr persEmpr;
	private Almacen almacenId;
	private Long compania;
	private Double valorUnitario;
	private String infoAdicional;
	private String infoAdicional2;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private Date fechaInicial;
	private Date fechaFinal;
	private Date fechaVencimiento;
	private UdadMed unidadMedida;
	private Double cantidadCompra;
	private String loteCompraProducto;
	private String registroIca;
	private Long consecutivo;
	private ConceptoKardex conceptoKardexId;
	private String tipoMovimiento;
	private Long numFacturaCompra;
	private Double costoTotal;
	private Equipo equipoId;
	private Double porcIva;
	private Double valorIva;
	private Trabajador trabajador;
	private Nivel2 nivel2Id;
	private Nivel4 nivel4Id;
	private DatCompraProductos datCompraProductosId;
	private DatOtrosMovInventario datOtrosMovInventarioId;
	private DatServRealizadosEquipo datServRealizadosEquipoId;
	private Long conceptoGastoId;
	private String diferido;
	private String transportadoraFactura;
	private String transportadora_nguia;
	private Double transportadora_valor_flete;
	private String origenDatos;
	private Long etapaId;
	private Long variedId;

	private Trabajador operario_equipo_id;
	private Nivel2Clientesmq nivel2_clientesmq_id;
	private Long nivel4_clientesmq_id;
	private Double horometro_abastecimiento;
	private Long usuarioDigitacion;
	private Long indicador_vuelta_medidor;

	private UbicacionesAlmacen ubicacionesAlmacen;
	private Equipo implementoId;
	private Long datMantenimientoEquipoId;
	private Long centCostId;
	private String referenciaFacCompra;
	private Double descuentoProducto;
	public PrecioPromProd() {

	}

	public PrecioPromProd(Double descuentoProducto, Producto producto, PersEmpr persEmpr, Almacen almacenId, Long compania, Double valorUnitario,
			String infoAdicional, String infoAdicional2, Date fechaCreacion, Date fechaModificacion, Date fechaInicial,
			Date fechaFinal, Date fechaVencimiento, UdadMed unidadMedida, Double cantidadCompra,
			String loteCompraProducto, String registroIca, Long consecutivo, ConceptoKardex conceptoKardexId,
			String tipoMovimiento, Long numFacturaCompra, Double costoTotal, Equipo equipoId,
			DatCompraProductos datCompraProductosId, Double porcIva, Double valorIva, Trabajador trabajador,
			DatOtrosMovInventario datOtrosMovInventarioId, DatServRealizadosEquipo datServRealizadosEquipoId,
			Long conceptoGastoId, String diferido, String transportadoraFactura, String transportadora_nguia,
			Double transportadora_valor_flete, Nivel2 nivel2Id, Nivel4 nivel4Id, String origenDatos, Long etapaId,
			Long variedId, Trabajador operario_equipo_id, Nivel2Clientesmq nivel2_clientesmq_id,
			Long nivel4_clientesmq_id, Double horometro_abastecimiento, Long usuarioDigitacion,
			Long indicador_vuelta_medidor, UbicacionesAlmacen ubicacionesAlmacen, Equipo implementoId,
			Long datMantenimientoEquipoId, Long centCostId, String referenciaFacCompra) {
		this.referenciaFacCompra = referenciaFacCompra;
		this.producto = producto;
		this.persEmpr = persEmpr;
		this.almacenId = almacenId;
		this.compania = compania;
		this.valorUnitario = valorUnitario;
		this.infoAdicional = infoAdicional;
		this.infoAdicional2 = infoAdicional2;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.fechaInicial = fechaInicial;
		this.fechaFinal = fechaFinal;
		this.fechaVencimiento = fechaVencimiento;
		this.unidadMedida = unidadMedida;
		this.cantidadCompra = cantidadCompra;
		this.loteCompraProducto = loteCompraProducto;
		this.registroIca = registroIca;
		this.consecutivo = consecutivo;
		this.conceptoKardexId = conceptoKardexId;
		this.tipoMovimiento = tipoMovimiento;
		this.numFacturaCompra = numFacturaCompra;
		this.costoTotal = costoTotal;
		this.equipoId = equipoId;
		this.datCompraProductosId = datCompraProductosId;
		this.trabajador = trabajador;
		this.porcIva = porcIva;
		this.valorIva = valorIva;
		this.datOtrosMovInventarioId = datOtrosMovInventarioId;
		this.datServRealizadosEquipoId = datServRealizadosEquipoId;
		this.conceptoGastoId = conceptoGastoId;
		this.diferido = diferido;
		this.transportadoraFactura = transportadoraFactura;
		this.transportadora_nguia = transportadora_nguia;
		this.transportadora_valor_flete = transportadora_valor_flete;
		this.nivel2Id = nivel2Id;
		this.nivel4Id = nivel4Id;
		this.origenDatos = origenDatos;
		this.etapaId = etapaId;
		this.variedId = variedId;
		this.operario_equipo_id = operario_equipo_id;
		this.nivel2_clientesmq_id = nivel2_clientesmq_id;
		this.nivel4_clientesmq_id = nivel4_clientesmq_id;
		this.horometro_abastecimiento = horometro_abastecimiento;
		this.usuarioDigitacion = usuarioDigitacion;
		this.indicador_vuelta_medidor = indicador_vuelta_medidor;
		this.ubicacionesAlmacen = ubicacionesAlmacen;
		this.implementoId = implementoId;
		this.datMantenimientoEquipoId = datMantenimientoEquipoId;
		this.centCostId = centCostId;
		this.descuentoProducto=descuentoProducto;
	}

	public Double getDescuentoProducto() {
		return descuentoProducto;
	}

	public void setDescuentoProducto(Double descuentoProducto) {
		this.descuentoProducto = descuentoProducto;
	}

	public String getReferenciaFacCompra() {
		return referenciaFacCompra;
	}

	public void setReferenciaFacCompra(String referenciaFacCompra) {
		this.referenciaFacCompra = referenciaFacCompra;
	}

	public Long getCentCostId() {
		return centCostId;
	}

	public void setCentCostId(Long centCostId) {
		this.centCostId = centCostId;
	}

	public Long getDatMantenimientoEquipoId() {
		return datMantenimientoEquipoId;
	}

	public void setDatMantenimientoEquipoId(Long datMantenimientoEquipoId) {
		this.datMantenimientoEquipoId = datMantenimientoEquipoId;
	}

	public Equipo getImplementoId() {
		return implementoId;
	}

	public void setImplementoId(Equipo implementoId) {
		this.implementoId = implementoId;
	}

	public Long getIndicador_vuelta_medidor() {
		return indicador_vuelta_medidor;
	}

	public void setIndicador_vuelta_medidor(Long indicador_vuelta_medidor) {
		this.indicador_vuelta_medidor = indicador_vuelta_medidor;
	}

	public Long getUsuarioDigitacion() {
		return usuarioDigitacion;
	}

	public void setUsuarioDigitacion(Long usuarioDigitacion) {
		this.usuarioDigitacion = usuarioDigitacion;
	}

	public Double getHorometro_abastecimiento() {
		return horometro_abastecimiento;
	}

	public void setHorometro_abastecimiento(Double horometro_abastecimiento) {
		this.horometro_abastecimiento = horometro_abastecimiento;
	}

	public Trabajador getOperario_equipo_id() {
		return operario_equipo_id;
	}

	public void setOperario_equipo_id(Trabajador operario_equipo_id) {
		this.operario_equipo_id = operario_equipo_id;
	}

	public Nivel2Clientesmq getNivel2_clientesmq_id() {
		return nivel2_clientesmq_id;
	}

	public void setNivel2_clientesmq_id(Nivel2Clientesmq nivel2_clientesmq_id) {
		this.nivel2_clientesmq_id = nivel2_clientesmq_id;
	}

	public Long getNivel4_clientesmq_id() {
		return nivel4_clientesmq_id;
	}

	public void setNivel4_clientesmq_id(Long nivel4_clientesmq_id) {
		this.nivel4_clientesmq_id = nivel4_clientesmq_id;
	}

	public String getTransportadora_nguia() {
		return transportadora_nguia;
	}

	public void setTransportadora_nguia(String transportadora_nguia) {
		this.transportadora_nguia = transportadora_nguia;
	}

	public Double getTransportadora_valor_flete() {
		return transportadora_valor_flete;
	}

	public void setTransportadora_valor_flete(Double transportadora_valor_flete) {
		this.transportadora_valor_flete = transportadora_valor_flete;
	}

	public String getTransportadoraFactura() {
		return transportadoraFactura;
	}

	public void setTransportadoraFactura(String transportadoraFactura) {
		this.transportadoraFactura = transportadoraFactura;
	}

	public String getDiferido() {
		return diferido;
	}

	public void setDiferido(String diferido) {
		this.diferido = diferido;
	}

	public Long getConceptoGastoId() {
		return conceptoGastoId;
	}

	public void setConceptoGastoId(Long conceptoGastoId) {
		this.conceptoGastoId = conceptoGastoId;
	}

	public DatServRealizadosEquipo getDatServRealizadosEquipoId() {
		return datServRealizadosEquipoId;
	}

	public void setDatServRealizadosEquipoId(DatServRealizadosEquipo datServRealizadosEquipoId) {
		this.datServRealizadosEquipoId = datServRealizadosEquipoId;
	}

	public Double getPorcIva() {
		return porcIva;
	}

	public void setPorcIva(Double porcIva) {
		this.porcIva = porcIva;
	}

	public Double getValorIva() {
		return valorIva;
	}

	public void setValorIva(Double valorIva) {
		this.valorIva = valorIva;
	}

	public Trabajador getTrabajador() {
		return trabajador;
	}

	public void setTrabajador(Trabajador trabajador) {
		this.trabajador = trabajador;
	}

	public Long getPrecioProdId() {
		return this.precioProdId;
	}

	public void setPrecioProdId(Long precioProdId) {
		this.precioProdId = precioProdId;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public PersEmpr getPersEmpr() {
		return this.persEmpr;
	}

	public void setPersEmpr(PersEmpr persEmpr) {
		this.persEmpr = persEmpr;
	}

	public Almacen getAlmacenId() {
		return this.almacenId;
	}

	public void setAlmacenId(Almacen almacenId) {
		this.almacenId = almacenId;
	}

	public Long getCompania() {
		return this.compania;
	}

	public void setCompania(Long compania) {
		this.compania = compania;
	}

	public Double getValorUnitario() {
		return this.valorUnitario;
	}

	public void setValorUnitario(Double valorUnitario) {
		this.valorUnitario = valorUnitario;
	}

	public String getInfoAdicional() {
		return this.infoAdicional;
	}

	public void setInfoAdicional(String infoAdicional) {
		this.infoAdicional = infoAdicional;
	}

	public String getInfoAdicional2() {
		return this.infoAdicional2;
	}

	public void setInfoAdicional2(String infoAdicional2) {
		this.infoAdicional2 = infoAdicional2;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Date getFechaInicial() {
		return this.fechaInicial;
	}

	public void setFechaInicial(Date fechaInicial) {
		this.fechaInicial = fechaInicial;
	}

	public Date getFechaFinal() {
		return this.fechaFinal;
	}

	public void setFechaFinal(Date fechaFinal) {
		this.fechaFinal = fechaFinal;
	}

	public Date getFechaVencimiento() {
		return this.fechaVencimiento;
	}

	public void setFechaVencimiento(Date fechaVencimiento) {
		this.fechaVencimiento = fechaVencimiento;
	}

	public UdadMed getUnidadMedida() {
		return this.unidadMedida;
	}

	public void setUnidadMedida(UdadMed unidadMedida) {
		this.unidadMedida = unidadMedida;
	}

	public Double getCantidadCompra() {
		return this.cantidadCompra;
	}

	public void setCantidadCompra(Double cantidadCompra) {
		this.cantidadCompra = cantidadCompra;
	}

	public String getLoteCompraProducto() {
		return this.loteCompraProducto;
	}

	public void setLoteCompraProducto(String loteCompraProducto) {
		this.loteCompraProducto = loteCompraProducto;
	}

	public String getRegistroIca() {
		return this.registroIca;
	}

	public void setRegistroIca(String registroIca) {
		this.registroIca = registroIca;
	}

	public Long getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(Long consecutivo) {
		this.consecutivo = consecutivo;
	}

	public ConceptoKardex getConceptoKardexId() {
		return this.conceptoKardexId;
	}

	public void setConceptoKardexId(ConceptoKardex conceptoKardexId) {
		this.conceptoKardexId = conceptoKardexId;
	}

	public String getTipoMovimiento() {
		return this.tipoMovimiento;
	}

	public void setTipoMovimiento(String tipoMovimiento) {
		this.tipoMovimiento = tipoMovimiento;
	}

	public Long getNumFacturaCompra() {
		return this.numFacturaCompra;
	}

	public void setNumFacturaCompra(Long numFacturaCompra) {
		this.numFacturaCompra = numFacturaCompra;
	}

	public Double getCostoTotal() {
		return this.costoTotal;
	}

	public void setCostoTotal(Double costoTotal) {
		this.costoTotal = costoTotal;
	}

	public Equipo getEquipoId() {
		return this.equipoId;
	}

	public void setEquipoId(Equipo equipoId) {
		this.equipoId = equipoId;
	}

	public DatCompraProductos getDatCompraProductosId() {
		return this.datCompraProductosId;
	}

	public void setDatCompraProductosId(DatCompraProductos datCompraProductosId) {
		this.datCompraProductosId = datCompraProductosId;
	}

	public DatOtrosMovInventario getDatOtrosMovInventarioId() {
		return datOtrosMovInventarioId;
	}

	public void setDatOtrosMovInventarioId(DatOtrosMovInventario datOtrosMovInventarioId) {
		this.datOtrosMovInventarioId = datOtrosMovInventarioId;
	}

	public Nivel2 getNivel2Id() {
		return nivel2Id;
	}

	public void setNivel2Id(Nivel2 nivel2Id) {
		this.nivel2Id = nivel2Id;
	}

	public Nivel4 getNivel4Id() {
		return nivel4Id;
	}

	public void setNivel4Id(Nivel4 nivel4Id) {
		this.nivel4Id = nivel4Id;
	}

	public String getOrigenDatos() {
		return origenDatos;
	}

	public void setOrigenDatos(String origenDatos) {
		this.origenDatos = origenDatos;
	}

	public Long getEtapaId() {
		return etapaId;
	}

	public void setEtapaId(Long etapaId) {
		this.etapaId = etapaId;
	}

	public Long getVariedId() {
		return variedId;
	}

	public void setVariedId(Long variedId) {
		this.variedId = variedId;
	}

	public UbicacionesAlmacen getUbicacionesAlmacen() {
		return ubicacionesAlmacen;
	}

	public void setUbicacionesAlmacen(UbicacionesAlmacen ubicacionesAlmacen) {
		this.ubicacionesAlmacen = ubicacionesAlmacen;
	}

}