package co.com.arcosoft.modelo;

// Generated 08-sep-2015 22:35:03 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private Long productoId;
	private Long claseToxicologica;
	private TipoProducto tipoProducto;
	private Almacen almacen;
	private Long udadMedByUdadMedCosecha;
	private Long centCost;
	private UdadMed udadMedByUdadMedProd;
	private Long elementoCosto;
	private String codigo;
	private String nombre;
	public Long compania;
	private String flujoMovimiento;
	private String esGranel;
	private String observacion;
	private String infoAdicional;
	private String infoAdicional2;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String estado;
	private Set<PrecioPromProd> precioPromProds = new HashSet<PrecioPromProd>(0);
	private Set<DatHerramienta> datHerramientas = new HashSet<DatHerramienta>(0);
	private Set<DatRgtroInvent> datRgtroInvents = new HashSet<DatRgtroInvent>(0);
	private Set<MaduranteProducto> maduranteProductos = new HashSet<MaduranteProducto>(0);
	private Set<IngrActivProd> ingrActivProds = new HashSet<IngrActivProd>(0);
	private Set<EmpaqueProducto> empaqueProductos = new HashSet<EmpaqueProducto>(0);
	private Set<DatAplicProdDet> datAplicProdDets = new HashSet<DatAplicProdDet>(0);
	private Set<DatTransProdDet> datTransProdDets = new HashSet<DatTransProdDet>(0);
	private Set<DatAbastCombustible> datAbastCombustibles = new HashSet<DatAbastCombustible>(0);
	private Set<DatMantenimientoEquipoProd> datMantenimientoEquipoProds = new HashSet<DatMantenimientoEquipoProd>(0);
	private Set<TipoRecursosInsumos> tipoRecursosInsumoses = new HashSet<TipoRecursosInsumos>(0);
    private Set<Equipo> equipos = new HashSet<Equipo>(0);
    private Double saldoMinimo;
    private Double saldoMaximo;
    private String requiereSellos;
    private UbicacionesAlmacen ubicacionesAlmacenId;
    
    private Long usuarioDigitacion;
    private String esFormula;
    
    
	public Producto() {
	}

	public Producto(Long productoId) {
		this.productoId = productoId;
	}

	public Producto(Long productoId, Long claseToxicologica, TipoProducto tipoProducto, Almacen almacen,
			Long udadMedByUdadMedCosecha, Long centCost, UdadMed udadMedByUdadMedProd, Long elementoCosto,
			String codigo, String nombre, Long compania, String flujoMovimiento, String esGranel, String observacion,
			String infoAdicional, String infoAdicional2, Date fechaCreacion, Date fechaModificacion, String estado,
			Set<PrecioPromProd> precioPromProds, Set<DatHerramienta> datHerramientas,
			Set<DatRgtroInvent> datRgtroInvents, Set<MaduranteProducto> maduranteProductos,
			Set<IngrActivProd> ingrActivProds, Set<EmpaqueProducto> empaqueProductos,
			Set<DatAplicProdDet> datAplicProdDets, Set<DatTransProdDet> datTransProdDets,
			Set<DatAbastCombustible> datAbastCombustibles, Set<DatMantenimientoEquipoProd> datMantenimientoEquipoProds,
			Set<TipoRecursosInsumos> tipoRecursosInsumoses, Set<Equipo> equipos,
			Double saldoMinimo, Double saldoMaximo, String requiereSellos, UbicacionesAlmacen ubicacionesAlmacenId, String esFormula) {
		this.productoId = productoId;
		this.claseToxicologica = claseToxicologica;
		this.tipoProducto = tipoProducto;
		this.almacen = almacen;
		this.udadMedByUdadMedCosecha = udadMedByUdadMedCosecha;
		this.centCost = centCost;
		this.udadMedByUdadMedProd = udadMedByUdadMedProd;
		this.elementoCosto = elementoCosto;
		this.codigo = codigo;
		this.nombre = nombre;
		this.compania = compania;
		this.flujoMovimiento = flujoMovimiento;
		this.esGranel = esGranel;
		this.observacion = observacion;
		this.infoAdicional = infoAdicional;
		this.infoAdicional2 = infoAdicional2;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.estado = estado;
		this.precioPromProds = precioPromProds;
		this.datHerramientas = datHerramientas;
		this.datRgtroInvents = datRgtroInvents;
		this.maduranteProductos = maduranteProductos;
		this.ingrActivProds = ingrActivProds;
		this.empaqueProductos = empaqueProductos;
		this.datAplicProdDets = datAplicProdDets;
		this.datTransProdDets = datTransProdDets;
		this.datAbastCombustibles = datAbastCombustibles;
		this.datMantenimientoEquipoProds = datMantenimientoEquipoProds;
		this.tipoRecursosInsumoses = tipoRecursosInsumoses;
		this.equipos= equipos; 
		this.saldoMaximo= saldoMaximo;
		this.saldoMinimo=saldoMinimo;
		this.requiereSellos=requiereSellos;
		this.ubicacionesAlmacenId = ubicacionesAlmacenId;
		this.esFormula=esFormula;
	}
 
	public String getEsFormula() {
		return esFormula;
	}

	public void setEsFormula(String esFormula) {
		this.esFormula = esFormula;
	}

	/**
	 * @return the saldoMinimo
	 */
	public Double getSaldoMinimo() {
		return saldoMinimo;
	}

	/**
	 * @param saldoMinimo the saldoMinimo to set
	 */
	public void setSaldoMinimo(Double saldoMinimo) {
		this.saldoMinimo = saldoMinimo;
	}

	/**
	 * @return the saldoMaximo
	 */
	public Double getSaldoMaximo() {
		return saldoMaximo;
	}

	/**
	 * @param saldoMaximo the saldoMaximo to set
	 */
	public void setSaldoMaximo(Double saldoMaximo) {
		this.saldoMaximo = saldoMaximo;
	}

	public Set<Equipo> getEquipos() {
		return equipos;
	}

	public void setEquipos(Set<Equipo> equipos) {
		this.equipos = equipos;
	}

	public Set<TipoRecursosInsumos> getTipoRecursosInsumoses() {
		return tipoRecursosInsumoses;
	}

	public void setTipoRecursosInsumoses(Set<TipoRecursosInsumos> tipoRecursosInsumoses) {
		this.tipoRecursosInsumoses = tipoRecursosInsumoses;
	}

	public Long getProductoId() {
		return this.productoId;
	}

	public void setProductoId(Long productoId) {
		this.productoId = productoId;
	}

	public Long getClaseToxicologica() {
		return this.claseToxicologica;
	}

	public void setClaseToxicologica(Long claseToxicologica) {
		this.claseToxicologica = claseToxicologica;
	}

	public TipoProducto getTipoProducto() {
		return this.tipoProducto;
	}

	public void setTipoProducto(TipoProducto tipoProducto) {
		this.tipoProducto = tipoProducto;
	}

	public Almacen getAlmacen() {
		return this.almacen;
	}

	public void setAlmacen(Almacen almacen) {
		this.almacen = almacen;
	}

	public Long getUdadMedByUdadMedCosecha() {
		return this.udadMedByUdadMedCosecha;
	}

	public void setUdadMedByUdadMedCosecha(Long udadMedByUdadMedCosecha) {
		this.udadMedByUdadMedCosecha = udadMedByUdadMedCosecha;
	}

	public Long getCentCost() {
		return this.centCost;
	}

	public void setCentCost(Long centCost) {
		this.centCost = centCost;
	}

	public UdadMed getUdadMedByUdadMedProd() {
		return this.udadMedByUdadMedProd;
	}

	public void setUdadMedByUdadMedProd(UdadMed udadMedByUdadMedProd) {
		this.udadMedByUdadMedProd = udadMedByUdadMedProd;
	}

	public Long getElementoCosto() {
		return this.elementoCosto;
	}

	public void setElementoCosto(Long elementoCosto) {
		this.elementoCosto = elementoCosto;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Long getCompania() {
		return this.compania;
	}

	public void setCompania(Long compania) {
		this.compania = compania;
	}

	public String getFlujoMovimiento() {
		return this.flujoMovimiento;
	}

	public void setFlujoMovimiento(String flujoMovimiento) {
		this.flujoMovimiento = flujoMovimiento;
	}

	public String getEsGranel() {
		return this.esGranel;
	}

	public void setEsGranel(String esGranel) {
		this.esGranel = esGranel;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public String getInfoAdicional() {
		return this.infoAdicional;
	}

	public void setInfoAdicional(String infoAdicional) {
		this.infoAdicional = infoAdicional;
	}

	public String getInfoAdicional2() {
		return this.infoAdicional2;
	}

	public void setInfoAdicional2(String infoAdicional2) {
		this.infoAdicional2 = infoAdicional2;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set<PrecioPromProd> getPrecioPromProds() {
		return this.precioPromProds;
	}

	public void setPrecioPromProds(Set<PrecioPromProd> precioPromProds) {
		this.precioPromProds = precioPromProds;
	}

	public Set<DatHerramienta> getDatHerramientas() {
		return this.datHerramientas;
	}

	public void setDatHerramientas(Set<DatHerramienta> datHerramientas) {
		this.datHerramientas = datHerramientas;
	}

	public Set<DatRgtroInvent> getDatRgtroInvents() {
		return this.datRgtroInvents;
	}

	public void setDatRgtroInvents(Set<DatRgtroInvent> datRgtroInvents) {
		this.datRgtroInvents = datRgtroInvents;
	}

	public Set<MaduranteProducto> getMaduranteProductos() {
		return this.maduranteProductos;
	}

	public void setMaduranteProductos(Set<MaduranteProducto> maduranteProductos) {
		this.maduranteProductos = maduranteProductos;
	}

	public Set<IngrActivProd> getIngrActivProds() {
		return this.ingrActivProds;
	}

	public void setIngrActivProds(Set<IngrActivProd> ingrActivProds) {
		this.ingrActivProds = ingrActivProds;
	}

	public Set<EmpaqueProducto> getEmpaqueProductos() {
		return this.empaqueProductos;
	}

	public void setEmpaqueProductos(Set<EmpaqueProducto> empaqueProductos) {
		this.empaqueProductos = empaqueProductos;
	}

	public Set<DatAplicProdDet> getDatAplicProdDets() {
		return this.datAplicProdDets;
	}

	public void setDatAplicProdDets(Set<DatAplicProdDet> datAplicProdDets) {
		this.datAplicProdDets = datAplicProdDets;
	}

	public Set<DatTransProdDet> getDatTransProdDets() {
		return this.datTransProdDets;
	}

	public void setDatTransProdDets(Set<DatTransProdDet> datTransProdDets) {
		this.datTransProdDets = datTransProdDets;
	}

	public Set<DatAbastCombustible> getDatAbastCombustibles() {
		return this.datAbastCombustibles;
	}

	public void setDatAbastCombustibles(Set<DatAbastCombustible> datAbastCombustibles) {
		this.datAbastCombustibles = datAbastCombustibles;
	}

	public Set<DatMantenimientoEquipoProd> getDatMantenimientoEquipoProds() {
		return this.datMantenimientoEquipoProds;
	}

	public void setDatMantenimientoEquipoProds(Set<DatMantenimientoEquipoProd> datMantenimientoEquipoProds) {
		this.datMantenimientoEquipoProds = datMantenimientoEquipoProds;
	}

	public String getRequiereSellos() {
		return requiereSellos;
	}

	public void setRequiereSellos(String requiereSellos) {
		this.requiereSellos = requiereSellos;
	}

	public UbicacionesAlmacen getUbicacionesAlmacenId() {
		return ubicacionesAlmacenId;
	}

	public void setUbicacionesAlmacenId(UbicacionesAlmacen ubicacionesAlmacenId) {
		this.ubicacionesAlmacenId = ubicacionesAlmacenId;
	}

	public Long getUsuarioDigitacion() {
		return usuarioDigitacion;
	}

	public void setUsuarioDigitacion(Long usuarioDigitacion) {
		this.usuarioDigitacion = usuarioDigitacion;
	}

}
