package co.com.arcosoft.modelo;
// Generated 15/08/2019 06:30:30 PM by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * PuntosLubricacion generated by hbm2java
 */
public class PuntosLubricacion  implements java.io.Serializable {


     private Long puntoLubricacionId;
     private Long codigo;
     private String nombre;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Long compania;
     private String infoAdicional1;
     private String infoAdicional2;
     private String estado;

    public PuntosLubricacion() {
    }

    public PuntosLubricacion(Long codigo, String nombre, Date fechaCreacion, Date fechaModificacion, Long compania, String infoAdicional1, String infoAdicional2, String estado) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.compania = compania;
       this.infoAdicional1 = infoAdicional1;
       this.infoAdicional2 = infoAdicional2;
       this.estado = estado;
    }
   
    public Long getPuntoLubricacionId() {
        return this.puntoLubricacionId;
    }
    
    public void setPuntoLubricacionId(Long puntoLubricacionId) {
        this.puntoLubricacionId = puntoLubricacionId;
    }
    public Long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Long getCompania() {
        return this.compania;
    }
    
    public void setCompania(Long compania) {
        this.compania = compania;
    }
    public String getInfoAdicional1() {
        return this.infoAdicional1;
    }
    
    public void setInfoAdicional1(String infoAdicional1) {
        this.infoAdicional1 = infoAdicional1;
    }
    public String getInfoAdicional2() {
        return this.infoAdicional2;
    }
    
    public void setInfoAdicional2(String infoAdicional2) {
        this.infoAdicional2 = infoAdicional2;
    }

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}




}


