package co.com.arcosoft.modelo;

// Generated 05-ago-2015 14:10:19 by Hibernate Tools 4.0.0

/**
 * RestriMaduranteNivel4Id generated by hbm2java
 */
public class RestriMaduranteNivel4Id implements java.io.Serializable {

	private Long restrMaduranteRestMaduId;
	private Long nivel4Nivel4Id;

	public RestriMaduranteNivel4Id() {
	}

	public RestriMaduranteNivel4Id(Long restrMaduranteRestMaduId, Long nivel4Nivel4Id) {
		this.restrMaduranteRestMaduId = restrMaduranteRestMaduId;
		this.nivel4Nivel4Id = nivel4Nivel4Id;
	}

	public Long getRestrMaduranteRestMaduId() {
		return this.restrMaduranteRestMaduId;
	}

	public void setRestrMaduranteRestMaduId(Long restrMaduranteRestMaduId) {
		this.restrMaduranteRestMaduId = restrMaduranteRestMaduId;
	}

	public Long getNivel4Nivel4Id() {
		return this.nivel4Nivel4Id;
	}

	public void setNivel4Nivel4Id(Long nivel4Nivel4Id) {
		this.nivel4Nivel4Id = nivel4Nivel4Id;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RestriMaduranteNivel4Id))
			return false;
		RestriMaduranteNivel4Id castOther = (RestriMaduranteNivel4Id) other;

		return ((this.getRestrMaduranteRestMaduId() == castOther.getRestrMaduranteRestMaduId())
				|| (this.getRestrMaduranteRestMaduId() != null && castOther.getRestrMaduranteRestMaduId() != null
						&& this.getRestrMaduranteRestMaduId().equals(castOther.getRestrMaduranteRestMaduId())))
				&& ((this.getNivel4Nivel4Id() == castOther.getNivel4Nivel4Id())
						|| (this.getNivel4Nivel4Id() != null && castOther.getNivel4Nivel4Id() != null
								&& this.getNivel4Nivel4Id().equals(castOther.getNivel4Nivel4Id())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRestrMaduranteRestMaduId() == null ? 0 : this.getRestrMaduranteRestMaduId().hashCode());
		result = 37 * result + (getNivel4Nivel4Id() == null ? 0 : this.getNivel4Nivel4Id().hashCode());
		return result;
	}

}
