package co.com.arcosoft.modelo;

// Generated 05-ago-2015 14:10:19 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RestrMadurante generated by hbm2java
 */
public class RestrMadurante implements java.io.Serializable {

	private Long restMaduId;
	private String codigo;
	private String nombre;
	private String infoAdicional;
	private String infoAdicional2;
	public Long compania;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String estado;
	private Set<RestriMaduranteNivel4> restriMaduranteNivel4s = new HashSet<RestriMaduranteNivel4>(0);

	public RestrMadurante() {
	}

	public RestrMadurante(Long restMaduId) {
		this.restMaduId = restMaduId;
	}

	public RestrMadurante(Long restMaduId, String codigo, String nombre, Long compania, String infoAdicional,
			String infoAdicional2, Date fechaCreacion, Date fechaModificacion, String estado,
			Set<RestriMaduranteNivel4> restriMaduranteNivel4s) {
		this.restMaduId = restMaduId;
		this.codigo = codigo;
		this.nombre = nombre;
		this.compania = compania;
		this.infoAdicional = infoAdicional;
		this.infoAdicional2 = infoAdicional2;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.estado = estado;
		this.restriMaduranteNivel4s = restriMaduranteNivel4s;
	}

	public Long getRestMaduId() {
		return this.restMaduId;
	}

	public void setRestMaduId(Long restMaduId) {
		this.restMaduId = restMaduId;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getInfoAdicional() {
		return this.infoAdicional;
	}

	public void setInfoAdicional(String infoAdicional) {
		this.infoAdicional = infoAdicional;
	}

	public String getInfoAdicional2() {
		return this.infoAdicional2;
	}

	public void setInfoAdicional2(String infoAdicional2) {
		this.infoAdicional2 = infoAdicional2;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Long getCompania() {
		return this.compania;
	}

	public void setCompania(Long compania) {
		this.compania = compania;
	}

	public Set<RestriMaduranteNivel4> getRestriMaduranteNivel4s() {
		return this.restriMaduranteNivel4s;
	}

	public void setRestriMaduranteNivel4s(Set<RestriMaduranteNivel4> restriMaduranteNivel4s) {
		this.restriMaduranteNivel4s = restriMaduranteNivel4s;
	}

}
