package co.com.arcosoft.modelo;

// Generated 05-ago-2015 14:10:19 by Hibernate Tools 4.0.0

/**
 * RestriMaduranteNivel4 generated by hbm2java
 */
public class RestriMaduranteNivel4 implements java.io.Serializable {

	private RestriMaduranteNivel4Id id;
	private Nivel4 nivel4;
	private RestrMadurante restrMadurante;

	public RestriMaduranteNivel4() {
	}

	public RestriMaduranteNivel4(RestriMaduranteNivel4Id id, Nivel4 nivel4, RestrMadurante restrMadurante) {
		this.id = id;
		this.nivel4 = nivel4;
		this.restrMadurante = restrMadurante;
	}

	public RestriMaduranteNivel4Id getId() {
		return this.id;
	}

	public void setId(RestriMaduranteNivel4Id id) {
		this.id = id;
	}

	public Nivel4 getNivel4() {
		return this.nivel4;
	}

	public void setNivel4(Nivel4 nivel4) {
		this.nivel4 = nivel4;
	}

	public RestrMadurante getRestrMadurante() {
		return this.restrMadurante;
	}

	public void setRestrMadurante(RestrMadurante restrMadurante) {
		this.restrMadurante = restrMadurante;
	}

}
