package co.com.arcosoft.modelo;
// Generated 23-jul-2017 14:00:29 by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * SemanaAnio generated by hbm2java
 */
public class SemanaAnio  implements java.io.Serializable {


     private Long semanaAnioId;
     private AnioFiscal anioFiscal;
     private String codigo;
     private Date fechaInicial;
     private Date fechaFinal;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private String estado;
     private Long compania;

    public SemanaAnio() {
    }

    public SemanaAnio(AnioFiscal anioFiscal, String codigo, Date fechaInicial, Date fechaFinal, Date fechaCreacion, Date fechaModificacion, String estado, Long compania) {
       this.anioFiscal = anioFiscal;
       this.codigo = codigo;
       this.fechaInicial = fechaInicial;
       this.fechaFinal = fechaFinal;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estado = estado;
       this.compania = compania;
    }
   
    public Long getSemanaAnioId() {
        return this.semanaAnioId;
    }
    
    public void setSemanaAnioId(Long semanaAnioId) {
        this.semanaAnioId = semanaAnioId;
    }
    public AnioFiscal getAnioFiscal() {
        return this.anioFiscal;
    }
    
    public void setAnioFiscal(AnioFiscal anioFiscal) {
        this.anioFiscal = anioFiscal;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Date getFechaInicial() {
        return this.fechaInicial;
    }
    
    public void setFechaInicial(Date fechaInicial) {
        this.fechaInicial = fechaInicial;
    }
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Long getCompania() {
        return this.compania;
    }
    
    public void setCompania(Long compania) {
        this.compania = compania;
    }




}


