package co.com.arcosoft.modelo;
// Generated 14-oct-2017 19:44:07 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SistemasEquipo generated by hbm2java
 */
public class SistemasEquipo  implements java.io.Serializable {


     private Long sistemasEquipoId;
     private String codigo;
     private String nombre;
     private Long compania;
     private String infoAdicional;
     private String infoAdicional1;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private String estado;
     private String origenDatos;
     private Set<DatCheckListEquipo> datCheckListEquipos = new HashSet<DatCheckListEquipo>(0);
     private Set<PlanRevisionEquipoDet> planRevisionEquipoDets = new HashSet<PlanRevisionEquipoDet>(0);

    public SistemasEquipo() {
    }

    public SistemasEquipo(String codigo, String nombre, Long compania, String infoAdicional, String infoAdicional1, Date fechaCreacion, Date fechaModificacion, String estado, String origenDatos, Set<DatCheckListEquipo> datCheckListEquipos, Set<PlanRevisionEquipoDet> planRevisionEquipoDets) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.compania = compania;
       this.infoAdicional = infoAdicional;
       this.infoAdicional1 = infoAdicional1;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estado = estado;
       this.origenDatos = origenDatos;
       this.datCheckListEquipos = datCheckListEquipos;
       this.planRevisionEquipoDets = planRevisionEquipoDets;
    }
   
    public Long getSistemasEquipoId() {
        return this.sistemasEquipoId;
    }
    
    public void setSistemasEquipoId(Long sistemasEquipoId) {
        this.sistemasEquipoId = sistemasEquipoId;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Long getCompania() {
        return this.compania;
    }
    
    public void setCompania(Long compania) {
        this.compania = compania;
    }
    public String getInfoAdicional() {
        return this.infoAdicional;
    }
    
    public void setInfoAdicional(String infoAdicional) {
        this.infoAdicional = infoAdicional;
    }
    public String getInfoAdicional1() {
        return this.infoAdicional1;
    }
    
    public void setInfoAdicional1(String infoAdicional1) {
        this.infoAdicional1 = infoAdicional1;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getOrigenDatos() {
        return this.origenDatos;
    }
    
    public void setOrigenDatos(String origenDatos) {
        this.origenDatos = origenDatos;
    }
    public Set<DatCheckListEquipo> getDatCheckListEquipos() {
        return this.datCheckListEquipos;
    }
    
    public void setDatCheckListEquipos(Set<DatCheckListEquipo> datCheckListEquipos) {
        this.datCheckListEquipos = datCheckListEquipos;
    }
    public Set<PlanRevisionEquipoDet> getPlanRevisionEquipoDets() {
        return this.planRevisionEquipoDets;
    }
    
    public void setPlanRevisionEquipoDets(Set<PlanRevisionEquipoDet> planRevisionEquipoDets) {
        this.planRevisionEquipoDets = planRevisionEquipoDets;
    }

}


