package co.com.arcosoft.modelo;
// Generated 19-abr-2016 12:41:38 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TarifaEquipProp generated by hbm2java
 */
public class TarifaEquipProp implements java.io.Serializable {

	private Long tarifaEquipPropId;
	private UdadMed udadMed;
	private Labor labor_tarifa;
	private Equipo equipo;
	private Long compania;
	private Double tarifa;
	private Date fechaInicial;
	private Date fechaFinal;
	private Date fechaCreacion;
	private Date fechaModificacion;
	
	public TarifaEquipProp() {
	}

	public TarifaEquipProp(Long tarifaEquipPropId) {
		this.tarifaEquipPropId = tarifaEquipPropId;
	}

	public TarifaEquipProp(Long tarifaEquipPropId, UdadMed udadMed, Labor labor_tarifa, Equipo equipo, Long compania,
			Double tarifa, Date fechaInicial, Date fechaFinal, Date fechaCreacion, Date fechaModificacion) {
		this.tarifaEquipPropId = tarifaEquipPropId;
		this.udadMed = udadMed;
		this.labor_tarifa = labor_tarifa;
		this.equipo = equipo;
		this.compania = compania;
		this.tarifa = tarifa;
		this.fechaInicial = fechaInicial;
		this.fechaFinal = fechaFinal;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		
	}

	public Long getTarifaEquipPropId() {
		return this.tarifaEquipPropId;
	}

	public void setTarifaEquipPropId(Long tarifaEquipPropId) {
		this.tarifaEquipPropId = tarifaEquipPropId;
	}

	public UdadMed getUdadMed() {
		return this.udadMed;
	}

	public void setUdadMed(UdadMed udadMed) {
		this.udadMed = udadMed;
	}

	public Equipo getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}

	public Long getCompania() {
		return this.compania;
	}

	public void setCompania(Long compania) {
		this.compania = compania;
	}

	public Double getTarifa() {
		return this.tarifa;
	}

	public void setTarifa(Double tarifa) {
		this.tarifa = tarifa;
	}

	public Date getFechaInicial() {
		return this.fechaInicial;
	}

	public void setFechaInicial(Date fechaInicial) {
		this.fechaInicial = fechaInicial;
	}

	public Date getFechaFinal() {
		return this.fechaFinal;
	}

	public void setFechaFinal(Date fechaFinal) {
		this.fechaFinal = fechaFinal;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Labor getLabor_tarifa() {
		return labor_tarifa;
	}

	public void setLabor_tarifa(Labor labor_tarifa) {
		this.labor_tarifa = labor_tarifa;
	}

}
