package co.com.arcosoft.modelo;
// Generated 19-abr-2016 12:41:38 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TarifaContratista generated by hbm2java
 */
public class TarifaContratista implements java.io.Serializable {

	private Long tarifaCtrId;
	private UdadMed udadMed;
	private Labor labor;
	private ConceptoNomina servicio;
	private PersEmpr persEmpr;
	private Long compania;
	private Double tarifa;
	private Date fechaInicial;
	private Date fechaFinal;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private Profesion profesion;
	private Double edadInicial;
	private Double  edadFinal;
	private Double  pesoPromedio;
	private String  estadoIncidencia;
	private Nivel2 nivel2; 
	private Nivel4 nivel4 ;
	private String alturaPlanta;
	
	public TarifaContratista() {
	}

	public TarifaContratista(Long tarifaCtrId) {
		this.tarifaCtrId = tarifaCtrId;
	}

	public TarifaContratista(Long tarifaCtrId, UdadMed udadMed, Labor labor, ConceptoNomina servicio, PersEmpr persEmpr,
			Long compania, Double tarifa, Date fechaInicial, Date fechaFinal, Date fechaCreacion,
			Date fechaModificacion, Profesion profesion,
			 Double edadInicial,
			 Double  edadFinal,
			 Double  pesoPromedio,
			 String  estadoIncidencia,
			 Nivel4 nivel4, Nivel2 nivel2, String alturaPlanta
			) {
		this.tarifaCtrId = tarifaCtrId;
		this.udadMed = udadMed;
		this.labor = labor;
		this.servicio = servicio;
		this.persEmpr = persEmpr;
		this.compania = compania;
		this.tarifa = tarifa;
		this.fechaInicial = fechaInicial;
		this.fechaFinal = fechaFinal;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.profesion = profesion;
		this.edadInicial = edadInicial;
		this.edadFinal = edadFinal; 
		this.pesoPromedio = pesoPromedio;
		this.estadoIncidencia = estadoIncidencia;
		this.nivel4=nivel4;
		this.nivel2=nivel2;
		this.alturaPlanta=alturaPlanta;
	}

	
	
	public String getAlturaPlanta() {
		return alturaPlanta;
	}

	public void setAlturaPlanta(String alturaPlanta) {
		this.alturaPlanta = alturaPlanta;
	}

	public Nivel2 getNivel2() {
		return nivel2;
	}

	public void setNivel2(Nivel2 nivel2) {
		this.nivel2 = nivel2;
	}

	public Nivel4 getNivel4() {
		return nivel4;
	}

	public void setNivel4(Nivel4 nivel4) {
		this.nivel4 = nivel4;
	}

	public Double getEdadInicial() {
		return edadInicial;
	}

	public void setEdadInicial(Double edadInicial) {
		this.edadInicial = edadInicial;
	}

	public Double getEdadFinal() {
		return edadFinal;
	}

	public void setEdadFinal(Double edadFinal) {
		this.edadFinal = edadFinal;
	}

	public Double getPesoPromedio() {
		return pesoPromedio;
	}

	public void setPesoPromedio(Double pesoPromedio) {
		this.pesoPromedio = pesoPromedio;
	}

	public String getEstadoIncidencia() {
		return estadoIncidencia;
	}

	public void setEstadoIncidencia(String estadoIncidencia) {
		this.estadoIncidencia = estadoIncidencia;
	}

	public Profesion getProfesion() {
		return profesion;
	}

	public void setProfesion(Profesion profesion) {
		this.profesion = profesion;
	}

	public Long getTarifaCtrId() {
		return this.tarifaCtrId;
	}

	public void setTarifaCtrId(Long tarifaCtrId) {
		this.tarifaCtrId = tarifaCtrId;
	}

	public UdadMed getUdadMed() {
		return this.udadMed;
	}

	public void setUdadMed(UdadMed udadMed) {
		this.udadMed = udadMed;
	}

	public Labor getLabor() {
		return this.labor;
	}

	public void setLabor(Labor labor) {
		this.labor = labor;
	}

	public ConceptoNomina getServicio() {
		return this.servicio;
	}

	public void setServicio(ConceptoNomina servicio) {
		this.servicio = servicio;
	}

	public PersEmpr getPersEmpr() {
		return this.persEmpr;
	}

	public void setPersEmpr(PersEmpr persEmpr) {
		this.persEmpr = persEmpr;
	}

	public Long getCompania() {
		return this.compania;
	}

	public void setCompania(Long compania) {
		this.compania = compania;
	}

	public Double getTarifa() {
		return this.tarifa;
	}

	public void setTarifa(Double tarifa) {
		this.tarifa = tarifa;
	}

	public Date getFechaInicial() {
		return this.fechaInicial;
	}

	public void setFechaInicial(Date fechaInicial) {
		this.fechaInicial = fechaInicial;
	}

	public Date getFechaFinal() {
		return this.fechaFinal;
	}

	public void setFechaFinal(Date fechaFinal) {
		this.fechaFinal = fechaFinal;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

}
