package co.com.arcosoft.modelo;
// Generated 21-oct-2016 10:50:02 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TarifaInfraestructura generated by hbm2java
 */
public class TarifaInfraestructura implements java.io.Serializable {

	private Long tarInfraId;
	private Infraestructura infraestructura;
	private Date fechaInicial;
	private Date fechaFinal;
	private Double valor;
	private Date fechaCreacion;
	private Date fechaModificacion;

	public TarifaInfraestructura() {
	}

	public TarifaInfraestructura(Long tarInfraId) {
		this.tarInfraId = tarInfraId;
	}

	public TarifaInfraestructura(Long tarInfraId, Infraestructura infraestructura, Date fechaInicial, Date fechaFinal,
			Double valor, Date fechaCreacion, Date fechaModificacion) {
		this.tarInfraId = tarInfraId;
		this.infraestructura = infraestructura;
		this.fechaInicial = fechaInicial;
		this.fechaFinal = fechaFinal;
		this.valor = valor;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
	}

	public Long getTarInfraId() {
		return this.tarInfraId;
	}

	public void setTarInfraId(Long tarInfraId) {
		this.tarInfraId = tarInfraId;
	}

	public Infraestructura getInfraestructura() {
		return this.infraestructura;
	}

	public void setInfraestructura(Infraestructura infraestructura) {
		this.infraestructura = infraestructura;
	}

	public Date getFechaInicial() {
		return this.fechaInicial;
	}

	public void setFechaInicial(Date fechaInicial) {
		this.fechaInicial = fechaInicial;
	}

	public Date getFechaFinal() {
		return this.fechaFinal;
	}

	public void setFechaFinal(Date fechaFinal) {
		this.fechaFinal = fechaFinal;
	}

	public Double getValor() {
		return this.valor;
	}

	public void setValor(Double valor) {
		this.valor = valor;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

}
