package co.com.arcosoft.modelo;
// Generated 24-may-2016 17:14:38 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TarifaLaborRendimiento generated by hbm2java
 */
public class TarifaLaborRendimiento implements java.io.Serializable {

	private Long tarifaLaborId;
	private Labor labor;
	private Long compania;
	private Date fechaInicial;
	private Date fechaFinal;
	private PersEmpr contratistaId;
	private UdadMed udadMedId;
	private Nivel2 nivel2Id;
	private Double rendimiento;
	private Double tarifa;
	private Double bonificacion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private Double rendimientoMax;
    
	
	public TarifaLaborRendimiento() {
	}

	public TarifaLaborRendimiento(Long tarifaLaborId) {
		this.tarifaLaborId = tarifaLaborId;
	}

	public TarifaLaborRendimiento(Long tarifaLaborId, Labor labor, Long compania, Date fechaInicial, Date fechaFinal,
			PersEmpr contratistaId, UdadMed udadMedId, Nivel2 nivel2Id, Double rendimiento, Double tarifa,
			Double bonificacion, Date fechaCreacion, Date fechaModificacion, Double rendimientoMax) {
		this.tarifaLaborId = tarifaLaborId;
		this.labor = labor;
		this.compania = compania;
		this.fechaInicial = fechaInicial;
		this.fechaFinal = fechaFinal;
		this.contratistaId = contratistaId;
		this.udadMedId = udadMedId;
		this.nivel2Id = nivel2Id;
		this.rendimiento = rendimiento;
		this.tarifa = tarifa;
		this.bonificacion = bonificacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.rendimientoMax = rendimientoMax;
	}
	
	

	/**
	 * @return the rendimientoMax
	 */
	public Double getRendimientoMax() {
		return rendimientoMax;
	}

	/**
	 * @param rendimientoMax the rendimientoMax to set
	 */
	public void setRendimientoMax(Double rendimientoMax) {
		this.rendimientoMax = rendimientoMax;
	}

	public Long getTarifaLaborId() {
		return this.tarifaLaborId;
	}

	public void setTarifaLaborId(Long tarifaLaborId) {
		this.tarifaLaborId = tarifaLaborId;
	}

	public Labor getLabor() {
		return this.labor;
	}

	public void setLabor(Labor labor) {
		this.labor = labor;
	}

	public Long getCompania() {
		return this.compania;
	}

	public void setCompania(Long compania) {
		this.compania = compania;
	}

	public Date getFechaInicial() {
		return this.fechaInicial;
	}

	public void setFechaInicial(Date fechaInicial) {
		this.fechaInicial = fechaInicial;
	}

	public Date getFechaFinal() {
		return this.fechaFinal;
	}

	public void setFechaFinal(Date fechaFinal) {
		this.fechaFinal = fechaFinal;
	}

	public PersEmpr getContratistaId() {
		return this.contratistaId;
	}

	public void setContratistaId(PersEmpr contratistaId) {
		this.contratistaId = contratistaId;
	}

	public UdadMed getUdadMedId() {
		return this.udadMedId;
	}

	public void setUdadMedId(UdadMed udadMedId) {
		this.udadMedId = udadMedId;
	}

	public Nivel2 getNivel2Id() {
		return this.nivel2Id;
	}

	public void setNivel2Id(Nivel2 nivel2Id) {
		this.nivel2Id = nivel2Id;
	}

	public Double getRendimiento() {
		return this.rendimiento;
	}

	public void setRendimiento(Double rendimiento) {
		this.rendimiento = rendimiento;
	}

	public Double getTarifa() {
		return this.tarifa;
	}

	public void setTarifa(Double tarifa) {
		this.tarifa = tarifa;
	}

	public Double getBonificacion() {
		return this.bonificacion;
	}

	public void setBonificacion(Double bonificacion) {
		this.bonificacion = bonificacion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

}
