package co.com.arcosoft.modelo;

// Generated 08-sep-2015 22:35:03 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transportadora generated by hbm2java
 */
public class Transportadora implements java.io.Serializable {

	private Long transpId;
	private String codigo;
	private String nombre;
	public Long compania;
	private String nit;
	private String email;
	private String telefono;
	private String direccion;
	private String infoAdicional;
	private String infoAdicional2;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String estado;
	private Set<VehiculosTransp> vehiculosTransps = new HashSet<VehiculosTransp>(0);
	private Set<DatTransProd> datTransProds = new HashSet<DatTransProd>(0);

	public Transportadora() {
	}

	public Transportadora(Long transpId) {
		this.transpId = transpId;
	}

	public Transportadora(Long transpId, String codigo, String nombre, Long compania, String nit, String email,
			String telefono, String direccion, String infoAdicional, String infoAdicional2, Date fechaCreacion,
			Date fechaModificacion, String estado, Set<VehiculosTransp> vehiculosTransps,
			Set<DatTransProd> datTransProds) {
		this.transpId = transpId;
		this.codigo = codigo;
		this.nombre = nombre;
		this.compania = compania;
		this.nit = nit;
		this.email = email;
		this.telefono = telefono;
		this.direccion = direccion;
		this.infoAdicional = infoAdicional;
		this.infoAdicional2 = infoAdicional2;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.estado = estado;
		this.vehiculosTransps = vehiculosTransps;
		this.datTransProds = datTransProds;
	}

	public Long getTranspId() {
		return this.transpId;
	}

	public void setTranspId(Long transpId) {
		this.transpId = transpId;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Long getCompania() {
		return this.compania;
	}

	public void setCompania(Long compania) {
		this.compania = compania;
	}

	public String getNit() {
		return this.nit;
	}

	public void setNit(String nit) {
		this.nit = nit;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getInfoAdicional() {
		return this.infoAdicional;
	}

	public void setInfoAdicional(String infoAdicional) {
		this.infoAdicional = infoAdicional;
	}

	public String getInfoAdicional2() {
		return this.infoAdicional2;
	}

	public void setInfoAdicional2(String infoAdicional2) {
		this.infoAdicional2 = infoAdicional2;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set<VehiculosTransp> getVehiculosTransps() {
		return this.vehiculosTransps;
	}

	public void setVehiculosTransps(Set<VehiculosTransp> vehiculosTransps) {
		this.vehiculosTransps = vehiculosTransps;
	}

	public Set<DatTransProd> getDatTransProds() {
		return this.datTransProds;
	}

	public void setDatTransProds(Set<DatTransProd> datTransProds) {
		this.datTransProds = datTransProds;
	}

}
