package co.com.arcosoft.modelo;

// Generated 08-sep-2015 22:35:03 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ValorVarAnaLab generated by hbm2java
 */
public class ValorVarAnaLab implements java.io.Serializable {

	private Long valorVarAnaLabId;
	private VariableLab variableLab;
	private DatAnaLaboratorio datAnaLaboratorio;
	private String valor;
	private Date fechaCreacion;
	private Date fechaModificacion;

	public ValorVarAnaLab() {
	}

	public ValorVarAnaLab(Long valorVarAnaLabId) {
		this.valorVarAnaLabId = valorVarAnaLabId;
	}

	public ValorVarAnaLab(Long valorVarAnaLabId, VariableLab variableLab, DatAnaLaboratorio datAnaLaboratorio,
			String valor, Date fechaCreacion, Date fechaModificacion) {
		this.valorVarAnaLabId = valorVarAnaLabId;
		this.variableLab = variableLab;
		this.datAnaLaboratorio = datAnaLaboratorio;
		this.valor = valor;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
	}

	public Long getValorVarAnaLabId() {
		return this.valorVarAnaLabId;
	}

	public void setValorVarAnaLabId(Long valorVarAnaLabId) {
		this.valorVarAnaLabId = valorVarAnaLabId;
	}

	public VariableLab getVariableLab() {
		return this.variableLab;
	}

	public void setVariableLab(VariableLab variableLab) {
		this.variableLab = variableLab;
	}

	public DatAnaLaboratorio getDatAnaLaboratorio() {
		return this.datAnaLaboratorio;
	}

	public void setDatAnaLaboratorio(DatAnaLaboratorio datAnaLaboratorio) {
		this.datAnaLaboratorio = datAnaLaboratorio;
	}

	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

}
