package co.com.arcosoft.modelo;
// Generated 19-jun-2016 17:30:58 by Hibernate Tools 4.0.0

/**
 * VariedadNivel4 generated by hbm2java
 */
public class VariedadNivel4 implements java.io.Serializable {

	private Long variedadNivel4Id;
	private Nivel4 nivel4;
	private Variedad variedad;
	private Double porcentajeArea;

	public VariedadNivel4() {
	}

	public VariedadNivel4(Long variedadNivel4Id, Nivel4 nivel4, Variedad variedad) {
		this.variedadNivel4Id = variedadNivel4Id;
		this.nivel4 = nivel4;
		this.variedad = variedad;
	}

	public VariedadNivel4(Long variedadNivel4Id, Nivel4 nivel4, Variedad variedad, Double porcentajeArea) {
		this.variedadNivel4Id = variedadNivel4Id;
		this.nivel4 = nivel4;
		this.variedad = variedad;
		this.porcentajeArea = porcentajeArea;
	}

	public Long getVariedadNivel4Id() {
		return this.variedadNivel4Id;
	}

	public void setVariedadNivel4Id(Long variedadNivel4Id) {
		this.variedadNivel4Id = variedadNivel4Id;
	}

	public Nivel4 getNivel4() {
		return this.nivel4;
	}

	public void setNivel4(Nivel4 nivel4) {
		this.nivel4 = nivel4;
	}

	public Variedad getVariedad() {
		return this.variedad;
	}

	public void setVariedad(Variedad variedad) {
		this.variedad = variedad;
	}

	public Double getPorcentajeArea() {
		return this.porcentajeArea;
	}

	public void setPorcentajeArea(Double porcentajeArea) {
		this.porcentajeArea = porcentajeArea;
	}

}
