package co.com.arcosoft.modelo;

// Generated 05-ago-2015 14:10:19 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Variedad generated by hbm2java
 */
public class Variedad implements java.io.Serializable {

	private Long variedId;
	private Cultivo cultivo;
	private String codigo;
	private String nombre;
	public Long compania;
	private String tipoMaduracion;
	private Double edadCosecha;
	private String infoAdicional;
	private String infoAdicional2;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String estado;
	private String peso;
	private String color;
	private String diametro;
	private String forma;
	private String limpieza;
	private String recepcion;
	private String condicionesRechazo;

	private Set<VariedadNivel4> variedadNivel4s = new HashSet<VariedadNivel4>(0);
	private Set<ProgramaSiembraCosechaDet> programaSiembraCosechaDets = new HashSet<ProgramaSiembraCosechaDet>(0);

	public Variedad() {
	}

	public Variedad(Long variedId) {
		this.variedId = variedId;
	}

	public Variedad(Long variedId, Cultivo cultivo, String codigo, String nombre, Long compania, String tipoMaduracion,
			Double edadCosecha, String infoAdicional, String infoAdicional2, Date fechaCreacion, Date fechaModificacion,
			String estado, String peso, String color, String diametro, String forma, String limpieza, String recepcion,
			String condicionesRechazo, Set<VariedadNivel4> variedadNivel4s,
			Set<ProgramaSiembraCosechaDet> programaSiembraCosechaDets) {
		this.variedId = variedId;
		this.cultivo = cultivo;
		this.codigo = codigo;
		this.nombre = nombre;
		this.compania = compania;
		this.tipoMaduracion = tipoMaduracion;
		this.edadCosecha = edadCosecha;
		this.infoAdicional = infoAdicional;
		this.infoAdicional2 = infoAdicional2;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.estado = estado;
		this.variedadNivel4s = variedadNivel4s;
		this.peso = peso;
		this.color = color;
		this.diametro = diametro;
		this.forma = forma;
		this.limpieza = limpieza;
		this.recepcion = recepcion;
		this.condicionesRechazo = condicionesRechazo;
		this.programaSiembraCosechaDets = programaSiembraCosechaDets;
	}

	public Set<ProgramaSiembraCosechaDet> getProgramaSiembraCosechaDets() {
		return programaSiembraCosechaDets;
	}

	public void setProgramaSiembraCosechaDets(Set<ProgramaSiembraCosechaDet> programaSiembraCosechaDets) {
		this.programaSiembraCosechaDets = programaSiembraCosechaDets;
	}

	public String getPeso() {
		return peso;
	}

	public void setPeso(String peso) {
		this.peso = peso;
	}

	public String getColor() {
		return color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getDiametro() {
		return diametro;
	}

	public void setDiametro(String diametro) {
		this.diametro = diametro;
	}

	public String getForma() {
		return forma;
	}

	public void setForma(String forma) {
		this.forma = forma;
	}

	public String getLimpieza() {
		return limpieza;
	}

	public void setLimpieza(String limpieza) {
		this.limpieza = limpieza;
	}

	public String getRecepcion() {
		return recepcion;
	}

	public void setRecepcion(String recepcion) {
		this.recepcion = recepcion;
	}

	public String getCondicionesRechazo() {
		return condicionesRechazo;
	}

	public void setCondicionesRechazo(String condicionesRechazo) {
		this.condicionesRechazo = condicionesRechazo;
	}

	public Long getVariedId() {
		return this.variedId;
	}

	public void setVariedId(Long variedId) {
		this.variedId = variedId;
	}

	public Cultivo getCultivo() {
		return this.cultivo;
	}

	public void setCultivo(Cultivo cultivo) {
		this.cultivo = cultivo;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Long getCompania() {
		return this.compania;
	}

	public void setCompania(Long compania) {
		this.compania = compania;
	}

	public String getTipoMaduracion() {
		return this.tipoMaduracion;
	}

	public void setTipoMaduracion(String tipoMaduracion) {
		this.tipoMaduracion = tipoMaduracion;
	}

	public Double getEdadCosecha() {
		return this.edadCosecha;
	}

	public void setEdadCosecha(Double edadCosecha) {
		this.edadCosecha = edadCosecha;
	}

	public String getInfoAdicional() {
		return this.infoAdicional;
	}

	public void setInfoAdicional(String infoAdicional) {
		this.infoAdicional = infoAdicional;
	}

	public String getInfoAdicional2() {
		return this.infoAdicional2;
	}

	public void setInfoAdicional2(String infoAdicional2) {
		this.infoAdicional2 = infoAdicional2;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set<VariedadNivel4> getVariedadNivel4s() {
		return this.variedadNivel4s;
	}

	public void setVariedadNivel4s(Set<VariedadNivel4> variedadNivel4s) {
		this.variedadNivel4s = variedadNivel4s;
	}

}
