package co.com.arcosoft.modelo;
// Generated 13-abr-2018 9:41:11 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VariableLab generated by hbm2java
 */
public class VariableLab  implements java.io.Serializable {


     private Long variableLabId;
     private String codigo;
     private String consultaSql;
     private String nombre;
     private String tipoDato;
     private String periocidadVariable;
     private String tipoVariable;
     private String tipoDeAcumulado;
     private String formula;
     private Long compania;
     private String infoAdicional;
     private String infoAdicional2;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private String estado;
     private Integer numeroDecimales;
     private Double valorMinimo;
     private Double valorMaximo;
     private Set<AnaLaboratorioVariable> anaLaboratorioVariables = new HashSet<AnaLaboratorioVariable>(0);
     private Set<DatAnaLaboratorioDet> datAnaLaboratorioDets = new HashSet<DatAnaLaboratorioDet>(0);
     private Long orden;

    public VariableLab() {
    }

    public VariableLab(String codigo, String consultaSql, Long orden, String nombre, String tipoDato, String periocidadVariable, String tipoVariable, String tipoDeAcumulado, String formula, Long compania, String infoAdicional, String infoAdicional2, Date fechaCreacion, Date fechaModificacion, String estado, Integer numeroDecimales, Double valorMinimo, Double valorMaximo, Set<AnaLaboratorioVariable> anaLaboratorioVariables, Set<DatAnaLaboratorioDet> datAnaLaboratorioDets) {
       this.codigo = codigo;
       this.consultaSql = consultaSql;
       this.nombre = nombre;
       this.tipoDato = tipoDato;
       this.periocidadVariable = periocidadVariable;
       this.tipoVariable = tipoVariable;
       this.tipoDeAcumulado = tipoDeAcumulado;
       this.formula = formula;
       this.compania = compania;
       this.infoAdicional = infoAdicional;
       this.infoAdicional2 = infoAdicional2;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estado = estado;
       this.numeroDecimales = numeroDecimales;
       this.valorMinimo = valorMinimo;
       this.valorMaximo = valorMaximo;
       this.anaLaboratorioVariables = anaLaboratorioVariables;
       this.datAnaLaboratorioDets = datAnaLaboratorioDets;
       this.orden = orden;
    }
    
    
   
    /**
	 * @return the orden
	 */
	public Long getOrden() {
		return orden;
	}

	/**
	 * @param orden the orden to set
	 */
	public void setOrden(Long orden) {
		this.orden = orden;
	}

	public Long getVariableLabId() {
        return this.variableLabId;
    }
    
    public void setVariableLabId(Long variableLabId) {
        this.variableLabId = variableLabId;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getConsultaSql() {
		return consultaSql;
	}

	public void setConsultaSql(String consultaSql) {
		this.consultaSql = consultaSql;
	}

	public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipoDato() {
        return this.tipoDato;
    }
    
    public void setTipoDato(String tipoDato) {
        this.tipoDato = tipoDato;
    }
    public String getPeriocidadVariable() {
        return this.periocidadVariable;
    }
    
    public void setPeriocidadVariable(String periocidadVariable) {
        this.periocidadVariable = periocidadVariable;
    }
    public String getTipoVariable() {
        return this.tipoVariable;
    }
    
    public void setTipoVariable(String tipoVariable) {
        this.tipoVariable = tipoVariable;
    }
    public String getTipoDeAcumulado() {
        return this.tipoDeAcumulado;
    }
    
    public void setTipoDeAcumulado(String tipoDeAcumulado) {
        this.tipoDeAcumulado = tipoDeAcumulado;
    }
    public String getFormula() {
        return this.formula;
    }
    
    public void setFormula(String formula) {
        this.formula = formula;
    }
    public Long getCompania() {
        return this.compania;
    }
    
    public void setCompania(Long compania) {
        this.compania = compania;
    }
    public String getInfoAdicional() {
        return this.infoAdicional;
    }
    
    public void setInfoAdicional(String infoAdicional) {
        this.infoAdicional = infoAdicional;
    }
    public String getInfoAdicional2() {
        return this.infoAdicional2;
    }
    
    public void setInfoAdicional2(String infoAdicional2) {
        this.infoAdicional2 = infoAdicional2;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Integer getNumeroDecimales() {
        return this.numeroDecimales;
    }
    
    public void setNumeroDecimales(Integer numeroDecimales) {
        this.numeroDecimales = numeroDecimales;
    }
    public Double getValorMinimo() {
        return this.valorMinimo;
    }
    
    public void setValorMinimo(Double valorMinimo) {
        this.valorMinimo = valorMinimo;
    }
    public Double getValorMaximo() {
        return this.valorMaximo;
    }
    
    public void setValorMaximo(Double valorMaximo) {
        this.valorMaximo = valorMaximo;
    }
    public Set<AnaLaboratorioVariable> getAnaLaboratorioVariables() {
        return this.anaLaboratorioVariables;
    }
    
    public void setAnaLaboratorioVariables(Set<AnaLaboratorioVariable> anaLaboratorioVariables) {
        this.anaLaboratorioVariables = anaLaboratorioVariables;
    }
    public Set<DatAnaLaboratorioDet> getDatAnaLaboratorioDets() {
        return this.datAnaLaboratorioDets;
    }
    
    public void setDatAnaLaboratorioDets(Set<DatAnaLaboratorioDet> datAnaLaboratorioDets) {
        this.datAnaLaboratorioDets = datAnaLaboratorioDets;
    }




}


