package co.com.arcosoft.modelo;

// Generated 05-ago-2015 14:10:19 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ZonaGeografica generated by hbm2java
 */
public class ZonaGeografica implements java.io.Serializable {

	private Long zonaGeograficaId;
	private String codigo;
	private String nombre;
	private String sigla;
	public Long compania;
	private String infoAdicional;
	private String infoAdicional2;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String estado;
	private Set<Nivel2> nivel2s = new HashSet<Nivel2>(0);

	public ZonaGeografica() {
	}

	public ZonaGeografica(Long zonaGeograficaId) {
		this.zonaGeograficaId = zonaGeograficaId;
	}

	public ZonaGeografica(Long zonaGeograficaId, String codigo, String nombre, String sigla, Long compania,
			String infoAdicional, String infoAdicional2, Date fechaCreacion, Date fechaModificacion, String estado,
			Set<Nivel2> nivel2s) {
		this.zonaGeograficaId = zonaGeograficaId;
		this.codigo = codigo;
		this.nombre = nombre;
		this.sigla = sigla;
		this.compania = compania;
		this.infoAdicional = infoAdicional;
		this.infoAdicional2 = infoAdicional2;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.estado = estado;
		this.nivel2s = nivel2s;
	}

	public Long getZonaGeograficaId() {
		return this.zonaGeograficaId;
	}

	public void setZonaGeograficaId(Long zonaGeograficaId) {
		this.zonaGeograficaId = zonaGeograficaId;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getSigla() {
		return this.sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	public Long getCompania() {
		return this.compania;
	}

	public void setCompania(Long compania) {
		this.compania = compania;
	}

	public String getInfoAdicional() {
		return this.infoAdicional;
	}

	public void setInfoAdicional(String infoAdicional) {
		this.infoAdicional = infoAdicional;
	}

	public String getInfoAdicional2() {
		return this.infoAdicional2;
	}

	public void setInfoAdicional2(String infoAdicional2) {
		this.infoAdicional2 = infoAdicional2;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set<Nivel2> getNivel2s() {
		return this.nivel2s;
	}

	public void setNivel2s(Set<Nivel2> nivel2s) {
		this.nivel2s = nivel2s;
	}

}
